### ISSUE TITLE
Cannot create instance of the driver 

### ISSUE THREAD

**Issue by Artem-applitools** [appium/ruby_lib#1012]
## This is a
* [X] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
Getting an error on driver instance creation. Issue happens even before `driver.start_driver`

## Environment
* Appium version (or git revision): 2.0.0-flutter2 (version on sauce labs)
* `ruby_lib` version: 13.0.1 with the `appium_lib_core`: 7.4.0 (prior version works fine)
* Mobile platform/version/device under test: ios and android. 

## Actual behaviour and steps to reproduce
Driver instance not created and throwing an error about undefined method `export_session'. Which was removed from the latest version of the [appium_lib_core](https://github.com/appium/ruby_lib_core/commit/b77460d7e81f74fcc831b8e0636ce014928ea3a8#diff-ba25829070765d1b487bb110890008b9949b3e7d35d5de2d1823b4feba490838L50).

## Expected behaviour
Driver instance should be created without errors. Gemspec for the lib version should contain compatible `appium_lib_core` range of versions

## Ruby logs

```
1.1) Failure/Error: driver = Appium::Driver.new({caps: caps, appium_lib: { server_url: 'https://ondemand.us-west-1.saucelabs.com:443/wd/hub' } }, false)
          
          NoMethodError:
            undefined method `export_session' for #<Appium::Core::Driver:0x000000010b4dcce8 @delegate_target=#<Appium::Core::Driver:0x000000010b4dcce8 ...>, @automation_name=nil, @custom_url="https://ondemand.us-west-1.saucelabs.com:443/wd/hub", @caps=#<Appium::Core::Base::Capabilities:0x000000010b4dc6a8 @capabilities={:browserName=>"", :platformName=>"Android", :"appium:platformVersion"=>"11.0", :"appium:newCommandTimeout"=>600, :"appium:app"=>"storage:filename=SimpleRandomStock_classic.apk", :"appium:deviceName"=>"Google Pixel 5 GoogleAPI Emulator", :"appium:automationName"=>"UiAutomator2", :"appium:orientation"=>"PORTRAIT", :"appium:autoGrantPermissions"=>true, :"sauce:options"=>{:username=>"***", :accessKey=>"***", :name=>"Support Matrix Ruby"}}>, @enable_idempotency_header=true, @default_wait=nil, @port=4723, @wait_timeout=30, @wait_interval=0.5, @listener=nil, @direct_connect=true, @device=:android>
          # /Users/artem/.rvm/gems/ruby-3.2.2/gems/appium_lib-13.0.1/lib/appium_lib/driver.rb:171:in `initialize'
          # ./spec/appium_helper.rb:5:in `new'
          # ./spec/appium_helper.rb:5:in `block (2 levels) in <top (required)>'
          # ./spec/appium_helper.rb:64:in `block (2 levels) in <top (required)>'
```

**Comment by KazuCocoa** [comment]
Thank you for the report. I have submitted a new minor which limits the core lib version right now.
