### ISSUE TITLE
bug: unable to create a driver without the `app` capability

### ISSUE THREAD

**Issue by eglitise** [appium/ruby_lib#1038]
## This is a
* [X] Bug report
* [ ] Question
* [ ] Freature Request

## Summary

When creating a driver by passing a capability set _without_ the `app` capability, the driver fails to be created and returns an error:

```
absolute_app_path invoked and app is not set! (ArgumentError)
```

Could not reproduce this using `ruby_lib` `15.2.0` and identical versions of `ruby_lib_core`.
I believe the issue was likely introduced in #1037.

## Environment
* Appium version (or git revision): 2.11.2
* `ruby_lib` version: 15.2.1
* Mobile platform/version/device under test: Android/iOS

## Actual behaviour and steps to reproduce

Create a driver and pass a capability set that does _NOT_ contain the `app` capability, e.g.

```ruby
url = "http://localhost:4723/"
caps = {"platformName"=>"iOS", "appium:options"=>{"automationName"=>"XCUITest", "deviceName"=>"iPhone", "udid"=>"<udid>", "noReset"=>true, "forceAppLaunch"=>true, "bundleId"=>"<bundle id>"}}
$driver = Appium::Driver.new({ caps: caps, appium_lib: { server_url: url } })
```

This returns an error.

## Expected behaviour

Driver is created fine

## Link to Appium/Ruby logs

N/A

## Any additional comments

N/A

**Comment by KazuCocoa** [comment]
Yes, it looks like ruby_lib's historical place reason. Let me fix that.

**Comment by KazuCocoa** [comment]
Could you try out with 15.2.2?

**Comment by eglitise** [comment]
Working fine now, thanks 👌
