### ISSUE TITLE
Run tests on CI

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#167]
It'd be nice for the tests to automatically run on CI.

**Comment by KazuCocoa** [comment]
We may achieve this with https://docs.travis-ci.com/user/sauce-connect/ .

**Comment by KazuCocoa** [comment]
We can run like https://github.com/KazuCocoa/ruby_lib/blob/travis_return_visible_elements/.travis.yml .
But running all tests for Android/iOS every PR is not suitable, I think.

So, I'll prepare setting examples in https://github.com/appium/ruby_lib/blob/master/contributing.md for them.
