### ISSUE TITLE
can't switch into webview

### ISSUE THREAD

**Issue by wensj** [appium/ruby_lib#180]
I use this code switch into webview:
webview = available_contexts[3]
current_context = web view  

After that,I use "puts get_source”,try to get page source.  It didn't switch into web view correctly.

 {"name":"财酷","type":"UIAApplication","label":"财酷","value":null,"rect":{"origin":{"x":0,"y":20},"size":{"width":320,"height":548}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[{"name":null,"type":"UIAWindow","label":null,"value":null,"rect":{"origin":{"x":0,"y":0},"size":{"width":320,"height":568}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[{"name":null,"type":"UIAScrollView","label":null,"value":null,"rect":{"origin":{"x":64,"y":20},"size":{"width":256,"height":548}},"dom":null,"enabled":true,"valid":true,"visible":false,"children":[{"name":null,"type":"UIAWebView","label":null,"value":null,"rect":{"origin":{"x":64,"y":20},"size":{"width":256,"height":548}},"dom":null,"enabled":true,"valid":true,"visible":false,"children":[],"hint":null},{"name":null,"type":"UIAImage","label":null,"value":null,"rect":{"origin":{"x":64,"y":568},"size":{"width":256,"height":0}},"dom":null,"enabled":true,"valid":true,"visible":false,"children":[],"hint":null}],"hint":null},{"name":null,"type":"UIAScrollView","label":null,"value":null,"rect":{"origin":{"x":0,"y":20},"size":{"width":256,"height":548}},"dom":null,"enabled":true,"valid":true,"visible":false,"children":[{"name":null,"type":"UIAWebView","label":null,"value":null,"rect":{"origin":{"x":0,"y":20},"size":{"width":256,"height":548}},"dom":null,"enabled":true,"valid":true,"visible":false,"children":[],"hint":null},{"name":null,"type":"UIAImage","label":null,"value":null,"rect":{"origin":{"x":0,"y":568},"size":{"width":256,"height":0}},"dom":null,"enabled":true,"valid":true,"visible":false,"children":[],"hint":null}],"hint":null},{"name":"登录","type":"UIAButton","label":"登录","value":null,"rect":{"origin":{"x":0,"y":20},"size":{"width":320,"height":44}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[],"hint":null},{"name":null,"type":"UIAScrollView","label":null,"value":null,"rect":{"origin":{"x":0,"y":64},"size":{"width":320,"height":504}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[{"name":null,"type":"UIAWebView","label":null,"value":null,"rect":{"origin":{"x":0,"y":64},"size":{"width":320,"height":504}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[{"name":null,"type":"UIATextField","label":null,"value":"输入注册手机号","rect":{"origin":{"x":61.5,"y":79.5},"size":{"width":243,"height":44}},"dom":{"id":"username"},"enabled":true,"valid":true,"visible":true,"children":[],"hint":""},{"name":null,"type":"UIASecureTextField","label":null,"value":"输入密码","rect":{"origin":{"x":61.5,"y":124},"size":{"width":198,"height":44}},"dom":{"id":"password"},"enabled":true,"valid":true,"visible":true,"children":[],"hint":""},{"name":"登录","type":"UIAStaticText","label":"登录","value":"","rect":{"origin":{"x":140,"y":195},"size":{"width":40,"height":23}},"dom":{"id":""},"enabled":true,"valid":true,"visible":true,"children":[],"hint":""},{"name":"忘记密码？","type":"UIAStaticText","label":"忘记密码？","value":"","rect":{"origin":{"x":245,"y":240.5},"size":{"width":60,"height":14}},"dom":{"id":""},"enabled":true,"valid":true,"visible":true,"children":[],"hint":""},{"name":"财酷客服热线","type":"UIAStaticText","label":"财酷客服热线","value":"","rect":{"origin":{"x":60,"y":510.5},"size":{"width":72.5,"height":14}},"dom":{"id":""},"enabled":true,"valid":true,"visible":true,"children":[],"hint":""},{"name":"4001-666-333","type":"UIALink","label":"4001-666-333","value":"","rect":{"origin":{"x":159.5,"y":507},"size":{"width":100,"height":18}},"dom":{"id":""},"enabled":true,"valid":true,"visible":true,"children":[{"name":"4001-666-333","type":"UIAStaticText","label":"4001-666-333","value":"","rect":{"origin":{"x":159.5,"y":507},"size":{"width":100,"height":18}},"dom":{"id":""},"enabled":true,"valid":true,"visible":true,"children":[],"hint":""}],"hint":""}],"hint":null},{"name":null,"type":"UIAImage","label":null,"value":null,"rect":{"origin":{"x":0,"y":568},"size":{"width":320,"height":0}},"dom":null,"enabled":true,"valid":true,"visible":false,"children":[],"hint":null}],"hint":null},{"name":"In progress","type":"UIAActivityIndicator","label":"In progress","value":"1","rect":{"origin":{"x":135,"y":180},"size":{"width":50,"height":50}},"dom":null,"enabled":true,"valid":true,"visible":false,"children":[],"hint":null}],"hint":null},{"name":null,"type":"UIAWindow","label":null,"value":null,"rect":{"origin":{"x":0,"y":0},"size":{"width":320,"height":568}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[{"name":null,"type":"UIAStatusBar","label":null,"value":null,"rect":{"origin":{"x":0,"y":0},"size":{"width":320,"height":20}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[{"name":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","type":"UIAElement","label":null,"value":null,"rect":{"origin":{"x":6,"y":0},"size":{"width":38,"height":20}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[],"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top"},{"name":"3 of 3 Wi-Fi bars","type":"UIAElement","label":"3 of 3 Wi-Fi bars","value":null,"rect":{"origin":{"x":49,"y":0},"size":{"width":13,"height":20}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[],"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top"},{"name":"9:31 PM","type":"UIAElement","label":"9:31 PM","value":null,"rect":{"origin":{"x":137,"y":0},"size":{"width":46,"height":20}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[],"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top"},{"name":"100% battery power","type":"UIAElement","label":"100% battery power","value":null,"rect":{"origin":{"x":290,"y":0},"size":{"width":25,"height":20}},"dom":null,"enabled":true,"valid":true,"visible":true,"children":[],"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top"}],"hint":null}],"hint":null}],"hint":null}

**Comment by reach2jeyan** [comment]
I am getting the same error. Is the issue fixed?

**Comment by KazuCocoa** [comment]
I don't know well. Could you create a new issue?
I'll check it later.

**Comment by reach2jeyan** [comment]
@KazuCocoa I am trying to go to safari browser to a website `mailinator.com` and enter the email id over there and click on go.

The text field i am accessing is `xpath` and there is no id in that. This is the desired capabilities, with which I am launching safari
```Then(/^I launch safari browser$/) do
  def caps
    {

        caps:

            {

                udid: "74c2448d14432239c7a4d85e62ceb5e669b04726",
                deviceName: "YIP-25",
                browserName: "Chrome",
                automationName: "XCUITest",
                startIWDP: "true",
                bundleId: "com.google.chrome.ios",
                platformName: "iOS",

            }
    }
  end
  def server_url
    'http://0.0.0.0:4723/wd/hub'
  end

  appium_driver = Appium::Driver.new(caps)
  @Selenium_driver = appium_driver.start_driver
  @Selenium_driver.manage.timeouts.implicit_wait = 60```

And For interacting with elements, i have used all these things but in vain

```And(/^I type "([^"]*)" in textifield$/) do |arg|


  #webview = wait_true { @driver.contexts.last }
  #@driver.switch_to.window(webview)

  #@Selenium_driver.find_element(:xpath, '/XCUIElementTypeOther[@name="Mailinator"]/XCUIElementTypeTextField').send_keys(arg)
  #Selenium_driver.find_element(:xpath, '/AppiumAUT/XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeWebView/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField').send_keys(arg)
  #text = wait_true { exists { Selenium_driver.find_element(id: "GO!").text }}
  #puts text
end


def switch_to_webview
  wait_true { available_contexts.include? 'WEBVIEW_1' }
  set_context 'WEBVIEW_9' unless current_context.equal? 'WEBVIEW'
end

And(/^I click$/) do
  @Selenium_driver.navigate.to "http://www.google.co.in"
  @Selenium_driver.find_element(:id, "Sign in").click
end```

I have installed the safari launcher and also enabled `webkit_proxy`.

Any idea, how do I make `appium_lib` ruby interact with web elements in safari?

**Comment by reach2jeyan** [comment]
@KazuCocoa Well my mistake! I never realised webview is exactly like a desktop view, where its having a different set of elements. `page_source` helped me out.

Thanks :)

**Comment by KazuCocoa** [comment]
:+1:

Have a good testing:)

**Comment by satnam-malhotra** [comment]
@KazuCocoa , I am facing the same issue. How did you resolve it? Could you please share the piece of code that resolved it. thanks!

**Comment by KazuCocoa** [comment]
@satnam-malhotra 
Thanks!
Only I shared is:

1. `page_source` and make sure elements you can get.
2. Make sure switching context with `available_contexts`, `set_context`, `current_context`.
    - If something happens, it's better to create a new issue with the log.
