### ISSUE TITLE
Detect min required appium version

### ISSUE THREAD

**Issue by wensj** [appium/ruby_lib#230]
when I use appium_lib 4.0.0 and appium 1.1.0,I got this error.But when I use appium_lib 3.0.3 and appium 1.1.0,no error.

my code:
allButtons = $driver.buttons

appium log:
info: [BOOTSTRAP] [info] Got command of type ACTION
info: [BOOTSTRAP] [debug] Got command action: find
info: [BOOTSTRAP] [debug] Finding new UiSelector().className(android.widget.Button);new UiSelector().className(android.widget.ImageButton); using ANDROID_UIAUTOMATOR with the contextId: 

info: [BOOTSTRAP] [info] Returning result: {"value":"Could not parse UiSelector argument: Expected \".\" but saw \";\"","status":9}

info: Responding to client with error: {"status":9,"value":{"message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.","origValue":"Could not parse UiSelector argument: Expected \".\" but saw \";\""},"sessionId":"670f07ac-feed-4447-a828-a9e17cf6cc22"}

POST /wd/hub/session/670f07ac-feed-4447-a828-a9e17cf6cc22/elements 500 933ms - 329b

**Comment by KazuCocoa** [comment]
add required Appium server version for XCUITest.
https://github.com/appium/ruby_lib/blob/2a91a6dcd50097101e212b1ed9fc64a470dd95da/lib/appium_lib/driver.rb#L433

If the library requires particular server versions, then the library would like to raise some errors in the future like the above.
