### ISSUE TITLE
Appium::TouchAction.new.long_press does not respect duration

### ISSUE THREAD

**Issue by vfxdrummer** [appium/ruby_lib#231]
I was checking out a failed test, and it seems like Appium::TouchAction.new.long_press does not respect duration.
This was the command that I was using :
Appium::TouchAction.new.long_press(x: 280, y: 530, duration:2000).perform

I have swapped it to this call, and it seems to be working well for me :
Appium::TouchAction.new.press(x: 280, y: 530).wait(2000).release.perform

long_press has the same behavior for any duration value

**Comment by know2script** [comment]
@bootstraponline @vfxdrummer  It been loong time guys. Does this issues got fixed ?

I see that long_press is not reacting for the :duration argument. What @vfxdrummer mentioned is still exist. Please help

**Comment by bootstraponline** [comment]
> It been loong time guys. Does this issues got fixed ?

https://github.com/appium/ruby_lib/issues/337

**Comment by KazuCocoa** [comment]
Is this issue's GOAL raising error if `duration` is set to `long_press` ?
or using `touchLongClick` instead of longPress [here](https://github.com/appium/ruby_lib/blob/8b71cdc81be8f50f5f97f0131aee5f3dc67c3eb7/lib/appium_lib/device/touch_actions.rb#L49) for example ?

**Comment by KazuCocoa** [comment]
According to the following code, `Appium::TouchAction.new.long_press(x: 280, y: 530, duration: 2000).perform` and `Appium::TouchAction.new.press(x: 280, y: 530).wait(2000).release.perform` work as same for now. But I can't find duration option in [appium-ios-driver](https://github.com/appium/appium-ios-driver/search?utf8=%E2%9C%93&q=longPress).

- XCUITest(iOS)
    - https://github.com/appium/appium-xcuitest-driver/blob/f05b8b7c12a67bebe9a6ab2a3833c70424689ca6/lib/commands/gesture.js#L93
- Android
    - https://github.com/appium/appium-android-driver/blob/ab024485ee1e31b8287a7549f343b294a8ebd29b/lib/commands/touch.js#L61

- test codes
    - Android: 
        - https://github.com/appium/appium-android-driver/blob/d615b15319f00181a053664f5ed6f68338a9fd2b/test/unit/commands/touch-specs.js#L96
    - XCUITest:
        - https://github.com/appium/appium-xcuitest-driver/blob/9d89d79d987de324b79452b2b7a7758c0718b310/test/functional/basic/gesture-e2e-specs.js#L62

- Java Client also has same arguments.
    - https://github.com/appium/java-client/blob/c5b9d7bc352edca396940c4a59e0a4a4cf91334d/src/main/java/io/appium/java_client/TouchAction.java

So, I think `duration` works for now except for UIAutomation based iOS driver at least.
`Appium::TouchAction.new.press(x: 280, y: 530).wait(2000).release.perform` is alternative action for long press. So, I add just documentation about it.

**Comment by Pedro1105** [comment]
Gostaria de saber se alguém poderia me ajudar... Preciso de um comando que ele pressione e arraste... alguém sabe ???
Muito obrigada!

**Comment by Pedro1105** [comment]
sasasa
