### ISSUE TITLE
Cannot use .move_to method with Appium::TouchAction.new.press

### ISSUE THREAD

**Issue by isonic1** [appium/ruby_lib#242]
Appium::TouchAction.new.press(x: 212.5, y: 600.0).wait(7000).release.perform lifts the cell which works for the beginning action. However, Appium::TouchAction.new.press(x: 212.5, y: 600.0).wait(7000).move_to(x: 64.0, y: 525.0).release.perform will not move the cell to that location. The app bounces up and down during the wait set time. 

I used to use long_press with duration  (which used to work) but per the appium discussion board that no longer is supposed to work.

**Comment by KazuCocoa** [comment]
according to https://github.com/appium/appium-xcuitest-driver/blob/9d89d79d987de324b79452b2b7a7758c0718b310/test/functional/basic/gesture-e2e-specs.js#L97 , `move_to` may work with `press`.
