### ISSUE TITLE
touch action with duration triggering invalid duration error

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#246]
bug from iOS physical device:

> act = TouchAction.new
> act.swipe start_x: 1.0, start_y: 0.0, end_x: 0.0, end_y: 0.0, duration: 1
> act.perform

The above code should work. Instead it errors with:

> duration value must be greater than or equal to 0.5 or less than 60

**Comment by KazuCocoa** [comment]
Duration should be milliseconds and it's already mentioned in documentations like the following line.

```
    # @option opts [int] :duration How long the actual swipe takes to complete in milliseconds. Default 200.
```
