### ISSUE TITLE
moveTo second attribute should be called offset

### ISSUE THREAD

**Issue by prolificcoder** [appium/ruby_lib#247]
Rest of the appium client examples  and code seems to refer to moveTo second arguments as an offset -
https://github.com/appium/appium/blob/master/lib/server/controller.js#L783
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/appium-bindings.md

Perhaps you should rename them as such (including swipe and anywhere we use the 2nd attribute)

**Comment by KazuCocoa** [comment]
https://github.com/search?q=org%3Aappium+moveTo&type=Code
`moveTo` throws its attributes to the server. So, current `:x` and `:y` is suitable for the server, I think.
