### ISSUE TITLE
update set_wait / no_wait logic

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#249]
the complex set_wait logic around implicit wait duplicates the api that already exists in the selenium webdriver gem. It should be removed.

**Comment by tmulry** [comment]
`set_wait` should be removed from the readme as well. using `default_wait=` is the only way I could get appium to change the global wait time

**Comment by KazuCocoa** [comment]
example

https://github.com/KazuCocoa/ruby_lib/commit/ea06bdca2dd87ad5fdafadabd5b871d7ea8c6b7b
