### ISSUE TITLE
coverage enabled app should be able to launch activites

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#258]
- `https://github.com/appium/appium/pull/3462`

**Comment by KazuCocoa** [comment]
https://github.com/Sw0rdstream/appium/blob/6f11ede8df88d99ef90bc2776b8e9e26f7329242/docs/en/writing-running-appium/android_coverage.md

**Comment by KazuCocoa** [comment]
https://github.com/appium/android-apidemos/blob/a20597cb97238bf43c073500444b9428fab53f50/README.md#emma-build-for-testing-code-coverage

**Comment by KazuCocoa** [comment]
just append documentations for android coverage
