### ISSUE TITLE
scroll_to is not working with 1.2.2

### ISSUE THREAD

**Issue by isonic1** [appium/ruby_lib#262]
The command hangs and eventually times out crashing the appium server. However, this could be the appium server and not necessarily this method. 

info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Test\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains(\"Test\").instance(0));","context":"","multiple":false}]
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Test\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains(\"Test\").instance(0));","context":"","multiple":false}]
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Tried to send command to non-existent Android socket, maybe it's shutting down?"},"sessionId":"a4e02852-248b-499d-8f33-639f2bb29c4b"}

**Comment by bootstraponline** [comment]
There are a few issues with this related to the UiSelector parsing in the appium server. This will hopefully improve in a future release. At this point, it's not a bug in the Ruby bindings.
