### ISSUE TITLE
Multi touch actions have no effect and server log shows Result is not protocol compliant

### ISSUE THREAD

**Issue by aishwaryar** [appium/ruby_lib#265]
I'm using ruby and automating on the IOS 7.1 simulator. I need to pinch and zoom on the image and not the whole page. Swipe seems to have broken. I've tried $driver.pinch 75 and zoom but that seems to hit the corners of the app which causes it to navigate elsewhere. So  I added the muti touch

[{:action=>:press, :options=>{:element=>"2", :x=>150, :y=>300}},
{:action=>:moveTo, :options=>{:element=>"2", :x=>45, :y=>372}},
{:action=>:release, :options=>{:element=>"2"}}],
[{:action=>:press, :options=>{:element=>"2", :x=>190, :y=>300}},
{:action=>:moveTo, :options=>{:element=>"2", :x=>283, :y=>250}},
{:action=>:release, :options=>{:element=>"2"}}]]

Server response is : 
info: --> POST /wd/hub/session/22433c80-586d-43e8-9507-49b6738145d4/touch/multi/perform {"actions":[[{"action":"press","options":{"element":"2","x":150,"y":300}},{"action":"moveTo","options":{"element":"2","x":45,"y":372}},{"action":"release","options":{"element":"2"}}],[{"action":"press","options":{"element":"2","x":190,"y":300}},{"action":"moveTo","options":{"element":"2","x":283,"y":250}},{"action":"release","options":{"element":"2"}}]]}

debug: Appium request initiated at /wd/hub/session/22433c80-586d-43e8-9507-49b6738145d4/touch/multi/perform

debug: Request received with params: {"actions":[[{"action":"press","options":{"element":"2","x":150,"y":300}},{"action":"moveTo","options":{"element":"2","x":45,"y":372}},{"action":"release","options":{"element":"2"}}],[{"action":"press","options":{"element":"2","x":190,"y":300}},{"action":"moveTo","options":{"element":"2","x":283,"y":250}},{"action":"release","options":{"element":"2"}}]]}
debug: Pushing command to appium work queue: "au.getElement('2').rect()"
debug: Sending command to instruments: au.getElement('2').rect()
debug: Sending command to instruments: au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Got new command 25 from instruments: au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluating au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluation finished

(This is where I think my actions going wrong)
debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Result is not protocol compliant, wrapping

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Running system command #26: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":320,"height":64}}}...

debug: Socket data received (80 bytes)

debug: Socket data being routed.
debug: Got result from instruments: {"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":320,"height":64}}}
debug: Pushing command to appium work queue: "au.getElement('2').rect()"
debug: Sending command to instruments: au.getElement('2').rect()
debug: Sending command to instruments: au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Got new command 26 from instruments: au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluating au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluation finished

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Result is not protocol compliant, wrapping

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Running system command #27: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":320,"height":64}}}...

debug: Socket data received (80 bytes)

debug: Socket data being routed.
debug: Got result from instruments: {"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":320,"height":64}}}
debug: Pushing command to appium work queue: "au.getElement('2').rect()"
debug: Sending command to instruments: au.getElement('2').rect()
debug: Sending command to instruments: au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Got new command 27 from instruments: au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluating au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluation finished

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Result is not protocol compliant, wrapping

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Running system command #28: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":320,"height":64}}}...

debug: Socket data received (80 bytes)

debug: Socket data being routed.
debug: Got result from instruments: {"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":320,"height":64}}}
debug: Pushing command to appium work queue: "au.getElement('2').rect()"
debug: Sending command to instruments: au.getElement('2').rect()
debug: Sending command to instruments: au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Got new command 28 from instruments: au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluating au.getElement('2').rect()

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluation finished

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Result is not protocol compliant, wrapping

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Running system command #29: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":320,"height":64}}}...

debug: Socket data received (80 bytes)

debug: Socket data being routed.
debug: Got result from instruments: {"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":320,"height":64}}}
debug: Pushing command to appium work queue: "target.touch([{\"time\":0.2,\"touch\":[{\"x\":150,\"y\":300},{\"x\":190,\"y\":300}]},{\"time\":0.4,\"touch\":[{\"x\":45,\"y\":372},{\"x\":283,\"y\":250}]}])"
debug: Sending command to instruments: target.touch([{"time":0.2,"touch":[{"x":150,"y":300},{"x":190,"y":300}]},{"time":0.4,"touch":[{"x":45,"y":372},{"x":283,"y":250}]}])
debug: Sending command to instruments: target.touch([{"time":0.2,"touch":[{"x":150,"y":300},{"x":190,"y":300}]},{"time":0.4,"touch":[{"x":45,"y":372},{"x":283,"y":250}]}])

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Got new command 29 from instruments: target.touch([{"time":0.2,"touch":[{"x":150,"y":300},{"x":190,"y":300}]},{"time":0.4,"touch":[{"x":45,"y":372},{"x":283,"y":250}]}])

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluating target.touch([{"time":0.2,"touch":[{"x":150,"y":300},{"x":190,"y":300}]},{"time":0.4,"touch":[{"x":45,"y":372},{"x":283,"y":250}]}])

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: target.touch(__NSCFArray)

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: evaluation finished

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Command executed without response

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Result is not protocol compliant, wrapping

debug: [INST] 2014-09-06 15:12:57 +0000 Debug: Running system command #30: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

debug: Socket data received (25 bytes)

info: <-- POST /wd/hub/session/22433c80-586d-43e8-9507-49b6738145d4/touch/multi/perform 200 845.113 ms - 74 {"status":0,"value":"","sessionId":"22433c80-586d-43e8-9507-49b6738145d4"}

debug: Socket data being routed.
debug: Got result from instruments: {"status":0,"value":""}
debug: Responding to client with success: {"status":0,"value":"","sessionId":"22433c80-586d-43e8-9507-49b6738145d4"}

Result is not protocol compliant.

**Comment by slipy12** [comment]
@KazuCocoa I think those methods were refactored, isn't it?

**Comment by KazuCocoa** [comment]
yes, thanks!
