### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#268]
Here's what I'm planning for the Ruby bindings. There's no ETA at the moment. The items are at various stages of completion.
- New Xamarin based sample apps for identical Ruby unit tests across iOS/Android
- Replace minispec with the more well known RSpec framework
- Use new gem for page object pattern
- Rewrite iOS helpers so they're not based on XPath
- Fix failing unit tests (most of these are due to known server issues)
- Attempt running the unit tests on CI once more

Once the basic functionality is confirmed to work well with the new appium server, it'll be much easier to fix the Ruby specific issues.

**Comment by tBStar** [comment]
Any updates the items above would be appreciated.

**Comment by bootstraponline** [comment]
> Any updates the items above would be appreciated.

https://github.com/appium/ruby_lib/issues/337
