### ISSUE TITLE
IOS Appium click and tap inconsistent on simulator and real device.

### ISSUE THREAD

**Issue by srikanthsadhu** [appium/ruby_lib#269]
We had a Popover in our app with some labels , one of it is 'Cancel Record' ,
1) trying to click some times works with xpath , when it doesnt we caught the exception 'could not be tapped' and get the element location and tap the co-ordinates , didnt work.
2)Tried with the BY element with name , didnt work.
3)Tried with name as below and it worked , but only on simulators not on real device , issue from appium server logs pasted below .

Code:
begin

```
 web_element.click
```

   rescue => e
     puts "exception :#{e.backtrace}     in click of:[#{text}] \n so trying to tap at location of element: #{loc.x},#{loc.y}"
     # swipe_co_ord(loc.x,loc.y,loc.x+40,loc.y)  ---didnt work
      touch_co_ord(loc.x+35,loc.y+35) ---didnt work
      long_press_co_ord(loc.x+35,loc.y+35) ---didnt work
      long_press_element(web_element)
     # p @driver.target.front_most_app.main_window.elements 
      @driver.find_element(:name,'Cancel Record').click  ---worked but only on real device
     # @driver.execute_script("mobile: findAndAct", strategy: "name", selector: "Play", action: "click")
   end

Pls. help , exception below:

info: [debug] [INST] 2014-09-15 16:58:51 +0000 Debug: Got new command 437 from instruments: au.getElementByName('Cancel Record')
info: [debug] [INST] 2014-09-15 16:58:51 +0000 Debug: evaluating au.getElementByName('Cancel Record')
info: [debug] Socket data received (40 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"123"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"123"},"sessionId":"82e56de5-b24b-4ca6-bd6d-80f644f05d59"}
info: <-- POST /wd/hub/session/82e56de5-b24b-4ca6-bd6d-80f644f05d59/element 200 1536.304 ms - 89 {"status":0,"value":{"ELEMENT":"123"},"sessionId":"82e56de5-b24b-4ca6-bd6d-80f644f05d59"}
info: --> POST /wd/hub/session/82e56de5-b24b-4ca6-bd6d-80f644f05d59/element/123/click {}
info: [debug] Pushing command to appium work queue: "au.tapById('123')"
info: [debug] Sending command to instruments: au.tapById('123')
info: [debug] [INST] 2014-09-15 16:58:52 +0000 Debug: evaluation finished
info: [debug] [INST] 2014-09-15 16:58:52 +0000 Debug: Lookup returned [object UIATableCell] with the name "Cancel Record" (id: 123).
info: [debug] [INST] 2014-09-15 16:58:52 +0000 Debug: responding with:
info: [debug] [INST] 2014-09-15 16:58:52 +0000 Debug: Running system command #438: /usr/local/Cellar/node/0.10.29/bin/node /Users/ethanlab1/Appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"123"}}...
info: [debug] [INST] 2014-09-15 16:58:53 +0000 Debug: Got new command 438 from instruments: au.tapById('123')
info: [debug] [INST] 2014-09-15 16:58:53 +0000 Debug: evaluating au.tapById('123')
info: [debug] [INST] 2014-09-15 16:58:53 +0000 Debug: UIATableCell.tap()
info: [debug] [INST] 2014-09-15 16:58:53 +0000 Debug: UIATableCell could not be tapped
info: [debug] Socket data received (59 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":13,"value":"elementId 123 could not be tapped"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"elementId 123 could not be tapped"},"sessionId":"82e56de5-b24b-4ca6-bd6d-80f644f05d59"}
info: <-- POST /wd/hub/session/82e56de5-b24b-4ca6-bd6d-80f644f05d59/element/123/click 500 1630.119 ms - 202 
info: --> DELETE /wd/hub/session/82e56de5-b24b-4ca6-bd6d-80f644f05d59 {}
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2014-09-15 16:58:52 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] 2014-09-15 16:58:53 +0000 Error: VerboseError: elementId 123 could not be tapped
info: [debug] [INST] 2014-09-15 16:58:53 +0000 Error: Error during eval: tapById@file:///Users/ethanlab1/Appium/appium/AF28FF32-52D0-4AC6-AE79-93B92A727A55/bootstrap-9df758f291f56293.js:1043:25
       eval code
eval@[native code]
startProcessing@file:///Users/ethanlab1/Appium/appium/AF28FF32-52D0-4AC6-AE79-93B92A727A55/bootstrap-9df758f291f56293.js:2583:30
bootstrap@file:///Users/ethanlab1/Appium/appium/AF28FF32-52D0-4AC6-AE79-93B92A727A55/bootstrap-9df758f291f56293.js:2649:31
global code@file:///Users/ethanlab1/Appium/appium/AF28FF32-52D0-4AC6-AE79-93B92A727A55/bootstrap-9df758f291f56293.js:2658:10
info: [debug] [INST] 2014-09-15 16:58:53 +0000 Debug: responding with:
       2014-09-15 16:58:53 +0000 Debug: Running system command #439: /usr/local/Cellar/node/0.10.29/bin/node /Users/ethanlab1/Appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":13,"value":"elementId 123 could not be tapped"}...

**Comment by slipy12** [comment]
@KazuCocoa I think we could close this one (uses finding by [:name], seems too old)

**Comment by KazuCocoa** [comment]
`:name` depends on back-end server. for example, WebDriverAgent supports `:name` attribute.
But we can close this, I think.

thanks!
