### ISSUE TITLE
appium.txt hardcoded for load_appium_text?

### ISSUE THREAD

**Issue by jmieleiii** [appium/ruby_lib#280]
Going through the [Appium bootcamp](https://saucelabs.com/resources/appium-bootcamp) I noticed an appium.txt file is used to set the capabilities.  It it appears the directory and filename are passed in.  I figured I could extend this to setup a few different text files depending on the build of the app (debug, release candidate, production, etc) which each have slightly different apk names.

From [here](https://github.com/appium/ruby_lib/blob/a13158fb926212d84f26120c3bc5355c8cd34baf/lib/appium_lib/driver.rb#L72)

It appears that the file name appium.txt is actually hardcoded though, specifically at line 81, so passing something like `@caps = Appium.load_appium_txt file: File.join("/path/to/appium/text", "debug_appium.txt")` won't actually load that file, but the appium.txt file instead.

If I'm correct, the current form of the text file loading doesn't really provide much utility when you need change the capabilities for different test configurations.  If I'm not, please enlighten.

**Comment by calin-ciobanu** [comment]
any update on this? I am running parallel tests on multiple devices and would be very useful to be able to specify the config file

**Comment by bootstraponline** [comment]
You can locally make the following change to driver.rb

```diff
-  parent_dir = File.dirname file
-  toml       = File.expand_path File.join parent_dir, 'appium.txt'
+  toml       = File.expand_path file
```

In terms of getting this fixed in the gem, there's a [call for maintainers](https://github.com/appium/ruby_lib/issues/337).

**Comment by calin-ciobanu** [comment]
thank you! :+1:

**Comment by Bojole** [comment]
@calin-ciobanu if you are on Rails application this worked ok for me:
`appium_txt = Rails.root.join('path/to/mobile/production/', 'appium.txt')` for later loading the caps as:
`caps = Appium.load_appium_txt file: appium_txt`

**Comment by droca** [comment]
I'm really interested in having this fix added in the gem as well. For the moment I'll make the changes locally.
