### ISSUE TITLE
Can we integrate the httpproxy with appium ?

### ISSUE THREAD

**Issue by manasatr** [appium/ruby_lib#290]
For selenium web we integrate the proxy like below. 
proxy = Selenium::WebDriver::Proxy.new(:http => "proxy.org:8080")

How do we do for mobile apps using appium.

**Comment by manasatr** [comment]
Caps worked for Firefox browser but it never worked for Mobile.
 platform=MAC, proxy={proxyAutoconfigUrl=null, autodetect=false, socksUsername=null, socksPassword=null, httpProxy=localhost:8080, proxyType=MANUAL, noProxy=null, ftpProxy=localhost:8080, socksProxy=localhost:8080, hCode=122114483, class=org.openqa.selenium.Proxy, sslProxy=localhost:8080}, desired={app=/Users//app/ios/ios-1.14.4-debug-device-app.app, platformVersion=8.1, platformTarget=ios, platformName=iOS, mobile_server_target=Production, deviceName=iPhone Simulator,interface_locale=en_US},

**Comment by bootstraponline** [comment]
@manasatr See https://github.com/appium/appium/issues/4968
