### ISSUE TITLE
rename end_x and end_y to delta_x and delta_y

### ISSUE THREAD

**Issue by wensj** [appium/ruby_lib#293]
I am not sure this is a bug of appium or ruby_lib.The UIAMapView location is {35,83} and size is {250,250}.So I use TouchAction to try to pinch the UIAMapView,like this:
map = find_element :xpath,"//UIAMapView[1]"
puts map.location.x
puts map.location.y

top = Appium::TouchAction.new
top.swipe start_x: 35, start_y: 83, end_x: 65, end_y: 113, duration: 500

bottom = Appium::TouchAction.new
bottom.swipe(start_x: 285,start_y: 333, end_x: 235, end_y: 283, duration: 500)

pinch = Appium::MultiTouch.new
pinch.add top
pinch.add bottom
pinch.perform
I get this error:
point is not within the bounds of the screen (Selenium::WebDriver::Error::JavascriptError)

**Comment by ryanwyu** [comment]
This issue has not been solved even in 8.0.2 release version, which costed us one whole day to find out this issue. 

The new appium server need the client to use the end_x and end_y to get the offset when sending to the server, why the client just sends the end_x, end_y to server. As suggested above, when we use the swipe method, we should treat end_x and end_y as offset_x and offset_y. 

Hope it can be solved in new version.

**Comment by KazuCocoa** [comment]
rename `end_` to `delta_` is included in https://rubygems.org/gems/appium_lib/versions/8.1.0
