### ISSUE TITLE
Android - Handling lists of elements

### ISSUE THREAD

**Issue by kviji** [appium/ruby_lib#299]
Hi,

I am working on a Android project in which there are grids of Models present.
I need to find the total count of models present. I am able to swipe the list and obtain models present.
But the list of models also support duplicate names.
Is there a way in Appium to handle this issue ?

In iOS, on inspecting a screen, all the elements present entirely get detected. I face the issue in Android alone.
Please help.

Regards,
Viji

**Comment by bootstraponline** [comment]
The difference is on iOS, appium is able to detect invisible elements. However on Android, uiautomator & selendroid aren't able to detect invisible elements. I opened an enhancement request on the appium server.

https://github.com/appium/appium/issues/4369

For now you'll probably have to swipe on Android and decide on some heuristic for uniquely identifying the elements (maybe instance number?). This isn't related to a Ruby issue so the best place to discuss is on https://discuss.appium.io
