### ISSUE TITLE
Appium unable to find content decsription

### ISSUE THREAD

**Issue by prathimak** [appium/ruby_lib#300]
I trying to find out content dec using below method but appium not able to find this element,if i am wrong can you guide me 

def check_content_desc? id, text
    begin
      element = driver.find_element(:id, id)
    rescue
      return element.attribute('content-desc')==text
    end
  end

**Comment by bootstraponline** [comment]
Try a [UiSelector](http://developer.android.com/tools/help/uiautomator/UiSelector.html)

> find_element(:uiautomator, "new UiSelector().descriptionMatches(#{value});"

**Comment by prathimak** [comment]
no luck with this method is there any other way i can find element using textview which is of transparent text color

**Comment by prathimak** [comment]
I tried to use find_element(:accessibility_id, 'some id') it returned webdriver element but i am not able to get the text from this

**Comment by bootstraponline** [comment]
If you use uiautomatorviewer, what does it show for the element? If it has text then appium should be able to get it.

**Comment by bootstraponline** [comment]
The unit tests for finding by content description / getting text are passing so I'm pretty sure this isn't a bug in the ruby bindings.
