### ISSUE TITLE
clear method is not working on Android device

### ISSUE THREAD

**Issue by vikramvi** [appium/ruby_lib#308]
Hi,
I'm getting below error while using clear method ( Appium client 1.3.5 )

find_element(:id,'android:id/edit').clear
Selenium::WebDriver::Error::UnknownError: Unknown error clearing text
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:429:in `clearElement'
	from /Users/vikram/.rvm/gems/ruby-2.1.1/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/element.rb:141:in `clear'

Please look into this issue

Thanks & Regards,
Vikram

**Comment by vikramvi** [comment]
this fails in case of multi string text present , if there is single string present , it does work.

Please fix for multi string scenario

**Comment by bootstraponline** [comment]
This is a bug in the appium server. It's unrelated to the Ruby bindings. I recommend opening [an issue on the appium server repo](https://github.com/appium/appium/issues).
