### ISSUE TITLE
allow showing all elements on ios page command

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#310]
apparently people want to show all elements instead of only visible elements, this should be easy to add as an optional arg to the ios page command.

**Comment by cyrilchampier** [comment]
It would indeed allow to write tests in command line instead of avoid to launch the "inspector" to understand the hierarchy of a page.

**Comment by KazuCocoa** [comment]
We can get all elements include hidden view via predicate with the following method.
https://github.com/appium/ruby_lib/blob/2ff78b190f53011c9f0b26777cb1caf64410eaf8/lib/appium_lib/ios/helper.rb#L336


I think we can get all element via `page` with predicate.
https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/ios/helper.rb#L139
