### ISSUE TITLE
within_context swallowing block return value

### ISSUE THREAD

**Issue by maudineormsby** [appium/ruby_lib#311]
within_context always returns "" instead of the value of the block given. It would be nice if it returned the value of the block; for example Capybara has `within_window` which does the same thing but returns the return value of the block.

E.g. https://github.com/jnicklas/capybara/blob/master/lib/capybara/session.rb#L439

**Comment by bootstraponline** [comment]
makes sense, I'd merge a pull request with this feature.

**Comment by maudineormsby** [comment]
I have some appium_capybara things to do this weekend, I'll see if I can get to this.
