### ISSUE TITLE
Eliminate global driver to enable multi-device automation within a single process

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#312]
https://github.com/appium/appium/pull/4752#issuecomment-86674826

**Comment by emlloyd** [comment]
Any updates on when/if this is going to be implemented?

**Comment by bootstraponline** [comment]
> Any updates on when/if this is going to be implemented?

https://github.com/appium/ruby_lib/issues/337

**Comment by KazuCocoa** [comment]
We should avoid global scope to be able to run multi-driver in a single process.

**Comment by KazuCocoa** [comment]
- [ ] create documentations to run multiple sessions
- [ ] implement & run tests with multiple simulators by Xcode
