### ISSUE TITLE
Question about minitest and ruby_lib

### ISSUE THREAD

**Issue by xsmaster** [appium/ruby_lib#315]
Hey all,

I don't know where to ask this so I'm trying here. I would like to use minitest on a few custom calls since we have to use find_element directly. How can should I start the driver in my minitest to call the appium.txt file and start the emulator?

Also if this is not the best place for questions where should I go to post?

Thanks

J

**Comment by bootstraponline** [comment]
minitest works fine. I use a customized version to test the ruby_lib bindings. You can see how I have it [setup here](https://github.com/appium/ruby_lib/blob/d4517b878763523068f99b89b38a1ea3b0a98c4b/android_tests/lib/run.rb#L28). 

- Call Appium.load_appium_txt to parse the appium.txt file
- Pass the caps to Appium::Driver.new(caps) and start the driver
- Register an Minitest.after_run hook to cleanly exit the driver

The emulator will be started by the appium server (use avd in appium.txt [as shown in the getting started code](https://github.com/tourdedave/appium-getting-started-code-exampes/blob/master/6/3/android/appium.txt#L7)).
