### ISSUE TITLE
Adopt angular.js commit message format for auto generating release notes

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#317]
The release notes currently include all commits, even though some aren't relevant. Auto filtering based on prefixes would clean up the release notes.
- https://github.com/angular/angular.js/blob/9dfa949dadbbf97e342d747beda5a3549e3eafd0/CONTRIBUTING.md#commit-message-format

**Comment by KazuCocoa** [comment]
- feature: A new feature
- fix: A bug fix
- docs: Documentation only changes
- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- refactor: A code change that neither fixes a bug nor adds a feature
- test: Adding missing or correcting existing tests
- chore: Changes to the build process or auxiliary tools and libraries such as documentation generation

----

In this case, we can ignore `docs`, `style`, `chore` for release note.
