### ISSUE TITLE
rspec-core-3.2.3 will cause define_singleton_method error

### ISSUE THREAD

**Issue by jmieleiii** [appium/ruby_lib#328]
After updating rspec-core to 3.2.3 I started receiving this error:

```shell
/Users/jmiele/.rvm/gems/ruby-2.1.5/gems/appium_lib-5.0.1/lib/appium_lib/driver.rb:169:in `define_singleton_method': can't define singleton (TypeError)
	from /Users/jmiele/.rvm/gems/ruby-2.1.5/gems/appium_lib-5.0.1/lib/appium_lib/driver.rb:169:in `block (2 levels) in promote_singleton_appium_methods'
```

Reverting back to 3.1.0 allows me to execute without failure

**Comment by bootstraponline** [comment]
Are you invoking `promote_singleton_appium_methods` in your code? Does this happen with appium_lib v6?

**Comment by bootstraponline** [comment]
If you could provide example code that triggers the issue then I'll be able to fix this quickly. 

My guess is adding a `next unless const.respond_to?(:define_singleton_method)` immediately after `$driver.public_methods(false).each do |m|` will resolve the issue.

**Comment by jmieleiii** [comment]
Yes I'm calling that method in my code. This happens on appium_lib 6.0

```ruby
def setup_driver
  return if $driver

  caps = Appium.load_appium_txt file: File.join(Dir.pwd, '/ios/appium.txt')
  caps[:caps][:name] = self.class.metadata[:full_description]

  if using_sauce?
    # SauceLabs related caps
    caps[:caps][:app] = 'sauce-storage:whiteout.zip'
    caps[:caps].delete :avd

    # appium_lib
    caps[:appium_lib][:sauce_username ]  = SAUCE_USERNAME
    caps[:appium_lib][:sauce_access_key] = SAUCE_ACCESS_KEY
  else
    caps[:caps][:app] = '~/appium-test-automation/app/WhiteOut.app'
  end

  Appium::Driver.new caps
end

def promote_methods
  Appium.promote_singleton_appium_methods RSpec::Core::ExampleGroup
  Appium.promote_appium_methods RSpec::Core::ExampleGroup
end

RSpec.configure do |config|
  config.before(:all) do
    startup
  end

  config.after(:all) do
    teardown
  end
end

def startup
  setup_driver
  promote_methods

  $driver.start_driver
end
```

I don't think there's much else I'm doing via code that would impact this.

**Comment by bootstraponline** [comment]
@jmieleiii Thanks, that all the info I need to resolve the problem. Have you tried not invoking the singleton method?

```ruby
def promote_methods
  Appium.promote_appium_methods RSpec::Core::ExampleGroup
end
``` 

I think this would work.

**Comment by jmieleiii** [comment]
Awesome.

I did not try not invoking the method, I just specified the earlier version of rspec in my Gemfile, so not a big deal.

**Comment by bootstraponline** [comment]
> I did not try not invoking the method,

I'm 99% sure that will solve the issue.

**Comment by bootstraponline** [comment]
@jmieleiii I updated [the documentation](https://github.com/appium/ruby_lib/commit/b19d0e03940d80314cb61c3c86f28c6f54e9da57). The TypeError being raised is the correct behavior. The singleton method is never meant to be used except in a specific narrow case of a particular page object design. For RSpec, the `promote_appium_methods` method is correct. Hope this helps. Thanks for reporting the issue.
