### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#337]
The Appium Ruby bindings welcomes new maintainers. Mostly this involves running the iOS/Android test suite and reviewing pull requests. If you're interested and have contributed pull requests, let me know and I'll add you to the Ruby team.

The declining quality of the appium server (objectively measured in terms of passing the Ruby tests) has reduced my enthusiasm for the project. I'm hoping some new maintainers will help keep the Ruby bindings in good condition. As of [the v7 release](https://discuss.appium.io/t/appium-ruby-bindings-appium-lib-v7-0-0-released/4237), I've moved on from appium.

**Comment by hardik-d** [comment]
@bootstraponline this is a little disappointing to hear, i have had hard time maintaining a very small suite of tests i have currently and having to constantly fight test flakiness. I would be happy to contribute in any way i can but if you have better tool suggestion happy to learn about it as well. Also, is it just ruby tests failures or other languages suffer similar problem as well?

**Comment by JaniJegoroff** [comment]
@hardik-d Do you have problems with Android, iOS or both? I'm currently working in a mobile project where we have extensive set of scenarios for Android (iOS work is in progress). The app is fairly simple but we don't have flakiness at all - not even when running on CI.

**Comment by hardik-d** [comment]
@JaniJegoroff my flakiness is on ios but it could be attributed to the app being hybrid. constantly having to struggle with webview/Native view, switching context is flaky and in general my view is appium doesn't do a great job with hybrid apps. More curious here on @bootstraponline comment "The declining quality of the appium server (objectively measured in terms of passing the Ruby tests)". Lot of times my tests fail on just launch and accessing first page or so. native pop ups for notification, location, etc gave me good amount of headaches. accessing/hiding keyboards and webview pop ups are other pain points as well. I am on older lib version for sure.

**Comment by bootstraponline** [comment]
What we use at work now is Espresso for Android and XCTest for iOS. The problems are in the underlying drivers used by appium for ios/android. After creating over [400](https://github.com/appium/appium/issues/created_by/bootstraponline) issues on the appium server alone, it was time to move on. 

I'm very familiar with the flakiness of dealing with webviews in native apps. There's no solution in appium to handle this reliably. The issue impacts everyone and isn't Ruby specific. That's a great example of what I meant about being unable to pass the Ruby tests. Espresso has webview support on Android now which is a plus.

Appium is working well for a bunch of people so I recommend trying your luck with the 1.5 beta. I'm expecting Sauce to take over official maintenance of the Ruby bindings in the future. In the long term appium will be moving to newer automation backends that will solve the reliability issues.

**Comment by titusfortner** [comment]
@bootstraponline - what do you mean by "newer automation backends?" Is that the w3c implementations? And do you know who at Sauce is going to be doing the Ruby bindings?

**Comment by bootstraponline** [comment]
> what do you mean by "newer automation backends?"

Specifically:
- [uiautomator v2 via Selendroid on android](https://github.com/appium/appium-uiautomator2-driver) - replaces the deprecated uiautomator v1 backend
- [XCUITest via webdriver agent](https://github.com/appium/appium-webdriveragent-driver) - replaces the [deprecated instruments backend](https://forums.developer.apple.com/thread/9169)

This is mostly at a conceptual stage (for example there's no XCUITest code written) for now. Once they're a bit more developed then there'll be a formal announcement so people can help out.

> Is that the w3c implementations?

No.

> And do you know who at Sauce is going to be doing the Ruby bindings?

I expect Sauce will communicate that information when they're ready. Note that I'm talking about the appium ruby bindings (`appium/ruby_lib`) and not the general Selenium bindings.

**Comment by titusfortner** [comment]
Great, thanks for the links; I've been in a number of discussions lately about where mobile test automation is going.

So you made the decision to maintain 2 separate test suites, one in Javascript & the other in Java for your mobile testing, rather than trying to get one Ruby suite to do everything you needed it to?

(and since I'm the one who maintains the general Selenium bindings for Ruby I already know that Sauce has no interest in maintaining that code). :)

**Comment by bootstraponline** [comment]
> So you made the decision to maintain 2 separate test suites, one in Javascript & the other in Java for your mobile testing, rather than trying to get one Ruby suite to do everything you needed it to?

Originally we used Ruby across web/ios/android. The mobile tests weren't stable. Now we have 3 suites in different languages. 

- Ruby web test suite ([angular_automation](https://github.com/bootstraponline/angular_automation))
- Java Android suite (Espresso)
- Objective C iOS suite (XCTest)

It's a lot of work but the tests are stable and fast. I hope the new mobile WebDriver technologies are successful because I'd much rather have one language for everything.

**Comment by tk8817** [comment]
Is there any info floating around on whether Sauce will start maintaining the language bindings? Its been sad watching the ruby bindings continue to wither especially after all that hard work that has been put in by the community - especially @bootstraponline.

**Comment by bootstraponline** [comment]
> Is there any info floating around on whether Sauce will start maintaining the language bindings?

I posted this to the internal Appium slack, reposting here for the community.

Sauce Product Management has decided to stop supporting all their Ruby gems, including the appium bindings. As far as I know, there are zero developers from Sauce working on Ruby gems.

> Hi there,
>
> In order to ensure the best possible experience for our users, we are announcing plans to officially end support for the sauce_ruby gem. 
>
> Sauce Labs has not been doing active development for this project for several years. We are making what is already de facto the case official so that users will turn to other more active projects like the selenium-webdriver gem, the parallel_tests gem, and sauce_whisk. For more information please visit our Ruby docs. 
>
> We are planning to mark the gem as deprecated on May 27, 2016.
>
> Thank you, 
>
> Jack Moxon
> Product Manager
> Sauce Labs
>
> https://wiki.saucelabs.com/display/DOCS/2016/05/23/Deprecating+the+sauce_ruby+Gem

**Comment by titusfortner** [comment]
They are at least still working on: https://github.com/saucelabs/sauce_whisk

**Comment by bootstraponline** [comment]
I [disagree](https://github.com/saucelabs/sauce_whisk/pull/54). The code hasn't changed since Feb. PRs take months to review. sauce_whisk does not have any developers assigned to it. One person helping out as time allows is very different from active development from Sauce.

**Comment by titusfortner** [comment]
You mean removing the 'w' in the url in the Readme took too long to fix? If you mean no developer is working full time on this gem, that's definitely true. :)

> [Saucelabs has] decided to stop supporting all their Ruby gems

Is a false statement.

**Comment by hardik-d** [comment]
So basiclally they are pushing ruby app automation community to http://calaba.sh/ ?

**Comment by hardik-d** [comment]
i do not use sauce_ruby only ruby_lib @bootstraponline are you saying ruby_lib will also be dead?

**Comment by titusfortner** [comment]
> watching the ruby bindings continue to wither

What is withering? I'm not seeing a ton of issues being filed here since @bootstraponline asked for maintainers. Are there updates that need to be made?

I'm not a mobile tester. I was given access to this code base so I can fix low hanging fruit if I change something in Selenium and someone says that it breaks something here (which Selenium 3 may or may not do). 

A heavy theme of this thread is that Appium itself is struggling as a project. Several Rubyists I trust switched from Appium to Calabash last year because it worked better for them. I don't know if that is still or will continue to be the case.

**Comment by bootstraponline** [comment]
> [Saucelabs has] decided to stop supporting all their Ruby gems
> Is a false statement.

I don't think so having talked with the maintainer of sauce_whisk & employees at Sauce. If you'd like to classify minimal activity as "support" then I guess that's up for debate.

It's more accurate to say that Sauce has zero full time developers on any of their Ruby projects.

**Comment by bootstraponline** [comment]
> i do not use sauce_ruby only ruby_lib @bootstraponline are you saying ruby_lib will also be dead?

I'm saying that ruby_lib is "community maintained" just like almost all the other Ruby gems. This is a shift in strategy as at one point Sauce was considering investing development resources in their Ruby ecosystem.

calabash has full time development resources so they appear to be in a more competitive position right now, at least in terms of Ruby support.

**Comment by hardik-d** [comment]
perfect timing for me, since have a new project kick starting. Will give calabash a go this time around. Almost wasted 1.5 year on appium.

**Comment by tk8817** [comment]
We moved to Calabash from Appium about 4 months ago. @titusfortner from my view (looking at other language bindings), the ruby_lib is lagging behind  especially since the appium-core rewrite in release 1.5. I mean, the last serious update to ruby_lib was 6 months ago. 

I am sad to see in writing that Sauce are dropping support for those gems - we never depended on them, but I know many who do. With Microsoft purchasing Xamarin I was worried, but there has been a noted uptick in support and development. 

Overall, neither Appium or Calabash are 'great' - and we are close to just moving everything to Earl Grey and biting the bullet that Ruby is not the right entry point for iOS testing.

**Comment by hardik-d** [comment]
Interesting most of my problems have been android, after some sincere efforts all my ios test are reliable on appium.

**Comment by titusfortner** [comment]
I'd like to see Appium succeed, but I suspect it will take getting Google & Apple to provide better built in support. Google has developed chromedriver for many years & Apple is releasing their own safaridriver for MacOS Sierra, so that support isn't out of the question, I just don't see it soon.

**Comment by bootstraponline** [comment]
For what it's worth, I've been very happy with EarlGrey & Espresso. Google continues to make a significant investment in their testing frameworks. I think on a technical level, there's no way Ruby can achieve similar performance and stability in the mobile testing space for native app automation.

**Comment by tk8817** [comment]
@titusfortner, I think you hit the nail on the head with your comment. It is a noble pursuit that appium/frank/calabash/etc.. have taken up, but there is only so much communities can weather when the OS owners are not playing ball. The decline of SafariDriver in recent years is an apt example,and I imagine many are very excited to see Apple take a role in driving it now.

Big thanks to all the key open source players who have gotten us this far :)

**Comment by amias-channer** [comment]
I could possibly help

**Comment by bootstraponline** [comment]
> I could possibly help

What's your email? I'll invite you to the appium development slack.

**Comment by amias-channer** [comment]
me AT Amias DOT net

**Comment by bootstraponline** [comment]
Invite sent.
