### ISSUE TITLE
Selenium WebDriver API Support Code Generation

### ISSUE THREAD

**Issue by tBStar** [appium/ruby_lib#338]
It would nice to have the option to record with Selenium API or Appium_Lib.

Thanks,
Fahd

**Comment by bootstraponline** [comment]
[appium.app](https://github.com/appium/appium-dot-app) already supports Ruby recording. Feature requests about recording should be made on that repo (or [appium.exe](https://github.com/appium/appium-dot-exe) if you use windows).
