### ISSUE TITLE
AbstractEventListener support

### ISSUE THREAD

**Issue by brbrr** [appium/ruby_lib#339]
It would be great to support selenium AbstractEventListener in appium. looks like not hard to implement

**Comment by bootstraponline** [comment]
I think we already support this. Have you [tried the example](https://github.com/SeleniumHQ/selenium/blob/51fd82ec9cb1ebe7596bf7bb3fb8290113466a9a/rb/lib/selenium/webdriver/support/abstract_event_listener.rb#L28)? Everything in the selenium ruby gem is also in the appium gem, including AbstractEventListener.

**Comment by bootstraponline** [comment]
Oh, it looks like we need to add a listener parameter to [driver initialization](https://github.com/appium/ruby_lib/blob/252e83806318df7df28e9060d3f8e1e56dc732ba/lib/appium_lib/driver.rb#L484).

**Comment by brbrr** [comment]
Yup, new parameter should be sent there. but I'm not sure where to put it. In to driver initialize method or simple accessor for that parameter?

**Comment by KazuCocoa** [comment]
I merged in Add EventListener to Driver #389
