### ISSUE TITLE
Logging has been removed?

### ISSUE THREAD

**Issue by umara123** [appium/ruby_lib#340]
Just upgraded from appium_lib 5 to appium_lib 7 and noticed that when I run my tests using cucumber the debugging output does not appear anymore.

Is this intentional? I searched but couldn't see any change documentation for this.

Cheers,

**Comment by umara123** [comment]
ok I found the documentation which says it is intentional on this page https://discuss.appium.io/t/appium-ruby-bindings-appium-lib-v7-0-0-released/4237


If anyone's wondering, logging is now configurable and can be enabled using something like this:
```
Appium::Logger.level = ::Logger::DEBUG
```

**Comment by bootstraponline** [comment]
for what it's worth, this is clearly documented [in the homepage readme.](https://github.com/appium/ruby_lib#logging)

**Comment by umara123** [comment]
Ah yes completely missed that, thanks!

By the way, it's a shame that you're leaving the ruby bindings for appium :( your work and support has been greatly appreciated. Good luck with your future endeavours!

**Comment by bootstraponline** [comment]
Thanks! I'm hoping Sauce Labs will decide to invest in Ruby support (both for appium and their sauce gems) and appoint a new maintainer.
