### ISSUE TITLE
scroll_to and scroll_to_exact is not working on android ruby on android.webkit.WebView

### ISSUE THREAD

**Issue by prathimak** [appium/ruby_lib#341]
I have to verify page must scroll up and down but page is big page and android.webkit.WebView.
I tried to use scroll_to and scroll_to_exact both are not working is there any other way i can verify.

**Comment by JaniJegoroff** [comment]
What do you mean by "not working"? Do you see any errors?
What is your Appium server version?
Are you aware of this Appium server issue: https://github.com/appium/appium/issues/4482

**Comment by prathimak** [comment]
No element found (Selenium::WebDriver::Error::NoSuchElementError) and appium version: 1.3.7

**Comment by JaniJegoroff** [comment]
We need to see more logs to be able to help.

Are you switching context between native app and Webview?
Have you tried Appium server version 1.4.0?

**Comment by prathimak** [comment]
no i am not switching context between native app and Webview, no i have't tried on 1.4.0

**Comment by bootstraponline** [comment]
This is a feature, not a bug. Most of the helpers in ruby_lib are designed exclusively for the native context. They will not work in a webview. Scrolling in a webview should be done via either the mobile scroll or standard selenium methods. The ruby bindings expose the full selenium api.
