### ISSUE TITLE
IOS Safari always launches to http://127.0.0.1:4723/welcome

### ISSUE THREAD

**Issue by chris1248** [appium/ruby_lib#343]
Every time I start up IOS Safari through this ruby library, it always launches at 
`http://127.0.0.1:4723/welcome`

This is even before I can navigate to a page.
I'd like a simple blank page, because that would be a lot faster.

How can I fix this?

Here is the **ruby** script I'm using:

    require 'appium_lib'
    desired_caps = {
      caps:       {
        platformName: 'iOS',
        platformVersion: '8.3',
        deviceName:    'iPad Air',
        browserName:   'Safari'
      }
    }
    # Start the driver
    driver = Appium::Driver.new(desired_caps)
    driver = driver.start_driver # <---------------- Loads that default page HERE!!!! 
    driver.get("http://www.google.com")

I am using appium from the command line. Basically version 1.4+
This appium_lib I am using is version 6.0

**Comment by JaniJegoroff** [comment]
Look at the Appium server code: https://github.com/appium/appium/blob/master/lib/devices/ios/ios.js#L1615

Set `safariInitialUrl` in capabilities: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

**Comment by chris1248** [comment]
Thanks Jani.
I can confirm that I can set that capability, and it indeed does browse to it.
i.e.

    desired_caps = {
      caps:       {
        platformName: 'iOS',
        platformVersion: '8.3',
        deviceName:    'iPad Air',
        browserName:   'Safari',
        safariInitialUrl: 'www.github.com'
      },

Now how can I prevent it from browsing to a page altogether? As in just launch safari, and don't try to navigate to a URL?

**Comment by chris1248** [comment]
bump?

**Comment by chris1248** [comment]
I think this is an issue in appium itself, not in this ruby library.
