### ISSUE TITLE
Pluggable backends for the helpers

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#344]
The Android helpers use uiselectors and the iOS helpers use _elementOrElementsByType. For some apps, the old xpath implementation works better. Until alternative server automation backends exist which enable reliable finding and interacting of elements, it might make sense to allow the user to select which backend powers the helpers. Currently the only option is to use the default implementation as xpath has numerous issues on both android/ios which still remain unresolved as appium server issues (the bugs are ultimately in uiautomator/instruments).

**Comment by KazuCocoa** [comment]
- XPath for Android
    - https://github.com/appium/ruby_lib/blob/27e10f8ba310ce933171b169607172e593344ad7/lib/appium_lib/android/helper.rb#L255
