### ISSUE TITLE
Running `rake android[test]` fails

### ISSUE THREAD

**Issue by jraczak** [appium/ruby_lib#348]
Finished in 30 secs

  1) Error:
spec home, accessibility, and animation#test_0001_spec:
Timeout::Error: execution expired
    /Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:43:in `sleep'
    /Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:43:in `rescue in block in wait'
    /Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:38:in `block in wait'
    /Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:36:in `wait'
    /Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/driver.rb:161:in `rescue in block (3 levels) in promote_singleton_appium_methods'
    /Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/driver.rb:158:in `block (3 levels) in promote_singleton_appium_methods'
    /usr/local/lib/node_modules/appium/appium/submodules/ApiDemos/tutorial/projects/ruby_android/appium/android/pages/home.rb:32:in `assert'
    /usr/local/lib/node_modules/appium/appium/submodules/ApiDemos/tutorial/projects/ruby_android/appium/android/pages/home.rb:9:in `accessibility_click'
    /usr/local/lib/node_modules/appium/appium/submodules/ApiDemos/tutorial/projects/ruby_android/appium/android/specs/test.rb:6:in `block (2 levels) in <top (required)>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
delete 

Understand this is a failure to locate the element. This is built from the tutorial. What needs to be updated?

**Comment by JaniJegoroff** [comment]
From what tutorial this is built from? At least `appium_lib` version looks super old.

**Comment by jraczak** [comment]
The tutorial from the Appium documentation. 

http://appium.io/slate/en/tutorial/android.html?ruby

**Comment by JaniJegoroff** [comment]
I can't use that link to get to the right location. Is it this one?
https://github.com/appium/tutorial/tree/master/projects/ruby_android

**Comment by jraczak** [comment]
Sorry about that.

http://appium.io/slate/en/tutorial/android.html?ruby#running-the-test

**Comment by JaniJegoroff** [comment]
No worries, I see few others also complaining about broken/outdated tests. Please report any issues related to those tutorial tests here: https://github.com/appium/tutorial/issues

If you agree, I'm going to close this issue since it's not relevant to `appium_lib` project.

**Comment by jraczak** [comment]
Ok, I'm going to copy-paste post there. Thanks!
