### ISSUE TITLE
method app_installed? always returning true.

### ISSUE THREAD

**Issue by wili3** [appium/ruby_lib#350]
I'm trying to verify if the facebook app is installed so, I'm calling the method 'app_installed?' with the arg 'com.facebook'.

The problem is that no matter what argument I send to this method, because is always returning true.

app_installed? 'com.example' 
=> true

I though that the server was checking the bundle Id of the app provided in the capabilities but the server log shows the same string that I send to the method app_installed?.

this is the server log after call that method.

info: --> POST /wd/hub/session/898faf54-f2b3-4c12-bc73-eb2c468ca7a8/appium/device/app_installed {"bundleId":"blablabla"}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"898faf54-f2b3-4c12-bc73-eb2c468ca7a8"}
info: <-- POST /wd/hub/session/898faf54-f2b3-4c12-bc73-eb2c468ca7a8/appium/device/app_installed 200 1558.014 ms - 76 {"status":0,"value":true,"sessionId":"898faf54-f2b3-4c12-bc73-eb2c468ca7a8"}
 
I don't know if it's a bug or if I'm doing something wrong.

**Comment by sofaking** [comment]
Cannot reproduce. 
```ruby
> app_installed? 'com.example'
=> false
```
Could you provide more information, logs probably? (better without blablabla)
```js
info: --> POST /wd/hub/session/c06918bb-26aa-4021-903c-0846a90bbe2e/appium/device/app_installed {"bundleId":"com.example"}
info: [debug] Getting install status for com.example
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/aup/Library/Android/sdk/platform-tools/adb -s 048892632523cee2 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 22
info: [debug] executing cmd: /Users/aup/Library/Android/sdk/platform-tools/adb -s 048892632523cee2 shell "pm list packages -3 com.example"
info: [debug] App is not installed
info: [debug] Responding to client with success: {"status":0,"value":false,"sessionId":"c06918bb-26aa-4021-903c-0846a90bbe2e"}
info: <-- POST /wd/hub/session/c06918bb-26aa-4021-903c-0846a90bbe2e/appium/device/app_installed 200 436.282 ms - 77 {"status":0,"value":false,"sessionId":"c06918bb-26aa-4021-903c-0846a90bbe2e"}
```

**Comment by wili3** [comment]
ouch, is this method only available for Android?

**Comment by wili3** [comment]
app_installed? 'com.example'
=> true

info: --> POST /wd/hub/session/7593b59e-96de-4dce-a993-130c60630ddb/appium/device/app_installed {"bundleId":"com.example"}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"7593b59e-96de-4dce-a993-130c60630ddb"}
info: <-- POST /wd/hub/session/7593b59e-96de-4dce-a993-130c60630ddb/appium/device/app_installed 200 1549.961 ms - 76 {"status":0,"value":true,"sessionId":"7593b59e-96de-4dce-a993-130c60630ddb"}

**Comment by JaniJegoroff** [comment]
Please, always add details what Appium server version you are using.

**Comment by wili3** [comment]
appium server version => 1.4.8

**Comment by wili3** [comment]
further information:

-test executed in iOS real device

-server running on mac os

If more information required please tell me. Thanks in advance.

**Comment by JaniJegoroff** [comment]
Unable to reproduce in simulator:
`appium server 1.4.10`
`iPhone 6, 8.4 Simulator`
```
[5] pry(main)> app_installed? 'com.example'
false
```
```
info: --> POST /wd/hub/session/be1da7e4-be23-4e68-adfa-66703af2d33b/appium/device/app_installed {"bundleId":"com.example"}
info: [debug] Responding to client with success: {"status":0,"value":false,"sessionId":"be1da7e4-be23-4e68-adfa-66703af2d33b"}
info: <-- POST /wd/hub/session/be1da7e4-be23-4e68-adfa-66703af2d33b/appium/device/app_installed 200 0.817 ms - 77 {"status":0,"value":false,"sessionId":"be1da7e4-be23-4e68-adfa-66703af2d33b"}
```

**Comment by sofaking** [comment]
I looked a bit into appium sources and it seems this command shouldn't work on simulator at all. Will check on real device tomorrow and get back with results.

**Comment by wili3** [comment]
I found the cause

After a few tries I realized that this issue happens, in 1.4.8 and in 1.4.10 version as  well only if you initialize the appium server with the -U (udid) option, it happens in the Appium.app if you check the udid option inside iOS launch options.

And happens if running appium from source when running => node . -U

Hope it helps.

**Comment by wili3** [comment]
Should I or someone create this issue in another repo since It's a server issue?

**Comment by JaniJegoroff** [comment]
Yes, create issue for Appium main repo. Well done by debugging this issue further. :+1:
