### ISSUE TITLE
can't get text from vebview element

### ISSUE THREAD

**Issue by kingangelTOT** [appium/ruby_lib#351]
appium_lib (7.0.0)
selenium-webdriver (2.47.1, 2.46.2)

I can get element by name, value is 历史红包

<android.webkit.WebView index="0" text="" class="android.webkit.WebView" package="me.ele" content-desc="我的红包" checkable="false" checked="false" clickable="false" enabled="true" focusable="true" focused="true" scrollable="true" long-clickable="false" password="false" selected="false" bounds="[0,243][1080,1776]" resource-id="" instance="1">
                  <android.view.View index="0" text="" class="android.view.View" package="me.ele" content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,243][1080,381]" resource-id="" instance="2">
                    <android.view.View index="0" text="" class="android.view.View" package="me.ele" content-desc="可用红包" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[3,246][540,378]" resource-id="" instance="3"/>
                    <android.view.View index="1" text="" class="android.view.View" package="me.ele" content-desc="历史红包" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[540,246][1077,372]" resource-id="" instance="4"/>
                  </android.view.View>

but didn't get text 

cucumber:
Scenario: 红包功能测试
		Given 定位单个元素 我的红包, 定位条件 uiautomator, 定位信息 new UiSelector().text("我的红包")
		When 点击元素 我的红包
		Given 获取元素 我的红包 的文本信息

		Given 定位单个元素 历史红包, 定位条件 name, 定位信息 历史红包
		When 点击元素 历史红包
		Given 获取元素 历史红包 的文本信息
		Given 定位单个元素 可用红包, 定位条件 name, 定位信息 可用红包
		When 点击元素 可用红包
		Given 定位单个元素 红包数量, 定位条件 xpath, 定位信息 //android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.FrameLayout[2]/android.widget.FrameLayout[1]/android.webkit.WebView[1]/android.webkit.WebView[1]/android.view.View[2]
		Given 获取元素 红包数量 的文本信息
		And 查看所有元素的文本信息

		And 点击返回键
		When 点击元素 我的红包

step:
Given /^定位单个元素 (.*), 定位条件 (.*), 定位信息 (.*)$/ do |element_name, by, value|
	# puts "元素名称:#{element_name}, 定位条件:#{by}, 定位信息:#{value}"
	@element = @driver.first(by, value)
	raise "元素名称重复...请改名..." if @element_cache.has_key?(element_name)
	@element_cache[element_name] = @element
end

Given /^定位多个元素, 定位条件 (.*), 定位信息 (.*)$/ do |by, value|
	@elements = @driver.all(by, value)
end

Given /^从多个元素中获取第 (.*) 个元素 (.*),索引: (.*)$/ do |index, element_name|
	raise "数组越界....." if @elements.size < index + 1 
	@element = @elements[index.to_i]
	raise "元素名称重复...请改名..." if @element_cache.has_key?(element_name)
	@element_cache[element_name] = @element
end

Given /获取元素缓存/ do
	puts @element_cache
end

When /^submit元素 (.*)$/ do |element_name|
	raise "元素对象中没有次元素,请确认元素名称是否正确,或者次元素已经被定位过....." if !@element_cache.has_key?(element_name)
	@element_cache[element_name].submit
end

When /^点击元素 (.*)$/ do |element_name|
	raise "元素对象中没有次元素,请确认元素名称是否正确,或者次元素已经被定位过....." if !@element_cache.has_key?(element_name)
	@element_cache[element_name].click
end

When /^输入数据 (.*), 到元素 (.*) 中去$/ do |value, element_name|
	raise "元素对象中没有次元素,请确认元素名称是否正确,或者次元素已经被定位过....." if !@element_cache.has_key?(element_name)
	element = @element_cache[element_name]
	element.click
	element.send_keys(value)
end

Given /^获取元素 (.*) 的文本信息$/ do |element_name|
	text = @element_cache[element_name].text
	@element_text_cache[element_name] = text
end

And /^查看所有元素的文本信息$/ do
	puts @element_text_cache
end

result:       {"我的红包"=>"我的红包", "历史红包"=>"", "红包数量"=>""}

expect: {"我的红包"=>"我的红包", "历史红包"=>"历史红包", "红包数量"=>"有 2 个红包即将到期
"}

**Comment by bootstraponline** [comment]
This is an [appium server problem](https://github.com/appium/appium/issues) and should be reposted there. The Ruby bindings just issue HTTP requests, the actual logic is in the server.
