### ISSUE TITLE
move_to is broken in Appium 1.5 and always says 'point is not within the bounds of the screen'

### ISSUE THREAD

**Issue by know2script** [appium/ruby_lib#365]
Hi - I'm using Appium 1.5 and ruby bindings.

iPhone 6S +
UICatalog.app
move_to functions looks like broken in this new version. The below snipped worked on 1.4.13 version of appium

Code : 

Appium::TouchAction.new.press(x: @appium_driver.find_element(:xpath,'//UIAApplication[1]/UIAWindow[2]/UIATableView[1]/UIATableCell[18]/UIAStaticText[1]').location_rel.x, y: @appium_driver.find_element(:xpath,'//UIAApplication[1]/UIAWindow[2]/UIATableView[1]/UIATableCell[18]/UIAStaticText[1]').location_rel.y).wait(5000).move_to(x:50,y:50).release.perform

Log:
[debug] [Instruments] [INST] 2016-03-14 20:35:04 +0000 Debug: target.touch(__NSCFArray)
[debug] [Instruments] [INST] 2016-03-14 20:35:09 +0000 Debug: point is not within the bounds of the screen
[debug] [UIAuto] Socket data received (70 bytes)
[debug] [UIAuto] Got result from instruments: {"status":17,"value":"point is not within the bounds of the screen"}

**Comment by bootstraponline** [comment]
This is a server bug since the Ruby move_to code hasn't changed. I recommend reposting the issue on [appium/appium](https://github.com/appium/appium/issues).
