### ISSUE TITLE
Inconsistent naming of driver#driver_quit and driver#screenshot

### ISSUE THREAD

**Issue by dgmora** [appium/ruby_lib#367]
I have a test suite with seleninum for a webapp and appium for iOS and Android. There are a few shared things, like quitting the driver and taking screenshots. It is a bit inconvenient that the selenium methods are `Selenium::WebDriver#quit` and `Selenium::WebDriver#save_screenshot`, where appium methods are `Appium::Driver#driver_quit` and `Selenium::WebDriver#screenshot`

Actually, `Appium::Driver#driver_quit` calls `@driver.quit`, and  `Appium::Driver#screenshot` calls `@driver.save_screenshot`. Is there any specific reason for that? Could we add an alias?

**Comment by bootstraponline** [comment]
If you want an exact API match then just use the [underlying driver object:](https://github.com/appium/appium_capybara/blob/master/lib/appium_capybara/driver/appium/driver.rb#L22)

```ruby
@appium_driver = Appium::Driver.new @options
# selenium is the standard selenium driver without any appium methods
@selenium = @appium_driver.start_driver
```

`quit` already exists in Pry and conflicts with the selenium quit when it's promoted to the top level. Also the behavior is different, appium's quit doesn't throw exceptions.

For screenshot I think an alias would be fine. Locally in your own code it's very easy to add aliases for anything.

**Comment by dgmora** [comment]
Ok, I was just thinking if it'd be possible, but I guess if it conflicts with the selenium quit there's not much to do...
