### ISSUE TITLE
driver.install_app giving "Method has not yet been implemented" error

### ISSUE THREAD

**Issue by juhlila** [appium/ruby_lib#375]
I created this issue on appium repo, but im pretty sure its a lib problem, so im reporting here:
## The problem

I cannot use the method install_app (and some of other methods listed [here](https://github.com/appium/appium/blob/51285550eadb907e5cf90931a0c72ec7bc4a004d/docs/en/writing-running-appium/appium-bindings.md)). It says method is not yet implemented
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): i was running 1.5.2 but never tried install_app on that version
- Desktop OS/version used to run Appium: mac el capitan
- Node.js version (unless using Appium.app|exe): 3.10.3
- Mobile platform/version under test: ios version 8.\* and 9.*
- Real device or emulator/simulator:  real devices
- Appium CLI or Appium.app|exe: cli
## Details

When I try to use install_app method inside a context, i see that error. Some o appium bindings works, some dont. 

if i use driver.install (as sugested), i get this message:
`NoMethodError:
       undefined method`install' for #<Selenium::WebDriver::Driver:0x7e0b57a05ecf54ce browser=:"">
       Did you mean?  install_app
`

Im using rspec scenarios. 
capabilities:

`capabilities = {
    platformName: 'iOS',
    versionNumber: '9.3',
    deviceName: get_device_name,
    app: app_path,
    backendRetries: 1,
    launchTimeout: 1000000,
    autoAcceptAlerts: true,
    newCommandTimeout: 12000,
    udid: get_udid
}` 

$appium = Appium::Driver.new(caps: capabilities)
$browser = $appium.start_driver
Appium.promote_appium_methods self.class
Appium.promote_appium_methods Object
Appium.promote_appium_methods Selenium::WebDriver #i added this later to try to solve the problem
Appium.promote_appium_methods RSpec::Core::ExampleGroup #i added this later to try to solve the problem
## Link to Appium logs

https://gist.github.com/juhlila/707a4fd6bfc996a9086d4c1a24018e80

about the log, i tried with fullReset false and it didnt work
## Code To Reproduce Issue [ Good To Have ]

```
describe 'Gameplay' do
    dir = File.dirname(File.expand_path( __FILE__))
    oi =  dir + '/IPAs/cheats4.ipa'
  before :all do
    driver.install_app oi
  end
it 'should work here too'
    driver.install_app oi
end 
```

**Comment by sofaking** [comment]
Hello @juhlila!
I've tried to reproduce your issue. This install_app command doesn't seem to work on iOS at all. (Didn't try on Android to be honest). In 1.5 AFAIK there is no such command. In Appium 1.4 I'm getting ```Only a (zipped) app/apk files can be installed using this endpoint``` no matter what I'm passing to it.

So, I guess you should install the second app manually, via fruitstrap or something (not sure what is used by Appium ATM)

**Comment by sofaking** [comment]
@bootstraponline I guess the issue can be closed, since it's clearly not the binding's one.

**Comment by juhlila** [comment]
thanks @sofaking, thats what I did. Just in case someone is having the same problem, here is the method I created, it still need to be improved:

```
  def install(app_ipa)
    driver_quit

    puts "Installing #{app_ipa}"
    install_and_run = Thread.new {
      Thread.abort_on_exception = true
      system `ideviceinstaller -u #{get_udid} -g #{app_ipa} > /dev/null`
    }
    puts ''
    print '.' until install_and_run.join(1)
    puts "\n Starting appium driver"
    startdriver = Thread.new {
      Thread.abort_on_exception = true
      start_appium_driver(app: app)
    }
    puts ''
    print '.' until startdriver.join(1); puts ''
  end
```

**Comment by sofaking** [comment]
Nice one.

Just saying, threads overcomplicate otherwise nice little method;)

**Comment by KazuCocoa** [comment]
close due to:

- https://github.com/appium/ruby_lib/issues/375#issuecomment-235848017
- https://github.com/appium/ruby_lib/issues/375#issuecomment-236158566
