### ISSUE TITLE
Cannot run two devices at same time

### ISSUE THREAD

**Issue by Kignuf** [appium/ruby_lib#379]
Hello,

I'm trying to setup a test that would open an app on two different devices (both Android) and then perform some actions on one then the other.

In my cucumber .feature file I do the following
Given Device1 opens App
And Device2 opens App
Then Device1 clicks button
Then Device2 clicks button

The problem is that the appium session gets terminated for device1 when we init device2.

Looking at the ruby_lib code, I found the culprit:
Line 292 in file lib/appium_lib/driver.rb
$driver.driver_quit if $driver

If I comment this line, then it works, I'm able to launch the app on the two devices. But I have issues afterwards, as the click on Device1 doesn't happen. It seems that it's clicking twice on Device2 instead. This behavior might be due to my code, or to the change I've done in the ruby_lib. I'm not sure yet.

In any case, I fear that commenting this code is not an innocent change and I don't want to build stuff on such a fragile foundation. Could someone explain me why this has been implemented that way and/or how I'm supposed to implement a multi device test with cucumber + ruby_lib ?

Thanks.

**Comment by ochubey** [comment]
Hi Kignuf,

Have you tried to run Appium Service programatically and use any free port?
This way you would be able to have 2 instances of the Appium Service and Appium Driver and actions would be run in parallel.
You can also refer to the following documentation to get starting with parallelisation of the tests on Android:
http://appium.io/slate/en/master/?ruby#parallel-android-tests 

Regards,
Oleksiy

**Comment by JaniJegoroff** [comment]
@ochubey Just out of curiosity, have you been able to do that with `ruby_lib`? I have tried parallel testing some time ago but came across with Selenium level error (can't remember the details though). I know Java guys are doing parallel testing without issues.

**Comment by Kignuf** [comment]
Thanks for the replies.

Yes I'm launching one appium per device. It's launched with a specific port, and I give the deviceId in the capabilities when I instantiate the driver:
driver = Appium::Driver.new(caps)

**Comment by ochubey** [comment]
@JaniJegoroff sorry to hear about such limitation with Ruby. Thought solution that work with java_client would be applicable for Ruby too.

**Comment by sofaking** [comment]
@JaniJegoroff using parallel testing from Ruby with no issues. You need to start multiple appium servers on different ports and bootstrap ports. Then just pass udid in caps section of capabilities and port in appium_lib section. That should be it.

Ah, BTW, if you calling adb directly from the code, you should use either -s flag or ANDROID_SERIAL env variable.

**Comment by Kignuf** [comment]
Thanks for all the tips.

I finally figured it out. It was due to the following call:
Appium.promote_appium_methods MyClass

Then in my step definitions I would do stuff like this:
MyObject.finds('blabla').click

Explanations:
- MyObject is an instance of MyClass, and I have one object per device
- finds method comes from ruby_lib. It is available in MyClass because of the promote thing

For some reason, this was not using the driver I instantiated in MyObject but the last one. So the click supposed to happen on device 1 was happening on device 2.

I commented the promote appium methods stuff and now do as follow:
MyObject.**driver**.find('blabla').click

I think it's better that way because now when using ruby_lib methods, I make explicit calls to driver.methodName. So I know I'm not using a custom function but one from the lib.

Cheers.

**Comment by JaniJegoroff** [comment]
Thank you all for confirming that parallel testing is possible with Ruby bindings. 👍
I will get back to try it out in my project very soon.

**Comment by Boopalanr** [comment]
@Kignuf , can you help me with your code implementation for the parallel execution. I am also trying to implement in my project but struggling to.thanks!

**Comment by KazuCocoa** [comment]
Does the below help you?

- https://github.com/appium/ruby_lib/tree/master/ios_tests#ruby_lib_ios
    > rake run_parallel_t Run a test in parallel with thread model.
    > rake run_parallel_p Run a test in parallel with process model.
- https://github.com/appium/ruby_lib/blob/master/ios_tests/readme.md#tips-for-parallel
