### ISSUE TITLE
Wait no longer exists for appium 1.6.0 with XCUITest driver?

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/ruby_lib#381]
I hope I'm posting this bug in the right place!

If iOS capabilities contains automationName: XCUITest, "Wait" no longer works. 

For example:
`def important_btn
        wait { find('SuperImportantButton') }
      end
`

This will fail:
`
Selenium::WebDriver::Error::TimeOutError: timed out after 30 seconds (Method is not implemented)
from /usr/local/lib/ruby/gems/2.3.0/gems/appium_lib-8.0.2/lib/appium_lib/common/wait.rb:50:in`_generic_wait'
`

Appium output: https://gist.github.com/VivaLosDoyers/5e53260464147ef321cad3387dd88dba

**Comment by bootstraponline** [comment]
Wait actually works, it's find that doesn't. Try `find('SuperImportantButton')` to see the real error.

ruby_lib has been [abandonware for over a year](https://github.com/appium/ruby_lib/issues/337) and no company has stepped up to sponsor continued development.

The methods in ruby_lib were written before appium's XCUITest driver existed. They're not compatible with the new driver.

**Comment by VivaLosDoyers** [comment]
find_element(id: 'SuperImportantButton') still seems to work. Would you recommend this as a replacement?

**Comment by bootstraponline** [comment]
I recommend using the upstream selenium bindings directly. They're actively maintained and support all the standard element locators.

**Comment by JaniJegoroff** [comment]
`wait`, `wait_true` etc blocks are working perfectly fine with XCUITest. The only change I had to make was not to use iOS helper methods (button, text, ...) since those methods executes raw UIA code.

**Comment by luskjh** [comment]
@bootstraponline @JaniJegoroff how would you recommend doing touch actions (i.e. scroll) in native apps with the upstream selenium bindings?

**Comment by JaniJegoroff** [comment]
@luskjh I believe you should use touch action API: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md

For simple scrolling this is working:
`execute_script('mobile: scroll', direction: :down)`

**Comment by slipy12** [comment]
@VivaLosDoyers can this issue be closed? I can use wait{} perfectly

**Comment by VivaLosDoyers** [comment]
Yes it can!

**Comment by kagalenitin** [comment]
Can someone post an example code for how the wait{} works. I am using react native app:

`wait { text 'This is my text' } `
 gives me NoMethodError: undefined method `wait' for...  error 
Any help will be appreciated.

**Comment by VivaLosDoyers** [comment]
@kagalenitin it might actually be text that doesn't exist. Try replacing text with a find_element and see if that works.

**Comment by kagalenitin** [comment]
Thanks @VivaLosDoyers I was able to make it work - I should have:
`@driver.wait(15) { @driver.find_element(:name, 'This is my text') }`
I am accessing via @driver variable in my script
