### ISSUE TITLE
Bump selenium-webdriver dependency

### ISSUE THREAD

**Issue by damonsilver** [appium/ruby_lib#382]
The latest version of selenium-webdriver gem is out (v3.0.0 of https://github.com/SeleniumHQ/selenium/tree/master/rb), but the gemspec here still depends on the older version, precluding those of us who rely on both gems from easily upgrading selenium-webdriver to 3.0.0.

https://github.com/appium/ruby_lib/blob/master/appium_lib.gemspec#L17 is the problem line.

Bump the dependency to `~> 3.0.0` when possible.

**Comment by krupani** [comment]
Facing the same problem, please update the dependency in the next version...

**Comment by JaniJegoroff** [comment]
@krupani This is not simply as "just bump up the version number and everything magically works" kind of change. Work is already in progress: https://github.com/appium/ruby_lib/pull/383

Community is maintaining this library voluntarily so contributions are welcome. :)

**Comment by KazuCocoa** [comment]
Yes, I'm trying to update dependencies on #383 . But I'm working on adapting XCUItest for now.

If you'd like to update dependencies based on ruby_lib v8, you could use https://github.com/KazuCocoa/ruby_lib/tree/update_gems branch. In my environment, the branch works fine. @krupani

**Comment by KazuCocoa** [comment]
released in 9.1.0 https://rubygems.org/gems/appium_lib/versions/9.1.0

**Comment by damonsilver** [comment]
Thank you!
