### ISSUE TITLE
Alternative to page?

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/ruby_lib#385]
With page no longer working with XCUITest, and Appium 1.6.0 GUI not yet a thing that exists, what's the best way to get a list of elements on the screen?

**Comment by bootstraponline** [comment]
The source endpoint should still work. I don't think it'd be that much effort to update the page command to parse the XCUITest output.

https://github.com/facebook/WebDriverAgent/issues/320 looks painful though.

**Comment by VivaLosDoyers** [comment]
If I'm understanding ruby_lib correctly, this could be difficult since the process starts with asking Instruments to return the tree:

`execute_script "UIATarget.localTarget().frontMostApp().windows()[#{window_number}].getTree()"`

I wouldn't know what to replace this with :\

**Comment by bootstraponline** [comment]
It'd be replaced with a call to the standard selenium source endpoint. We'd remove execute script entirely.

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib/releases/tag/v9.0.0

call `get_source`(call source endpoint) in `page()`
