### ISSUE TITLE
Appium 1.6, ruby, android - error in finding element via xpath

### ISSUE THREAD

**Issue by sohaib-apadmi** [appium/ruby_lib#386]
(Created gist to keep issue concise. Please refer to following: https://gist.github.com/sohaib-apadmi/44a59fbb04bac0361563ad3ae152db74)

Since upgrading to appium 1.6, I have faced a number of issues. One such issue is the following: when using android the tests start to run, it sees that it's on the login screen, manages to find its way to login and then even login. The problem occurs after that when it is looking for elements to check if it is on the homepage but fails. The terminal throws up (1) in the gist above.

The appium log which is relevant from when this occurs is seen at (2) in the gist above.

Finally the code I use to find elements is seen under (3) in the gist above.

To provide some flow: when you open the app you see a splash screen, you click on the sign in, put in your details and then are taken to home screen. The context switches from NATIVE_APP on the splash screen, to WEBVIEW on the login screen, back to NATIVE_APP on the home screen (not sure if this is relevant but providing info anyway) and to clarify, these tests worked perfectly fine on appium 1.5.3. Thanks in advance :slight_smile:

**Comment by JaniJegoroff** [comment]
There are known issues in WebDriverAgent regarding `xpath`.

Looks like you are using `uiautomator v2`? I would consider this still work in progress in Appium side so definitely you will come across with some issues. Also some of the `ruby_lib` Android helper methods uses raw `uiautomator v1` code which does not necessarily work with `uiautomator v2`. I would recommend to read Appium release notes before going for `uiautomator v2`.

> these tests worked perfectly fine on appium 1.5.3.

This is not fair comparison if you are using `uiautomator v2`. Try with `uiautomator v1` instead.

**Comment by sohaib-apadmi** [comment]
Ah, right that makes sense. I was under the impression that `uiatomator v2` was required with the new appium update. I've followed what you've mentioned but now I am getting new errors, which is that after sign in, it  sometimes displays either of the following : 
`undefined method 'click' for [#<Selenium::WebDriver::Element:0x..fc2c310f19d227ac4 id="7">]:Array (NoMethodError)`
or sometimes shows
`undefined method 'displayed?' for [#<Selenium::WebDriver::Element:0x4bea8ffcb5f927da id="4">]:Array
      Did you mean?  display (NoMethodError)`. For context, After login an overlay comes up telling you what's new with the app. My code checks if the "What's new" element is displayed and then clicks the close button. Again, this is only an android issue.

**Comment by JaniJegoroff** [comment]
Looks like object returned is an `Array` and therefore `click` nor `displayed?` methods are not defined.

**Comment by sohaib-apadmi** [comment]
Ah right, you're right on that. Thank you very much, you've been very helpul 😄

**Comment by sofaking** [comment]
It seems you're using find_elements instead of find_element and forget to get first element from resulting Array.
