### ISSUE TITLE
Selenium::WebDriver::Error::UnknownError: Method is not implemented

### ISSUE THREAD

**Issue by vikramvi** [appium/ruby_lib#399]
[caps]
automationName = "XCUITest"
platformName = "iOS"
app = "/Users/.../test.app"
deviceName = "iPhone SE"
platformVersion = "9.3"

with arc command, I could launch app in the simulator but when I tried page command; it's throwing below error

[1] pry(main)> page
Selenium::WebDriver::Error::UnknownError: Method is not implemented
from /Users/vikram-anna/.rvm/gems/ruby-2.3.2/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'

1.6.1-beta with XCode 8.0

**Comment by JaniJegoroff** [comment]
Duplicate to https://github.com/appium/ruby_lib/issues/385

**Comment by KazuCocoa** [comment]
I close this issue due to #385

**Comment by vikramvi** [comment]
verified fixed with appium 1.6.3 + appium_lib (9.0.0)

**Comment by vikramvi** [comment]
coming from Java world, I am confused why is ruby_lib in reality appium_lib ? Why can't both names be same ?

Please clarify @KazuCocoa @JaniJegoroff

**Comment by jlipps** [comment]
From the perspective of Appium, it is our "ruby library". From the perspective of a ruby user, it is the "appium library". We could change the name of this repo but it's probably not worth it at this point.
