### ISSUE TITLE
release 9.1

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#415]
- Support selenium-webdriver 3.0.2+
    - drop selenium-webdriver2
        - because some methods are incompatible
    - https://github.com/appium/ruby_lib/pull/413 , https://github.com/appium/ruby_lib/pull/383
- Support Ruby 2.0+ or 2.2+
    - https://github.com/appium/ruby_lib/issues/414
- update some dependencies

**Comment by slipy12** [comment]
It changes anything in terms of use? Or it's only intern refactor?

**Comment by KazuCocoa** [comment]
It's just internal refactoring for this library's users. If they already use Ruby 2.2+ and they can move to selenium-webdriver 3.0.2+, there is no concerns.

If someone uses Ruby1.9 and needs to continue to use selenium-webdriver 2.x, they need to update Ruby version and selenium-webdriver to use next release's version.

**Comment by KazuCocoa** [comment]
released https://rubygems.org/gems/appium_lib/versions/9.1.0

**Comment by KazuCocoa** [comment]
If someone needs Ruby 2.0 or 2.1, I'll set `required_ruby_version` as 2.0 to fit `selenium-webdriver`.
