### ISSUE TITLE
Add swipe endpoint for XCUITest

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#430]
WDA has a new "swipe" endpoint. Use it.
https://github.com/appium/appium/issues/7573#issuecomment-268319607

**Comment by KazuCocoa** [comment]
- current `swipe` method
    - https://github.com/appium/ruby_lib/blob/42df79b4cd0b5a36f52628f0acdeb688c5170c0c/lib/appium_lib/device/touch_actions.rb#L127
- commands for endpoint
    - https://github.com/appium/ruby_lib/blob/858863ad88e0d4e32acb109c6bd087a040817fd2/lib/appium_lib/common/command.rb
    - https://github.com/appium/ruby_lib/blob/e4b4426a1322a3a552bad93c4d8a54c9592bebc6/lib/appium_lib/device/device.rb#L307

**Comment by jlipps** [comment]
@KazuCocoa IMO, for forward compatibility, the ruby library should not attempt to send any commands to WDA directly, but rather should create a helper `swipe` method which just converts to the appropriate TouchActions (if this doesn't already exist)

**Comment by KazuCocoa** [comment]
I understood.
`ruby_lib` already have swipe action based on `touch_action`.

https://github.com/appium/ruby_lib/blob/42df79b4cd0b5a36f52628f0acdeb688c5170c0c/lib/appium_lib/device/touch_actions.rb#L147-L155

**Comment by jlipps** [comment]
👍  thanks @KazuCocoa. Hopefully the Appium server update will be sufficient.
