### ISSUE TITLE
raise Selenium::WebDriver::Error::UnknownError: Support for tap action

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#453]
from https://github.com/appium/ruby_lib/issues/254#issuecomment-270644557

tap is not working for me with appium 1.6.3 with appium_console: v2.0.1 and appium_lib: v9.1.2
I have a XCUIElementTypeAlert displayed on my screen
these are the coordinates of my XCUIElementTypeAlert: x=52, y=263, h=141, w=271
and this is the size of my screen where XCUIElementTypeAlert is displayed: height = 667, width = 375
I would like to tap outside XCUIElementTypeAlert:
`> Appium::TouchAction.new.tap(:x => 0, :y => window_size.width*0.5).release.perform
Selenium::WebDriver::Error::UnknownError: Support for this gesture is not yet implemented. Please contact an Appium dev
from /Users/admin/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-3.0.5/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'`

and when I try without release, it does not give any error but it tap the first button of the element XCUIElementTypeAlert instead of tapping outside:
`> Appium::TouchAction.new.tap(:x => 0, :y => window_size.width*0.5).perform
#<Appium::TouchAction:0x007fe958d77fa0 @actions=[{:action=>:tap, :options=>{:x=>0, :y=>187.5, :count=>1}}]>`

**Comment by KazuCocoa** [comment]
according to the appium-xcuitest-drive, `tap` should work

- implementation
    - https://github.com/appium/appium-xcuitest-driver/blob/21d5870780b66305be17425fa819af5e7b49cbea/lib/commands/gesture.js#L83
- test code
    - https://github.com/appium/appium-xcuitest-driver/blob/99fb837306a64db5f73bc2bcf336229edca0e01c/test/unit/commands/gesture-specs.js#L13
    - https://github.com/appium/appium-xcuitest-driver/blob/4caab38e09a923d8a4bc433469ae85b6be947446/test/functional/basic/gesture-e2e-specs.js#L40

**Comment by KazuCocoa** [comment]
> Appium::TouchAction.new.tap(:x => 0, :y => window_size.width*0.5).release.perform 

this action is not valid in `appium-xcuitest-drive`.
So, I need to update documentations.

---

cc @nairouz12

**Comment by nairouz12** [comment]
@KazuCocoa  tap works for me as well in the normal case.
it is only in the case that I described, having an alert popup displayed and I want to press outside of it, in this case it is always touching the first button of the popup instead of respecting the x and y passed in tap.

**Comment by nairouz12** [comment]
So any idea why tap does not work properly in the case I mentioned?

**Comment by KazuCocoa** [comment]
The action seems depends on WebDriverAgent, I think.

Can you try tapping `x, y = 0, 187.5` with the follwing command to WDA directly?
If it works same as your mentioned behaviour, this issue depends on WDA.

```
curl -X POST $JSON_HEADER \
-d "{\"x\":\"0\",\"y\":\"187.5\"}" \
$DEVICE_URL/session/$SESSION_ID/tap/0
```
ref: WDA's wiki: https://github.com/facebook/WebDriverAgent/wiki/Queries

---

Between ruby_lib and appium-xcuitest-driver looks works fine.
( from `<Appium::TouchAction:0x007fe958d77fa0 @actions=[{:action=>:tap, :options=>{:x=>0, :y=>187.5, :count=>1}}]>` )

On appium-xcuitest-driver, it sends a request to WDA as the following code.
https://github.com/appium/appium-xcuitest-driver/blob/21d5870780b66305be17425fa819af5e7b49cbea/lib/commands/gesture.js#L181

---

memos for me:

- WDA
    - endpoint https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L63
        - and `uuid = 0` is no element case
    - https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L314

**Comment by KazuCocoa** [comment]
@nairouz12 

Could you try https://github.com/appium/ruby_lib/issues/453#issuecomment-270685625 if you have time?

```
curl -X POST $JSON_HEADER \
-d "{\"x\":\"0\",\"y\":\"187.5\"}" \
$DEVICE_URL/session/$SESSION_ID/tap/0
```

**Comment by nairouz12** [comment]
@KazuCocoa I tried to sedn commands directly to WDA, but I was receiving an error so I stopped with that and I created this issue https://github.com/facebook/WebDriverAgent/issues/438 for WDA

**Comment by KazuCocoa** [comment]
Thanks for creating issue on WDA!

**Comment by KazuCocoa** [comment]
This may WDA side issue.
Please reopen if it clarifies this issue is appium_lib side.
