### ISSUE TITLE
REQUIRED_VERSION_XCUITEST

### ISSUE THREAD

**Issue by beanqueen** [appium/ruby_lib#463]
in [lib/appium_lib/driver.rb](https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/driver.rb#L435)

maybe change
`@appium_server_version['build']['version'] <= REQUIRED_VERSION_XCUITEST`
to
`@appium_server_version['build']['version'] < REQUIRED_VERSION_XCUITEST`
and fail with
`"XCUITest requires Appium version >= #{REQUIRED_VERSION_XCUITEST}"`

**Comment by KazuCocoa** [comment]
oops, thanks!

**Comment by KazuCocoa** [comment]
Fixed in #464 .
btw, some methods don't work well in Appium 1.6.0, 1.6.1 because of WDA :(
So, I recommended to use 1.6.2+.
