### ISSUE TITLE
Capabilities being renamed?

### ISSUE THREAD

**Issue by ragog** [appium/ruby_lib#476]
Hi,

I am running the following script in the TestObject cloud and, when sending over TO's own caps, these seem to get renamed. Example: 

> testobject_api_key
becomes
> testobjectApiKey

This has been brought to our attention by several users who updated to appium_lib 9.3 and were able to run normally before.

Here is the script I am running:

```
require 'appium_lib'
require 'test/unit'

class BasicTestSetup < Test::Unit::TestCase
  def setup
    desired_capabilities = {
        caps:       {
            testobject_api_key: 'EDITED',
            testobject_device: 'EDITED'
        },
        appium_lib: {
            server_url: 'http://appium.testobject.com/wd/hub',
            wait: 10
        }
    }

    # Start the driver
    @driver = Appium::Driver.new(desired_capabilities).start_driver
  end

  # test method names must start with "test_"
  # to be recognized by the test-unit framework
  def test_login
    # Your test
  end

  def teardown
    @driver.quit
  end
end
```

Here is what I am seeing from our logs:

`'{"desiredCapabilities":{"browserName":"","version":"","platform":"ANY","javascriptEnabled":true,"cssSelectorsEnabled":true,"takesScreenshot":true,"nativeEvents":false,"rotatable":false,"testobjectApiKey":"EDITED","testobjectDevice":"EDITED"}}'`

Any idea what might be going on?

**Comment by KazuCocoa** [comment]
@ragog 

I've changed the logic in https://github.com/appium/ruby_lib/releases/tag/v9.1.0 to catch up with selenium-webdriver v3. From the version, initializing capabilities use `::Selenium::WebDriver::Remote::Capabilities.new` and it depends on selenium-webdriver.
https://github.com/appium/ruby_lib/blob/bab7df7f097fef9e848f33a60d70d0e7e018c25c/lib/appium_lib/driver.rb#L254-L260

This change may affect your mentioned issue. Did your mentioned issue happen from v9.1.0?


In Appium, every capability is lowerCamelCase. So, I couldn't realise the effect.
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

**Comment by KazuCocoa** [comment]
I add some tests to clarify this issue.
https://github.com/appium/ruby_lib/pull/477/files

`elenium::WebDriver::Remote::Capabilities` convert snake_case to lowerCamelCase when it sends to Appium server as `JSON`.

**Comment by KazuCocoa** [comment]
Could you update your system to apply `lowerCamelCase`, too?
@ragog

**Comment by ragog** [comment]
@KazuCocoa we have deployed a fix to handle the needed change. Thank you for your help.
