### ISSUE TITLE
fix ::Fixnum is deprecated for Ruby2.4.0

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#491]
/Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/awesome_print-1.7.0/lib/awesome_print/formatters/base_formatter.rb:31: warning: constant ::Fixnum is deprecated

**Comment by alexandre-mbm** [comment]
Workaround: http://stackoverflow.com/a/42336144/3391915
```sh
export RUBYOPT="-W0"
```

**Comment by KazuCocoa** [comment]
If awesome_print will be published which include https://github.com/awesome-print/awesome_print/commit/d01fade4f2a090773ba8512ade456caf1e5cdbef , I'll update the version  and be able to close this issue.

**Comment by abotalov** [comment]
1.8.0 was released

**Comment by KazuCocoa** [comment]
thanks!
