### ISSUE TITLE
The android doc is messed up at the bottom half.

### ISSUE THREAD

**Issue by waynema** [appium/ruby_lib#524]
https://github.com/appium/ruby_lib/blob/master/docs/android_docs.md

**Comment by mykola-mokhnach** [comment]
We'd appreciate it if you could fix the markup there and create a PR.

**Comment by waynema** [comment]
@mykola-mokhnach, Can you send me the link on how we can contribute?

**Comment by mykola-mokhnach** [comment]
Sure thing. Simply fork the project, do all the necessary fixes and create a pull request. Check https://help.github.com/articles/creating-a-pull-request-from-a-fork/ and https://opensource.guide/how-to-contribute/ (section "Opening a pull request") for more details.

**Comment by waynema** [comment]
https://github.com/appium/ruby_lib/pull/525

**Comment by mykola-mokhnach** [comment]
Perfect 👍

**Comment by KazuCocoa** [comment]
thanks!
