### ISSUE TITLE
Unable to find element using :uiautomator

### ISSUE THREAD

**Issue by willosser** [appium/ruby_lib#527]
Environment: OS X Yosemite (10.10.5), Ruby 2.2.5, Appium 1.6.3
Gems: appium_lib-9.3.6, selenium-webdriver-3.3.0
Also fails with appium_lib-9.3.5 and appium_lib-9.3.4
Android: android-sdk/24.4.1_1

We had been using this code with no issues with Appium 1.4.13, Selenium-webdriver.2.53.4 and appium_lib-8.0.2.  My memory tells me that this was working just three weeks ago with (perhaps) some slight gem changes, but I have no physical evidence demonstrating that.
[appium-android.txt](https://github.com/appium/ruby_lib/files/890719/appium-android.txt)

When calling driver.find_element(:uiautomator, search_string), we receive the following error:

      cannot find element by :uiautomator (ArgumentError)
      /Users/wosser/.rvm/gems/ruby-2.2.5/gems/selenium-webdriver-3.3.0/lib/selenium/webdriver/common/search_context.rb:60:in `find_element'

I'm attaching the appium-android.txt log, although I don't believe the problem is reported there.

**Comment by KazuCocoa** [comment]
@willosser 
How about using `find_element_with_appium` instead of `find_element`?
Because we couldn't extend `find_element` directly from `selenium-webdriver3.x`. So, I've added `find_element/s_with_appium` for `@driver` instance to call some appium specific methods such as `:uiautomator` from `appium_lib9.1.0`.

-----

I have to update some documentations.

- https://github.com/appium/ruby_lib/blob/17d17e65a52cc22d093f913084673cb3a33b450c/lib/appium_lib/driver.rb#L691
- https://github.com/appium/ruby_lib/blob/4ae081549cf1aad89c6d304fc8a8b9499db96160/lib/appium_lib/device/device.rb#L426

**Comment by willosser** [comment]
I will test this.  Can I replace all calls to driver.find_element/s with calls to driver.find_elements/s_with_appium, or should I reserve that only for by-methods such as :uiautomator

**Comment by KazuCocoa** [comment]
You can replace all find_elament/s to find_element/s_with_appoum since _with_appium methods include find_elements.

**Comment by KazuCocoa** [comment]
@willosser 
I apologise you since I decide to remove `_with_appium` from find_elements.
https://github.com/appium/ruby_lib/pull/532/files

I'll release this as 9.3.7 soon.

Because my previous change associated `with_appium` confuse anyone.
So, I remove it and rename to `find_element/s`.

```
1] pry(#<driver>)> $driver.driver.find_elements :accessibility_id, "Toolbar"
=> [#<Selenium::WebDriver::Element:0x76d28ec830c6a272 id="A7372773-5402-4CE1-91DF-EEEC6FA01126">]
[2] pry(#<driver>)> find_elements :accessibility_id, "Toolbar"
=> [#<Selenium::WebDriver::Element:0x203d0b8d4ed8fed2 id="65B07CDA-D5B5-4C97-A2BB-B8EAA594BA85">]

```

**Comment by KazuCocoa** [comment]
I've update gems to be able to call `accessibility_id`, `:uiautomator` and `:predicate` with `@driver.find_element/s` with https://rubygems.org/gems/appium_lib/versions/9.3.7 .

Please update `ruby_lib` and try `find_element/s`, without `_with_appium` suffix. @willosser
