### ISSUE TITLE
NoMethodError: undefined method `get' for nil:NilClass

### ISSUE THREAD

**Issue by vikramvi** [appium/ruby_lib#528]
appium_console (2.1.1)
appium_lib (9.3.6)

I've below caps
[caps]
platformName = "Android"
deviceName = "placeholder string"
browserName = "Chrome"

This does launched Chrome browser on real device but when I try to execute command 

```
**[1] pry(main)> @driver.get("http://www.google.com")**

NoMethodError: undefined method `get' for nil:NilClass
Did you mean?  gets
               get_source
               get_settings
               gem
from (pry):1:in `__pry__'
```

**Comment by KazuCocoa** [comment]
@vikramvi 
It looks `@driver` is nil class.
Does `@driver` exist?

**Comment by vikramvi** [comment]
@KazuCocoa Please refer to below output, `@driver` is not nil

`[2] pry(main)> @driver.caps
#<Selenium::WebDriver::Remote::Capabilities:0x007fdc7aa0bb40 @capabilities={:browser_name=>"", :version=>"", :platform=>:any, :javascript_enabled=>true, :css_selectors_enabled=>true, :takes_screenshot=>true, :native_events=>false, :rotatable=>false, :firefox_profile=>nil, :proxy=>nil, :newCommandTimeout=>999999, :platformName=>"Android", :deviceName=>"placeholder string", :browserName=>"Chrome"}>
[3] pry(main)> @driver.get("http://www.google.com")
NoMethodError: undefined method `get' for nil:NilClass
Did you mean?  gets
               get_source
               get_settings
               gem
from (pry):3:in `__pry__'
[4] pry(main)> `

**Comment by KazuCocoa** [comment]
How to start the driver? @vikramvi 

I could call `.get` method as the following steps.

```
driver = Appium::Driver.new(caps).start_driver
driver.get("http://www.google.com")
```

**Comment by vikramvi** [comment]
@KazuCocoa using CAPS per original comment, I just use command `arc` so start session ( before this I start appium server ).

Later I user @driver to call methods, this does work for native app. I could use each of the methods listed by @driver.methods 

I wanted to use same approach for web automation on mobile browser and faced this issue. Am I doing something wrong ?

**Comment by KazuCocoa** [comment]
Oh, sorry, I have't use `arc`...

According to the following documentation, `.start_driver` provide standard selenium driver.

- https://github.com/appium/ruby_lib/blob/master/docs/docs.md

```
# appium specific driver with helpers available
@appium_driver = Appium::Driver.new @options
# standard selenium driver without any appium methods
@selenium_driver = @appium_driver.start_driver
```

So, if you haven't call `@driver.start_driver`, you can't call selenium related methods, I think.

**Comment by vikramvi** [comment]
@KazuCocoa  Thanks for detailed clarification; it did work.

I'm from Java background, can you please clarify what exactly  `arc` command does ? And which type of driver does it creates ?

**Comment by KazuCocoa** [comment]
- `Appium::Driver.new @options` create an object which has configurations and extended Appium specific methods.
    - https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/driver.rb#L362
    - Doesn't establish sessions to appium server yet.

- `@appium_driver.start_driver`
    - Start to establish sessions to appium server to be able to send some commands to the server.
        - Extended Appium methods and Selenium WebDriver's methods can send the server just now.
    - https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/driver.rb#L594

---

https://github.com/appium/ruby_console#run

I think some commands such as `arc toml FILE` just read configurations from files.
And `init` command calls `.start_driver` finally. `arc` extend Appium methods to `Object` which is a top level object in Ruby [here](https://github.com/appium/ruby_console/blob/master/lib/start.rb#L17).
So, you can also call appium methods without instance such as `@driver`.

- https://github.com/appium/ruby_console/blob/master/lib/appium_console.rb#L38
- https://github.com/appium/ruby_console/blob/master/lib/start.rb

**Comment by KazuCocoa** [comment]
additional:

In Ruby world, you can call appium methods without `@driver` if you call `Appium.promote_appium_methods SomeObject` like [here](https://github.com/appium/ruby_console/blob/master/lib/start.rb#L17).
After calling this method, `self.driver.texts` can call just `texts`.

Without `Appium.promote_appium_methods SomeObject` , you can call methods, Appium and Selenium, with `driver.xxxx` as same after start_driver.

**Comment by KazuCocoa** [comment]
Please reopen this issue if you need.
