### ISSUE TITLE
WARN: Unresolved specs during Gem::Specification.reset: json (>= 1.8)

### ISSUE THREAD

**Issue by vikramvi** [appium/ruby_lib#529]
appium_console (2.1.1)
appium_lib (9.3.6)

```
arc
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.8)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
[1] pry(main)> exit
```

**Comment by JaniJegoroff** [comment]
I believe you should run `bundle exec arc`

**Comment by vikramvi** [comment]
@JaniJegoroff But with earlier version just command `arc` was working fine.

Something changed with new version ?

**Comment by JaniJegoroff** [comment]
You should always use `bundle` to avoid dependency headache. If it worked for you previously without `bundle`, you just have been very lucky. :)
