### ISSUE TITLE
The iOS doc is messed up at the bottom half.

### ISSUE THREAD

**Issue by waynema** [appium/ruby_lib#533]
The issue (https://github.com/appium/ruby_lib/issues/524) happened on Android doc is showing on iOS now.

https://github.com/appium/ruby_lib/blob/master/docs/ios_docs.md

**Comment by waynema** [comment]
https://github.com/appium/ruby_lib/pull/526 may already fix this.

**Comment by KazuCocoa** [comment]
Exactly.

I'll update docs in the next release.
