### ISSUE TITLE
9.4.0 release sudden failures

### ISSUE THREAD

**Issue by Edouard-chin** [appium/ruby_lib#546]
Hey guys 👋 ,

Thanks for maintaining this great gem!
We noticed sudden failures on our UI automation, the failure started as soon as the `9.4.0` version got released.

Our automation became flakky (80% of failures), all errors were related to finding elements.
Line of code looking like this for example 
```ruby
appium_driver.button('Done').click
appium_driver.text('Select').click
```

After setting the gem version back to `9.3.8` the failures stopped.

Not sure if the way we find elements is wrong but it used to work perfectly for the last couple weeks.

Here is what our CI environment uses:

- Ubuntu 16.0.4
- Appium v1.6.3
- Android sdk-tools v 25.2.3

Thanks !

**Comment by KazuCocoa** [comment]
Thanks for your reporting!

hm...
I've changed some logic to xpath in https://github.com/appium/ruby_lib/pull/544.
I'll change to use uiautomation for `appium` automation name and xpath for `uiautomator2`.

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib/releases/tag/v9.4.1
