### ISSUE TITLE
doubleTap isn't tapping

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/ruby_lib#548]
I have an object in my iOS app that responds to both taps and double-taps the same way (by showing a popover). The contents of the popover are determined by whether or not the user performed a single tap or a double tap.

I can single tap the element like so:
`find_elements(id: 'ViewItem')[0].click`

However, when I do
`execute_script "mobile: doubleTap", element: find_elements(id: 'ViewItem')[0].ref`

Nothing happens :(

arc output:
```
[13] pry(main)> find_elements(id: 'ViewItem')[0].click
""
[14] pry(main)> find_elements(id: 'ViewItem')[0].ref
"36DCDD7D-68C8-406F-A86B-9A6645045EBE"
[15] pry(main)> execute_script "mobile: doubleTap", element: find_elements(id: 'ViewItem')[0].ref
nil
```

I've tried this with various versions of ruby_lib all the way up to 9.4.0.

**Comment by KazuCocoa** [comment]
The following `doubleTap` works fine.
https://github.com/appium/ruby_lib/blob/master/ios_tests/lib/ios/specs/ios/xcuitest_gestures.rb#L20
The command call `execute_script 'mobile: doubleTap', { element: button('Tinted').ref }`.

So, I think it depends on WebDriverAgent side.
Could you create an issue on WebDriverAgent or Appium side with server logs?
@VivaLosDoyers

**Comment by VivaLosDoyers** [comment]
I'll try to explore this a little more in the future, but sadly I don't have the time now.

I was able to work around this by finding the location of the element, and double-tapping a relative raw screen coordinate.

```
def double_tap(element)
  # Find the object, then go to the middle of it, and double-tap
  tapx = element.location.x + element.size.width * 0.50
  tapy = element.location.y + element.size.height * 0.50
  execute_script 'mobile: doubleTap', x: tapx, y: tapy
end
```

**Comment by KazuCocoa** [comment]
I checked code in WDA and Appium side. I guess it depends on XCUITest framework provided by Apple.
Thanks for your workaround! I'll add this workaround in doc. @VivaLosDoyers

**Comment by KazuCocoa** [comment]
@VivaLosDoyers 
I've appended and updated the workaround [here](https://github.com/appium/ruby_lib/pull/557).
Your workaround has many Appium calls. To make the method more efficient, it is better to reduce Appium calls.
