### ISSUE TITLE
drag_from_to_for_duration gets server error

### ISSUE THREAD

**Issue by StevePotter** [appium/ruby_lib#552]
I tried using the library's `drag_from_to_for_duration` but Appium server gave me:
`Error: "fromX" parameter is mandatory for "dragFromToForDuration" call`

The culprit is this line https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/ios/xcuitest_gestures.rb#L121

Change it to
`args = { fromX: from_x, fromY: from_y, toX: to_x, toY: to_y, duration: duration }` to fix it.  Do you want a PR for this?  Is this a change in Appium or has it been broken for a while?

**Comment by KazuCocoa** [comment]
Thanks!
I forgot to add the command's test... https://github.com/appium/ruby_lib/blob/master/ios_tests/lib/ios/specs/ios/xcuitest_gestures.rb
I'll fix and release fixed version soon.

**Comment by KazuCocoa** [comment]
I've published fixed version as v9.4.2: https://rubygems.org/gems/appium_lib/versions/9.4.2

@StevePotter

**Comment by StevePotter** [comment]
Thank you!
