### ISSUE TITLE
Getting Android version from driver?

### ISSUE THREAD

**Issue by yunhaom94** [appium/ruby_lib#574]
Hello, 

Is there a way of getting Android version of device from the server after the driver is created? 
I am using Appium 1.6.4.

**Comment by KazuCocoa** [comment]
No, there isn't, I think.

We should get a platform version or a sdk version via adb command such as the following command.(The following is a JS library.)
https://github.com/appium/appium-adb/blob/62a5f0cddfb633d7688a991dd8aad4672453d0e7/lib/tools/adb-commands.js#L42

The following is an example I used in my case.
https://github.com/KazuCocoa/droid_adbs/blob/a59472850ebe9492b74eec5ee8ae9cd47134893b/lib/droid_adbs/commons/devices.rb#L30

**Comment by yunhaom94** [comment]
Thanks for the reply.
Is there plan of adding this functionality to Appium client lib, since I can't run adb commands toward a device which is connected to the server while I'm on a remote client

**Comment by jlipps** [comment]
@yunhaom94 i'm confused how you end up in a situation where you don't know the android version of a device you've started a test on?

**Comment by yunhaom94** [comment]
Our use case require us to change connected testing devices often, therefore it's easier for us to provide only udid on client side and it will still get to the correct device. 

Since some of the test cases we use have slight differences between different Android versions, we hope there is way to check for the version through codes.

**Comment by yunhaom94** [comment]
We've decided to not use Appium to get that information.
