### ISSUE TITLE
Select value from UIAPickerWheel

### ISSUE THREAD

**Issue by bootstraponline** [appium/ruby_lib#58]
As reported [on the mailing list](https://groups.google.com/forum/#!topic/appium-discuss/p518OsjOjvU).

> select second value 'Chris Armstrong' in this UICatalog.

**Comment by stark154** [comment]
Is there a C# version for this?

**Comment by bootstraponline** [comment]
> Is there a C# version for this?

https://github.com/appium/appium-dotnet-driver

**Comment by stark154** [comment]
Thanks for the link. Though that was not what I meant to ask.
To be more specific is there a C# version to change the picker's value on iOS.

**Comment by bootstraponline** [comment]
There's no code you can copy and paste. The JavaScript methods used in the example also exist in the dotnet driver.
