### ISSUE TITLE
Driver disables Pry pager without asking

### ISSUE THREAD

**Issue by TikiTDO** [appium/ruby_lib#582]
The driver is set up to silently disable Pry pagination without asking, and without any ability to modify this behavior short of forking my own release. I actually find this feature of Pry extremely useful, and I would prefer if libraries didn't randomly turn it off without any input on my part, particularly when these libraries deal with app automation and have absolutely nothing to do with Pry in the first place. 

At the very least please mention in the docs that this is happening. I had to spent a significant amount of time figuring out why my debugger behavior suddenly changed.

In any case, this sort of configuration properly belong's in a user's .pryrc file, as per [this documentation](https://github.com/pry/pry/wiki/Customization-and-configuration).

**Comment by KazuCocoa** [comment]
Thanks, I understood.

https://github.com/appium/ruby_lib/blob/27e10f8ba310ce933171b169607172e593344ad7/lib/appium_lib/driver.rb#L779

**Comment by KazuCocoa** [comment]
^ Skip `Pry.config.pager = false` if users has `.pryrc` and add documentations for this option in readme.
