### ISSUE TITLE
Can't use Selenium and Appium driver methods in a same cucumber test

### ISSUE THREAD

**Issue by EugeneMarrow** [appium/ruby_lib#595]
Hi, I'm writing tests for native iOS app using Appium selenium and cucumber with Selenium::WebDriver as main driver.
Story is, I would like to use some Appium_lib methods in my tests along with Selenium ones.
For example:
I've tried to write a test for login via Facebook, which should switch to webview in order to process some commands via IWDP to Safari.
And thats where I feel a lack of commands.
problem is that I can't manage env.rb file to use methods from both libs.
Hope someone here has any suggestions on this.

Here is my env.rb file with witch I run cucumber tests using selenium methods:

require 'rspec'
require 'rspec/expectations'
require 'appium_lib'
require 'cucumber/ast'
require 'selenium-webdriver'
require 'capybara/cucumber'
#require 'capybara/rails'

class AppiumWorld
end

def caps
       {"deviceName"=> "iPhone 6s",
        "platformName"=> "iOS",
        #"browserName"=>"Safari",
        #"startIWDP"=>"true",
        "platformVersion"=> "10.3.1",
        "udid"=> "7cb9e60a22f9a3982523298ecbf806ba1b96c469",
        "app"=> "/Users/macpad/Projects/louder/Louder.me.ipa",
        "bundleId"=> "com.musicplatform.louderme",
        'noReset' => "true"
      }
end

def url 
   "http://localhost:4723/wd/hub" 
 end
 
def selenium
  @driver ||=Selenium::WebDriver.for(:remote, :desired_capabilities=>caps, :url=>url)
end
#Appium::Driver.new(caps)
#Appium.promote_appium_methods AppiumWorld

World do
  AppiumWorld.new
end

#Before { $driver.start_driver }
 After {@driver.quit}

Thanks in advance

**Comment by Asimk21** [comment]
@driver = Appium::Driver.new(caps) ==> Appium driver, use appium methods
@driver.driver ==================> Selenium driver, use selenium methods

I think this is what you need, right?

**Comment by EugeneMarrow** [comment]
@Asimk21 
Could you produce actual code for Selenium driver definition, or sample env.rb, if it's possible?
Asking because I've tried the following 

 ```
@driver = Appium::Driver.new(caps)
@driver.driver ||=Selenium::WebDriver.for(:remote, :desired_capabilities=>caps, :url=>url
```
and faced the error:

```
undefined method `driver=' for #<Appium::Driver:0x007fd0cdcffc60>
Did you mean?  driver (NoMethodError)
```


here is my env.rb file if it may help:

```
require 'rspec/expectations'
require 'appium_lib'
require 'cucumber/ast'
require 'capybara'
require 'capybara/cucumber'
require 'appium_capybara'
require  'selenium-webdriver'

class AppiumWorld
end


def caps
       {"deviceName"=> "iPhone 6s",
        "platformName"=> "iOS",
        #"browserName"=>"Safari",
        #"startIWDP"=>"true",
        "platformVersion"=> "10.3.1",
        "udid"=> "7cb9e60a22f9a3982523298ecbf806ba1b96c469",
        "app"=> "/Users/macpad/Projects/louder/Louder.me.ipa",
        "bundleId"=> "com.musicplatform.louderme",
        'noReset' => "true"
      }
end

def url 
   "http://localhost:4723/wd/hub" 
 end
 
 @driver = Appium::Driver.new(caps)
 @driver.driver ||=Selenium::WebDriver.for(:remote, :desired_capabilities=>caps, :url=>url)
 Appium.promote_appium_methods AppiumWorld
 World do
   AppiumWorld.new
 end

 Before { $driver.start_driver }
 After { $driver.driver_quit }
```

Thank you

**Comment by Asimk21** [comment]
This is how it looks like for android. You can try it for ios just by changing caps

```
require 'appium_lib'

desired_capabilities= {
        caps: {
              platformName: 'Android',
              deviceName: 'deviceID',
              automationName: 'Appium',
              browserName: 'chrome'
        },
        appium_lib:{
              server_url: 'http://0.0.0.0:4723/wd/hub/'
        }
}

@driver = Appium::Driver.new(desired_capabilities)
@driver.start_driver.manage.timeouts.implicit_wait = 10

puts @driver.class
puts @driver.driver.class

```

**Comment by EugeneMarrow** [comment]
@Asimk21  it responds with:

`An unknown server-side error occurred while processing the command. Original error: You must include a platformName capability (Selenium::WebDriver::Error::UnknownError)`

**Comment by Asimk21** [comment]
Did you not include platformName capability? What did you include in capabilities? For ios capabilities look like below

```
caps: {
        platformName: "ios",
        deviceName: DEVICE_NAME,
        platformVersion: PLATFORM_VERSION,
        udid: DEVICE_TARGET_UDID,
        app: APP_PATH,
        automationName: 'XCUITest'
    },
    appium_lib:{
       port: APPIUM_PORT
    }
```

**Comment by EugeneMarrow** [comment]
You can see them in log I've included above, I believe there is no difference in which case it's written

**Comment by Asimk21** [comment]
Where are the logs?

**Comment by EugeneMarrow** [comment]
@Asim21here is my env.rb file if it may help:

require 'rspec/expectations'
require 'appium_lib'
require 'cucumber/ast'
require 'capybara'
require 'capybara/cucumber'
require 'appium_capybara'
require  'selenium-webdriver'

class AppiumWorld
end


def caps
       {"deviceName"=> "iPhone 6s",
        "platformName"=> "iOS",
        #"browserName"=>"Safari",
        #"startIWDP"=>"true",
        "platformVersion"=> "10.3.1",
        "udid"=> "7cb9e60a22f9a3982523298ecbf806ba1b96c469",
        "app"=> "/Users/macpad/Projects/louder/Louder.me.ipa",
        "bundleId"=> "com.musicplatform.louderme",
        'noReset' => "true"
      }
end

def url 
   "http://localhost:4723/wd/hub" 
 end
 
 @driver = Appium::Driver.new(caps)
 @driver.driver ||=Selenium::WebDriver.for(:remote, :desired_capabilities=>caps, :url=>url)
 Appium.promote_appium_methods AppiumWorld
 World do
   AppiumWorld.new
 end

 Before { $driver.start_driver }
 After { $driver.driver_quit }

**Comment by KazuCocoa** [comment]
I've attached an example to use `capybara`  https://github.com/appium/appium/issues/8458#issuecomment-304413916 for https://github.com/appium/ruby_lib/issues/595#issuecomment-304309871

**Comment by EugeneMarrow** [comment]
@KazuCocoa Maybe you have any suggestions on this topic?

**Comment by KazuCocoa** [comment]
1st:

If you'd like to handle WebView context, you don't need to use `Selenium::WebDriver.for(:remote, :desired_capabilities=>caps, :url=>url)` because Appium support  it and `ruby_lib` is included selenium-webdriver. So, you can call selenium methods from `@driver` which defined in `@driver = Appium::Driver.new(caps)`.

https://github.com/appium/appium/blob/081907906991b8bea2018693c7f4b2abc770ccef/docs/en/advanced-concepts/hybrid.md

2nd:

I update appium_capybara's example to work with latest `appium_lib`. The example has no error such as the platformName error. So, I think you can conduct your test with updating the example.
https://github.com/KazuCocoa/appium_capybara/tree/example_for_8458/example

**Comment by KazuCocoa** [comment]
close because the issue is not active
