### ISSUE TITLE
refine Appium ruby binding

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#602]
Just proposal.

Current Appium ruby binding have many monkey patches for Selenium webdriver.
So, the library is affected by selenium-webdriver's changes such as _Update selenium-webdriver related methods #558_ .

To reduce the impact and enhance maintainability, I'd like to refine the implementations.

---

1. refactor/rewrite the library such as selenium's other drivers
2. ...?

----

- Selenium
    - [driver](https://github.com/goinstant/ruby-selenium-webdriver/blob/master/lib/selenium/webdriver/common/driver.rb)
        - ruby_lib call [here](https://github.com/goinstant/ruby-selenium-webdriver/blob/master/lib/selenium/webdriver/common/driver.rb#L32)
    - [remeote/bridge](https://github.com/goinstant/ruby-selenium-webdriver/blob/master/lib/selenium/webdriver/remote/bridge.rb)

----

## for various drivers
- default(iOS or Android) inherit selenium
    - bridge for Android, override default driver for some Android specific methods
        - uiautomator1
        - uiautomator2
        - espresso
        - ...
    - bridge for iOS, override default driver for some iOS specific methods
        - UIAutomation
        - XCUITest
        - EarlGrey, etc...

----

- example

```ruby
    class Driver
      include SearchContext

      class << self
        def for(os, driver, opts = {})
          listener = opts.delete(:listener)

          bridge = case os
            when :android
               case driver
               when :uiautomator2
                 Android::UIAutomator2::Bridge.new(opts)
               when :espresso
                 Android::Espresso::Bridge.new(opts)
               else # default for android
                 Android::UIAutomato1::Bridge.new(opts)
            when :ios
               case driver
               when :xcuitest
                 IOS::XCUITest::Bridge.new(opts)
               when :earlgrey
                 IOS::EarlGrey::Bridge.new(opts)
               else # default for ios
                 IOS::UIAutomation::Bridge.new(opts)
            else
              # Default::Bridge < :: Selenium::WebDriver::Driver::Remote::Bridge
              Default::Bridge.new(ops) # default. Each driver inherit this default bridge
          end

          bridge = Support::EventFiringBridge.new(bridge, listener) if listener

          new(bridge)
        end
      end
```

**Comment by jlipps** [comment]
I would not be opposed to a total rewrite. I think @KazuCocoa and @titusfortner might also have ideas on that

**Comment by KazuCocoa** [comment]
Previously, I and @vbanthia discussed the topic, so I mention him.

**Comment by KazuCocoa** [comment]
first, adding deprecation marks for unused or used rarely methods.

**Comment by titusfortner** [comment]
For the record, I think the best approach here would be to create a `ruby_core` gem that allows for easy extensibility for things like Capybara & Watir syntax. The `ruby_lib` can continue to be backward compatible by implementing its collection of helper methods on top of `ruby_core`.

**Comment by KazuCocoa** [comment]
👀 
I'll check https://github.com/watir/watir

**Comment by KazuCocoa** [comment]
memo

- checking all APIs if we can remove or not
    - `location_rel` is needed

**Comment by KazuCocoa** [comment]
concept:

1. re-struct `ruby_lib` like the following.
 ```
lib/appium_lib.rb
    /appium_lib
        /core # inherit selenium-webdriver and minimal spec to communicate with Appium server
        /drivers
            /android # extend core
                /common
                /uiautomator2
                /espresso
            /ios
                /common
                /xcuitest
        appium.rb
        source_labs.rb # sauce labs specific functions
        driver.rb # ruby_lib's driver
```

2. separate `core` as `appium_lib_core`, for example

**Comment by KazuCocoa** [comment]
todo

- [ ] update https://github.com/appium/appium_capybara

**Comment by KazuCocoa** [comment]
progress:

- `lib/appium_lib/core`
    - Minumul core driver
- `lib/appium_lib/common`
    - Appium related(include sauce labs)
- `lib/appium_lib/android`
    - Android related
- `lib/appium_lib/ios`
    - iOS related

**Comment by KazuCocoa** [comment]
re-consider to move android/ios related core part move to `lib/appium_lib/core`.
`core` means SearchContext, Device and some main parts.

- `lib/appium_lib/core`
    - `lib/appium_lib/core/android`
    - `lib/appium_lib/core/ios`
- `lib/appium_lib/common`
- `lib/appium_lib/android`
- `lib/appium_lib/ios`
- the other
    - include sauce labs

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib/pull/669#issuecomment-331611988

**Comment by KazuCocoa** [comment]
release after summarising changes

**Comment by KazuCocoa** [comment]
https://rubygems.org/gems/appium_lib/versions/9.7.0
Release once. I'll continue to work separating `core` and updating documentation.
