### ISSUE TITLE
Why send_keys to EditText will add placeholder in its value in Android emulator?? 

### ISSUE THREAD

**Issue by rogerluo410** [appium/ruby_lib#612]
send_keys('1111')  in code

but, it enterred placeholder string in front of the send key string from the soft keyboard.  
It's ok in iOS simulator

Is this really an issue of appium lib in Android emulator? Or, I made a mistake that the API of typing from soft keyboard  has a little of different between iOS  and Android?  
![11111](https://user-images.githubusercontent.com/5260711/27697760-c20a67fe-5d27-11e7-80b7-32ac7b40c3d8.jpg)

Versions: 
Appium 1.6.6
Ruby_lib 9.4.8
Android 7.1.1
Android API 25 

Reference: 
https://discuss.appium.io/t/android-appium-1-2-2-sendkeys-issue-with-hinted-edit-text/309

**Comment by KazuCocoa** [comment]
@rogerluo410

I'm not sure it's the driver side or OS side issue.
Which `automationName` do you use `appium` or `uiautomator2`?
How about Android6.x and emulator or a real device?

Anyway, it's not `ruby_client` side's issue since `send_keys` in `ruby_client` just calls selenium-webdriver's `send_keys`.

**Comment by KazuCocoa** [comment]
Or how about the following method?

```
textfields[0].send_keys('1111')
```

If the above works well, your `find_element` finds a wrong element you should send `send_keys`.

**Comment by rogerluo410** [comment]
@KazuCocoa , 

Thanks , I will try it.

**Comment by rogerluo410** [comment]
![image](https://user-images.githubusercontent.com/5260711/27779654-0b559e52-5ff7-11e7-91de-2f7147412e97.png)

Not works! 

My code snippet is : 

     def assert_exists
        @email_input = textfields[0]
        @password = textfields[1]

         @email_input.send_keys('daisy_davis@example.com')
        @password.send_keys('xxxxx')
      end


the login page has two edittexts

**Comment by ochubey** [comment]
If you manually click on email address field - will 'Email address' text remain in it?
If so - do `@email_input.clear()` before sending keys. `send_keys` will append text and not replace it.

**Comment by rogerluo410** [comment]
@KazuCocoa @ochubey  

It's ok when automationName = uiautomator2 in caps. 


Thank you all

**Comment by kazu-matsu** [comment]
👍 , and thanks for your support! @ochubey

**Comment by KazuCocoa** [comment]
👍 , and thanks for your support! @ochubey
