### ISSUE TITLE
Can't find the element when the element is flowing on the page (zIndex = 1)

### ISSUE THREAD

**Issue by rogerluo410** [appium/ruby_lib#630]
## This is a
* [ ] Bug report
* [x ] Question
* [ ] Freature Request

## Summary

Can't find the element when the element flows on the page (zIndex = 1). If can not find the element which flows, how to solve? 

## Environment
* Appium version (or git revision): 1.6.5
* `ruby_lib` version: 9.4.9
* Mobile platform/version/device under test:  iOS / 10.3 / iPhone6 simulator

## Link to Appium/Ruby logs

https://gist.github.com/rogerluo410/b29209edd0d8ce246d3d1d6adcabcc4b

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 

## Any additional comments

The button "Start Now" has `zIndex = 1` property, so it flows on the page, I can found the element in the page,  but unable to find the `zIndex =1`'s element with xPath.  

`page.find_elements(:xpath, "//XCUIElementTypeOther[@label='Start Now']") `. 

by the way, my Automation is XCUITest. 

Thanks.

**Comment by KazuCocoa** [comment]
It depends on WebDriverAgemt, I guess.

Can you find the element with predicate, accessibility_id or name?

**Comment by KazuCocoa** [comment]
And how about using `:class_chain` to find the element?

**Comment by rogerluo410** [comment]
@KazuCocoa , How to use :class_chain ?

page.find_elements(:name, "Start Now") , no use of it.

**Comment by rogerluo410** [comment]
No use of it

**Comment by KazuCocoa** [comment]
https://github.com/facebook/WebDriverAgent/blob/841271771f5f69dbf50184a591faa15f5cb8d2e4/WebDriverAgentLib/Utilities/FBXPath.m#L197
It looks webdriveragent doesn't support `zindex` attributes.
@rogerluo410

**Comment by KazuCocoa** [comment]
this issue is not `ruby_lib` related one.
