### ISSUE TITLE
Should we remove "count" option from touch_action commands?

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#644]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary

https://discuss.appium.io/t/ruby-appium-touchaction-perform-returns-error-method-has-not-yet-been-implemented/18308

`tap` hasn't been changed so long time(around a few years?). But I'll check `:fingers` and `:count` options if they are redundant current spec or not.

https://github.com/appium/java-client/blob/08fe157d46ae86c3f848ad9751310a9090580b4c/src/main/java/io/appium/java_client/TouchAction.java#L158

## Environment
* Appium version (or git revision): 
* `ruby_lib` version: 9.6.0
* Mobile platform/version/device under test:

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
I'll take a look

**Comment by mykola-mokhnach** [comment]
Probably, it is just not necessary to include _count_ key into options if it is equal to its default value (let say for a single tap it will always be 1)
