### ISSUE TITLE
rotate method not working

### ISSUE THREAD

**Issue by jeet4320** [appium/ruby_lib#652]
## This is a
* [ ] Bug report

## Summary
Methods like Rotate, scroll_up, text_exact are not working with capybara appium driver.
https://github.com/appium/appium_capybara/blob/master/lib/appium_capybara/driver/appium/driver.rb#L83

## Environment
* Appium version (or git revision): 1.6.6-beta.4
* `ruby_lib` version: 
* Mobile platform/version/device under test: iOS 10

## Actual behaviour and steps to reproduce
capabilities_iOS = {
  deviceName: "iPhone 7",
  platformName: "iOS",
  app: ipa_file_path,
  automationName: "XCUITest",
  platformVersion: "10.3.3",
  udid: "****",
  showXcodeLog: "true",
  xcodeOrgId: "***",
  xcodeSigningId: "***",
  autoGrantPermissions: true
}

Capybara.register_driver(:appium_iOS) do |app|
  appium_lib_options_iOS = {
      server_url:           url
  }
  all_options_iOS = {
      appium_lib:  appium_lib_options_iOS,
      caps:        capabilities_iOS
  }
 Appium::Capybara::Driver.new app, all_options_iOS
end
## Expected behaviour
Methods like Rotate, scroll_up, text_exact should work with capybara appium driver

## Link to Appium/Ruby logs
tried commands in pry debug mode like page.driver.appium_driver.driver.rotate :landscape, Capybara.current_session.driver.appium_driver.driver.rotate :landscape
but getting error as 

Selenium::WebDriver::Error::NoSuchDriverError: A session is either terminated or not started
from /Users/jeetendrapatil/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.5.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
https://gist.github.com/jeet4320/c5bc7cfedc138898427359dadbd77a07
## Any additional comments
no

**Comment by KazuCocoa** [comment]
In most cases, the error is raised when already driver session is terminated.

Could you also attach Appium server side error logs? @jeet4320 


The following is examples to call `rotate` in `ruby_lib`'s test cases, and `ruby_lib` called `/wd/hub/session/cbf5e309-2491-4cda-b5a6-54100e783d31/orientation` correctly.

- ruby_lib
```
[4] pry(#<driver>)> $driver.driver.rotate :portrait
=> "PORTRAIT"
[5] pry(#<driver>)> $driver.driver.rotate :landscape
=> "LANDSCAPE"
```

- Appium server side logs
```
[HTTP] <-- POST /wd/hub/session/cbf5e309-2491-4cda-b5a6-54100e783d31/timeouts/implicit_wait 200 7 ms - 76
[HTTP] --> POST /wd/hub/session/cbf5e309-2491-4cda-b5a6-54100e783d31/orientation {"orientation":"PORTRAIT"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/cbf5e309-2491-4cda-b5a6-54100e783d31/orientation] to [POST http://localhost:8100/session/BF886B2F-78AA-42AF-9EAD-60FCE29182E0/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"BF886B2F-78AA-42AF-9EAD-60FCE29182E0","status":0}
[JSONWP Proxy] Replacing sessionId BF886B2F-78AA-42AF-9EAD-60FCE29182E0 with cbf5e309-2491-4cda-b5a6-54100e783d31
[HTTP] <-- POST /wd/hub/session/cbf5e309-2491-4cda-b5a6-54100e783d31/orientation 200 1205 ms - 74
[HTTP] --> POST /wd/hub/session/cbf5e309-2491-4cda-b5a6-54100e783d31/orientation {"orientation":"LANDSCAPE"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/cbf5e309-2491-4cda-b5a6-54100e783d31/orientation] to [POST http://localhost:8100/session/BF886B2F-78AA-42AF-9EAD-60FCE29182E0/orientation] with body: {"orientation":"LANDSCAPE"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unable To Rotate Device","sessionId":"BF886B2F-78AA-42AF-9EAD-60FCE29182E0","status":777}
[JSONWP Proxy] Replacing sessionId BF886B2F-78AA-42AF-9EAD-60FCE29182E0 with cbf5e309-2491-4cda-b5a6-54100e783d31
[HTTP] <-- POST /wd/hub/session/cbf5e309-2491-4cda-b5a6-54100e783d31/orientation 200 6322 ms - 99
[BaseDriver] Shutting down because we waited 60 seconds for a command
```

**Comment by jeet4320** [comment]
I added below code and it started working:
Appium::Driver.new(capabilities_iOS)
Appium.promote_appium_methods Cucumber
