### ISSUE TITLE
iOS: Log capture broken! Ruby Client!

### ISSUE THREAD

**Issue by reach2jeyan** [appium/ruby_lib#654]
I am trying to fetch the logs with appium for iOS application. But I am thrown an undefined error for the code, which was working previously with appium.

I have tried this code in 1.6.4, 1.6.5 and 1.6.5beta but in vain.

To fetch the logs code
```
$driver.get_log(“crashlog”)
$driver.get_log(“syslog”)
```
My Desired capabilities has
`showIOSLog: "true"`

The error I get:
`undefined methodget_log’ for #Appium::Driver:0x007f8876165610`

I am using Xcode version more than 8.

Has the code changed? or is this still an open issue?

**Comment by KazuCocoa** [comment]
the command is defined in webdriver side and `ruby_lib` apply the command in https://github.com/appium/ruby_lib/blob/8a7c386a51e9f83826e1d5d799cc509cd0c7e3ae/lib/appium_lib/common/patch.rb#L173 , and `OSS` module has the command but `W3C` module hasn't.

1. Could you tell me the current `ruby_lib` and `selenium-webdriver` version?
    - And if you can know, let me know the `working previously` `ruby_lib` version.
2. What about the following commands?
 ```
$driver.driver. get_log(“ syslog”)
$driver.driver.log(“ syslog”)
```

@reach2jeyan

**Comment by reach2jeyan** [comment]
@KazuCocoa I tried using both the commands you gave. I get this error
```
undefined method `log' for #<Appium::Driver:0x007ff9352a3100>
      Did you mean?  lock (NoMethodError)
      ./Features/Support/hooks.rb:23:in `After'
```

**Comment by KazuCocoa** [comment]
> `gem 'appium_lib', '~> 9.4.6`

Hm, you use `ruby_lib` which hadn't supported `OSS` and `W3C` module yet.

You've described _which was working previously with appium_ in the description, could you tell me the version the command works?

**Comment by reach2jeyan** [comment]
I didn't make a note of the `appium_lib` that I used. But it was working well before Appium upgraded to support the XCUI framework.

**Comment by KazuCocoa** [comment]
I found the cause.

temporary, you can call the method like the following.

```ruby
driver.manage.logs.get type

# or

driver.send(:bridge).get_log
```

**Comment by reach2jeyan** [comment]
@KazuCocoa Thanks for coming back. Like you mentined I tried using
`driver.manage.logs.get("syslog)`  - Doesn't throw any error, also does not fetch logs
`driver.send(:bridge).get_log` - Throws `get_log` undefined method

**Comment by KazuCocoa** [comment]
I'll check again after my work. Could you tell me the version of `selenium-webdriver`?
Some methods depend on the `webdriver` version. I'd like to check the behaviour using the same version.

And if you can attach the server side logs here, can you attach it?
especially _driver.manage.logs.get("syslog") - Doesn't throw any error, also does not fetch logs_ case.
@reach2jeyan

**Comment by KazuCocoa** [comment]
I could get `selenium-webdriver 3.4.0` and `appium_lib 9.4.10 and 9.6.1` against appium `master` and `1.6.4`

```
$driver.driver.manage.logs.get("syslog")
```

## Run tests in `ruby_lib/ios_tests`
```
[2] pry(#<the web context>)> $driver.driver.manage.logs.get("syslog")
=> [#<Selenium::WebDriver::LogEntry:0x007fdda43508e8
  @level="ALL",
  @message="Sep  1 08:53:15 rrcs-172-254-99-28 systemsoundserver-simd[24744]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0",
  @timestamp=1504223595139>,
 #<Selenium::WebDriver::LogEntry:0x007fdda35a3a10
  @level="ALL",
  @message="Sep  1 08:53:15 rrcs-172-254-99-28 CoreSimulatorBridge[24530]: Pasteboard change listener callback port <NSMachPort: 0x7f832a741f90> registered",
  @timestamp=1504223595173>,
 #<Selenium::WebDriver::LogEntry:0x007fdda35a2c50
  @level="ALL",
  @message="Sep  1 08:53:15 rrcs-172-254-99-28 CoreSimulatorBridge[24530]: Pasteboard change listener callback port <NSMachPort: 0x7f832a5550b0> registered",
  @timestamp=1504223595418>,
```
@reach2jeyan

**Comment by reach2jeyan** [comment]
I am using
```
gem 'selenium-webdriver', '~> 3.4.0'
gem 'appium_lib', '~> 9.4.6'
```

**Comment by reach2jeyan** [comment]
I updated the gem to 
```
gem 'appium_lib', '~> 9.6.1'
gem 'selenium-webdriver', '~> 3.5.1'
```
and did a bundle update. Still, a log wouldn't get created

**Comment by KazuCocoa** [comment]
Hmm..

Could you attach the full debug logs on Appium server side?

**Comment by KazuCocoa** [comment]
Any updates for the log?

**Comment by KazuCocoa** [comment]
^ @reach2jeyan

**Comment by reach2jeyan** [comment]
@KazuCocoa I am really sorry for the delay. I'll attach it today for sure.

**Comment by reach2jeyan** [comment]
`[debug] [MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAKbAAAAKAAAApsAAAKbAAC4wUHa91sAAEAASURBVHgB\r\n7L3nlxzVue//+xvuPeu+OWvdV+ecdY8kshFJmhw1M5pRFsoJSShHlFDOWSIJEUQQ\r\nOYggkbOETbDBBBtjE4yxMWDAJAM2xuzf/m6dPVNT6p7p7ulQ1f2ptXq6p7vCrv18\r\nqvb32fXsZ/9//33uYMOLOoABGIABGIABGIABGICBaDPw/2GgaBsI+2AfGIABGIAB\r\nGIABGIABMYBw54kDT1xgAAZgAAZgAAZgAAZiwADCPQZGwsvGy4YBGIABGIABGIAB\r\nGEC4I9zxsGEABmAABmAABmAABmLAAMI9BkbCw8bDhgEYgAEYgAEYgAEYQLgj3PGw\r\nYQAGYAAGYAAGYAAGYsAAwj0GRsLDxsOGARiAARiAARiAARhAuCPc8bBhAAZgAAZg\r\nAAZgAAZiwADCPQZGwsPGw4YBGIABGIABGIABGEC4I9zxsGEABmAABmAABmAABmLA\r\nAMI9BkbCw8bDhgEYgAEYgAEYgAEYQLgj3PGwYQAGYAAGYAAGYAAGYsAAwj0GRsLD\r\nxsOGARiAARiAARiAARhAuCPc8bBhAAZgAAZgAAZgAAZiwADCPQZGwsPGw4YBGIAB\r\nGIABGIABGEC4I9zxsGEABmAABmAABmAABmLAAMI9BkbCw8bDhgEYgAEYgAEYgAEY\r\nQLgj3PGwYQAGYAAGYAAGYAAGYsAAwj0GRsLDxsOGARiAARiAARiAARhAuCPc8bBh\r\nAAZgAAZgAAZgAAZiwADCPQZGwsPGw4YBGIABGIABGIABGEC4I9zxsGEABmAABmAA\r\nBmAABmLAAMI9BkbCw8bDhgEYgAEYgAEYgAEYQLgj3PGwYQAGYAAGYAAGYAAGYsAA\r\n...
[HTTP] <-- GET /wd/hub/session/f5425461-ceec-482b-9759-58e8b468bf59/screenshot 200 55 ms - 150634 
[HTTP] --> POST /wd/hub/session/f5425461-ceec-482b-9759-58e8b468bf59/log {"type":"syslog"}
[debug] [MJSONWP] Calling AppiumDriver.getLog() with args: ["syslog","f5425461-ceec-482b-9759-58e8b468bf59"]
[debug] [XCUITest] Executing command 'getLog'
[debug] [iOS] Retrieving 'syslog' logs
[debug] [MJSONWP] Responding to client with driver.getLog() result: [{"timestamp":1505742328527,"level":"ALL","message":"oreSimulatorBridge[63767]: Pasteboard change listener callback port <NSMachPort: 0x7f883ef378f0> registered"},{"timestamp":1505742328596,"level":"ALL","message":"Sep 18 19:15:28 Mrityunjeyans-Mac-mini CoreSimulatorBridge[63767]: Pasteboard change listener callback port <NSMachPort: 0x7f883ef379a0> registered"},{"timestamp":1505742329662,"level":"ALL","message":"Sep 18 19:15:29 Mrityunjeyans-Mac-mini Sequoia[79780]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0"},{"timestamp":1505742329917,"level":"ALL","message":"Sep 18 19:15:29 Mrityunjeyans-Mac-mini CoreSimulatorBridge[63767]: Pasteboard change listener callback port <NSMachPort: 0x7f883ef37a50> registered"},{"timestamp":1505742330016,"level":"ALL","message":"Sep 18 19:15:30 Mrityunjeyans-Mac-mini CoreSimulatorBridge[63767]: Pasteboard change listener callback port <NSMachPort: 0x7f883ed2d6f0> registered"},{"timestamp":1505742330045,"level":"ALL","message":"Sep 18 19:15:30 Mrityunjey...
[HTTP] <-- POST /wd/hub/session/f5425461-ceec-482b-9759-58e8b468bf59/log 200 21 ms - 106130 
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 --- last message repeated 14 times ---
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 Mrityunjeyans-Mac-mini Sequoia[79855]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 --- last message repeated 14 times ---
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 Mrityunjeyans-Mac-mini Sequoia[79855]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 --- last message repeated 14 times ---
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 Mrityunjeyans-Mac-mini Sequoia[79855]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 --- last message repeated 14 times ---
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 Mrityunjeyans-Mac-mini Sequoia[79855]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 --- last message repeated 14 times ---
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 Mrityunjeyans-Mac-mini Sequoia[79855]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 --- last message repeated 14 times ---
[iOSLog] [IOS_SYSLOG_ROW] Sep 18 19:17:46 Mrityunjeyans-Mac-mini Sequoia[79855]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0
`

**Comment by KazuCocoa** [comment]
thanks! @reach2jeyan

It looks you can get some system logs, but it's probably too long...?

```
[
  {"timestamp":1505742328527,"level":"ALL","message":"oreSimulatorBridge[63767]: Pasteboard change listener callback port <NSMachPort: 0x7f883ef378f0> registered"},
  {"timestamp":1505742328596,"level":"ALL","message":"Sep 18 19:15:28 Mrityunjeyans-Mac-mini CoreSimulatorBridge[63767]: Pasteboard change listener callback port <NSMachPort: 0x7f883ef379a0> registered"},
  {"timestamp":1505742329662,"level":"ALL","message":"Sep 18 19:15:29 Mrityunjeyans-Mac-mini Sequoia[79780]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0"},
  {"timestamp":1505742329917,"level":"ALL","message":"Sep 18 19:15:29 Mrityunjeyans-Mac-mini CoreSimulatorBridge[63767]: Pasteboard change listener callback port <NSMachPort: 0x7f883ef37a50> registered"},
  {"timestamp":1505742330016,"level":"ALL","message":"Sep 18 19:15:30 Mrityunjeyans-Mac-mini CoreSimulatorBridge[63767]: Pasteboard change listener callback port <NSMachPort: 0x7f883ed2d6f0> registered"},
  {"timestamp":1505742330045,"level":"ALL","message":"Sep 18 19:15:30 Mrityunjey...
```

and we can see the error on [google search](https://www.google.co.jp/search?dcr=0&q=Pasteboard+change+listener+callback+port++registered&oq=Pasteboard+change+listener+callback+port++registered&gs_l=psy-ab.3...10837.10837.0.11121.1.1.0.0.0.0.108.108.0j1.1.0.foo%2Cnso-ehuqi%3D1%2Cnso-ehuui%3D1%2Cewh%3D0%2Cnso-mplt%3D2%2Cnso-enksa%3D0%2Cnso-enfk%3D1%2Cnso-usnt%3D1%2Cnso-qnt-npqp%3D0-1701%2Cnso-qnt-npdq%3D0-54%2Cnso-qnt-npt%3D0-1%2Cnso-qnt-ndc%3D300%2Ccspa-dspm-nm-mnp%3D0-05%2Ccspa-dspm-nm-mxp%3D0-125%2Cnso-unt-npqp%3D0-17%2Cnso-unt-npdq%3D0-54%2Cnso-unt-npt%3D0-0602%2Cnso-unt-ndc%3D300%2Ccspa-uipm-nm-mnp%3D0-007525%2Ccspa-uipm-nm-mxp%3D0-052675%2Ccfro%3D1...0...1.1.64.psy-ab..0.0.0....0.Co9SxFg9Efw)

**Comment by reach2jeyan** [comment]
@KazuCocoa  So the system doesn't generate the logs because, the file size may be too large?

Any work around for this?

**Comment by KazuCocoa** [comment]
@reach2jeyan 
I don't know the exact workaround, but how about clear system.log once before running tests?

I guess you can find system.log like `~/Library/Logs/CoreSimulator/<DEVICE_CODE>/system.log` path if you use simulators.

**Comment by reach2jeyan** [comment]
@KazuCocoa If that is the problem? How do I clear the system log each time before a log is generated or pick the last 1000 lines?

Like on android you have `adb logcat -c` Is there a command here?

**Comment by KazuCocoa** [comment]
In android case, you can probably set and restrict logcat's buffer size via adb command. It helps to limit device log size.

For iOS, getting device code to detect the path by `xcrun simctl` and remove logs before starting test or other timing, or you can create a PR to appium to erase the logs because appium already has code removing simulators, I guess.

**Comment by reach2jeyan** [comment]
Thanks @KazuCocoa i ll try clearing up the system logs tomorrow and try what you said and see if that is the problem

**Comment by reach2jeyan** [comment]
@KazuCocoa I cleared all the log files in my mac machine and I tried generating the logs with the code you gave, and still the same result.

**Comment by KazuCocoa** [comment]
hm..

Could you attach the logs like https://github.com/appium/ruby_lib/issues/654#issuecomment-330227105 ?
If the log section is the same as https://github.com/appium/ruby_lib/issues/654#issuecomment-330234856 , the path to logs is not https://github.com/appium/ruby_lib/issues/654#issuecomment-330880144 ...?

And try with the latest Appium to get the system logs?

**Comment by KazuCocoa** [comment]
📝 
https://github.com/appium/appium/issues/9246#issuecomment-331611747 is similar issue?

**Comment by reach2jeyan** [comment]
@KazuCocoa 

PFB the logs

`Calling AppiumDriver.getLog() with args: ["syslog","4ff86b33-6afe-4c18-88fb-5652a8c58b99"]
[debug] [XCUITest] Executing command 'getLog'
[debug] [iOS] Retrieving 'syslog' logs
[debug] [MJSONWP] Responding to client with driver.getLog() result: [{"timestamp":1506321148739,"level":"ALL","message":"imulatorBridge[29153]: Pasteboard change listener callback port <NSMachPort: 0x7f91a372a700> registered"},{"timestamp":1506321148825,"level":"ALL","message":"Sep 25 12:02:28 Admins-MacBook-Pro CoreSimulatorBridge[29153]: Pasteboard change listener callback port <NSMachPort: 0x7f91a3548c00> registered"},{"timestamp":1506321150270,"level":"ALL","message":"Sep 25 12:02:30 Admins-MacBook-Pro CoreSimulatorBridge[29153]: Pasteboard change listener callback port <NSMachPort: 0x7f91a3440f00> registered"},{"timestamp":1506321150393,"level":"ALL","message":"Sep 25 12:02:30 Admins-MacBook-Pro Sequoia[52083]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0"},{"timestamp":1506321150404,"level":"ALL","message":"Sep 25 12:02:30 Admins-MacBook-Pro CoreSimulatorBridge[29153]: Pasteboard change listener callback port <NSMachPort: 0x7f91a3443eb0> registered"},{"timestamp":1506321150419,"level":"ALL","message":"Sep 25 12:02:30 Admins-MacBook-Pro installd[29...
[HTTP] <-- POST /wd/hub/session/4ff86b33-6afe-4c18-88fb-5652a8c58b99/log 200 5 ms - 104927 
[iOSLog] [IOS_SYSLOG_ROW] Sep 25 12:04:52 --- last message repeated 14 times ---
[iOSLog] [IOS_SYSLOG_ROW] Sep 25 12:04:52 Admins-MacBook-Pro Sequoia[52699]: [aqme] 254: AQDefaultDevice (173): skipping input stream 0 0 0x0

`

**Comment by reach2jeyan** [comment]
@KazuCocoa The issue that you referenced to, appears to be similar to mine.

**Comment by reach2jeyan** [comment]
@KazuCocoa Out of box, on a side note, could I get your help on this one

http://discuss.appium.io/t/cucumber-ruby-distributed-tests-in-ios/18889

**Comment by KazuCocoa** [comment]
@reach2jeyan I put a comment on the post, but it just an example...

---

btw, I have no additional idea for this issue, sorry.
We need to watch appium/appium#9246 and updates.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/9246#issuecomment-331855940

**Comment by KazuCocoa** [comment]
close since logger itself isn't a ruby_lib side issue.
