### ISSUE TITLE
Find element using iOSClassChain locator strategy

### ISSUE THREAD

**Issue by himankarbn** [appium/ruby_lib#659]
Need help... So far we have been using XCUITest for our automation. We recently started with Appium Ruby and would like to use class_chain locator type strategy but we are having some trouble with it. Here is a the sample tree of our login screen
![screen shot 2017-09-06 at 10 12 14 am](https://user-images.githubusercontent.com/11064961/30123308-307a4ab0-92f7-11e7-8389-906011230199.png)

In XCTest to get the Password text field we use `table.cells.containing(.staticText, identifier:"Password").children(matching: .secureTextField).element`

Is there a better/shorter way to find the password field using class_chain ?
`find_elements(:class_chain, 'XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[3]/XCUIElementTypeStaticText')[0]`

**Comment by KazuCocoa** [comment]
@himankarbn 

You can probably find it with <code>find_element(:class_chain, "**/XCUIElementTypeStaticText]")</code> if you'd like to search it with shorter way. You can see the query variation on _using class chain_ section in [here](https://github.com/facebook/WebDriverAgent/wiki/Queries#searching-for-elements)

---

BTW, you can also find the element with <code>[textfields](https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/ios/xcuitest/element/textfield.rb#L41)[0]</code> or <code>[tags](https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/ios/xcuitest/helper.rb#L50)(::Appium::Ios::XCUIElementTypeSecureTextField)[0]</code>. They work with `ios_predicate` strategy, though.

**Comment by mykola-mokhnach** [comment]
`table.cells.containing(.staticText, identifier:"Password").children(matching: .secureTextField).element` will look like

```
**/XCUIElementTypeTable/XCUIElementTypeCell[`name CONTAINS 'Password'`]/XCUIElementTypeSecureTextField
```

in class chain notation. Also, make sure you use the recent Appium beta release, otherwise the locator won't work.

**Comment by himankarbn** [comment]
@KazuCocoa : appreciated a lot for the quick response. 
I tried this before as well and 
`find_element(:class_chain, "**/XCUIElementTypeStaticText]")` throws error
```find_element(:class_chain, "**/XCUIElementTypeStaticText]")
Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.
from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'``` 

Currently we are using `textfields` but wanted to know more about `class_chain` and other such locators similar to XCtest.

**Comment by mykola-mokhnach** [comment]
Read https://github.com/facebook/WebDriverAgent/wiki/Queries for more details about class chain locators

**Comment by KazuCocoa** [comment]
oops, `]` is the waste mark in my previous comment...

**Comment by himankarbn** [comment]
Yeah I tried with `]`

**Comment by himankarbn** [comment]
current appium version is `1.6.5`
```find_element(:class_chain, "**/XCUIElementTypeStaticText")
Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.
from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'```

**Comment by himankarbn** [comment]
@mykola-mokhnach : I used your above query and got the same error. Not sure what I am missing.
```find_element(:class_chain, "**/XCUIElementTypeTable/XCUIElementTypeCell[`name CONTAINS 'Password'`]/XCUIElementTypeSecureTextField")```

P.S All the examples I have seen for `class_chain` are mostly for `java_client`.

**Comment by KazuCocoa** [comment]
hm...

- What about `tags('XCUIElementTypeSecureTextField')`?
    - The `tag` methods get elements by class name with `predicate`.
    - If we get the elements with `predicate`, class chain failed to find the element or query was wrong, I guess.

If can't get any elements, could you get elements with `page`/`get_source` command?
The commands prints available elements on the screen. If the element doesn't exist in the printed lines, Appium server probably couldn't get the element.

**Comment by mykola-mokhnach** [comment]
@himankarbn 
Please read my comment above one more time:

> Also, make sure you use the recent Appium beta release, otherwise the locator won't work.

**Comment by himankarbn** [comment]
I can find the element with `tags('XCUIElementTypeSecureTextField')`
```
 pry(main)>tags('XCUIElementTypeSecureTextField')
[
    [0] #<Selenium::WebDriver::Element:0xa0762b64cda014c id="BA5FF2B9-7DAD-4359-AD4A-DA44C5437ACD">
]
```
And this is what it prints from `get_source`
![screen shot 2017-09-06 at 1 43 38 pm](https://user-images.githubusercontent.com/11064961/30128788-8691bdfe-9309-11e7-8f06-4d4895d24307.png)

@mykola-mokhnach : updated to the latest beta `1.7.0-beta`version and still getting the same error.

**Comment by mykola-mokhnach** [comment]
please attach appium server log then. It should contain more detailed description of the error (if your locator, for example, has some syntactical errors).

**Comment by mykola-mokhnach** [comment]
For tree above the locator should look like

```
**/XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeSecureTextField
```

**Comment by himankarbn** [comment]
@mykola-mokhnach : found the main issue. So I was starting the server from appium Desktop which was running v1.6.5.

Staring the server from terminal resolved the issue. Able to find elements using class_chain
`find_element(:class_chain, "**/XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeSecureTextField")`

Thanks a lot to both.

**Comment by mykola-mokhnach** [comment]
@himankarbn The PR https://github.com/facebook/WebDriverAgent/pull/707 has been recently merged to our WDA fork and is available in appium@beta

Please update you server and try it. The syntax for finding elements:

```
//Bla[ .//Bla2 ] -> **/Bla[$type == 'Bla2'$]
```
