### ISSUE TITLE
star/ Double star in class_chain throwing error

### ISSUE THREAD

**Issue by himankarbn** [appium/ruby_lib#661]
Was able to use class_chain successfully previously but it started throwing errors for indirect descendant search requests since today morning.

Not sure what I am missing. Anyone came across this issue?

`$ appium -v
1.7.0-beta`

Example:
`find_element(:class_chain, 'XCUIElementTypeWindow/**/XCUIElementTypeCell')
Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.
from /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/selenium-webdriver-3.5.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'`

appium.log
 `[HTTP] --> POST /wd/hub/session/22525409-29b9-43b6-a22d-c382cd3345a2/element {"using":"-ios class chain","value":"XCUIElementTypeWindow/**/XCUIElementTypeCell"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-ios class chain","XCUIElementTypeWindow/**/XCUIElementTypeCell","22525409-29b9-43b6-a22d-c382cd3345a2"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF7000B1-E9D8-4392-B1F9-23031A384576/element] with body: {"using":"class chain","value":"XCUIElementTypeWindow/**/XCUIElementTypeCell"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Cannot parse class chain query 'XCUIElementTypeWindow/**/XCUIElementTypeCell'. Unexpected character detected at position 24:\nXCUIElementTypeWindow/** <----\n\n(\n\t0   CoreFoundation                      0x00000001045d7b0b __exceptionPreprocess + 171\n\t1   libobjc.A.dylib                     0x000000010403c141 objc_exception_throw + 48\n\t2   WebDriverAgentLib                   0x0000000115d60952 -[XCUIElement(FBClassChain) fb_descendantsMatchingClassChain:shouldReturnAfterFirstMatch:] + 402\n\t3   WebDriverAgentLib                   0x0000000115d79221 +[FBFindElementCommands elementsUsing:withValue:under:shouldReturnAfterFirstMatch:] + 897\n\t4   WebDriverAgentLib                   0x0000000115d78e25 +[FBFindElementCommands elementUsing:withValue:under:] + 149\n\t5   WebDriverAgentLib                   0x0000000115d77e9b +[FBFindElementCommands handleFindElement:] + 331\n\t6   WebDriverAgentLib                   0x0000000115d67bf3 -[FBRoute_TargetAction mountRequest:intoResponse:] + 179\n\t7  ...
[HTTP] <-- POST /wd/hub/session/22525409-29b9-43b6-a22d-c382cd3345a2/element 500 50 ms - 164`

**Comment by KazuCocoa** [comment]
What versions of **previous** Appium and ruby_lib, class chain work fine, did you use?

Anyway, it looks driver side issue since current released ruby_lib were tested with ios_test and the class chain has been included in them.

Thus, could you create an issue on the Appium repository or XCUITest driver side instead?

**Comment by mykola-mokhnach** [comment]
To me this looks like an old WDA build is used. Make sure the correct WDA build is deployed on the device.

**Comment by himankarbn** [comment]
@KazuCocoa : Both Appium and ruby_lib versions were the same previously. Only thing that changed is the app source code. 

@mykola-mokhnach : We are using simulators and I thought appium takes care of WDA build.

**Comment by mykola-mokhnach** [comment]
Appium be default tries to keep WDA server running for as long as possible to avoid unnecessary recompilation delays. Also, there is such thing like Xcode cache.

**Comment by himankarbn** [comment]
Yeah, finally got it working. After reseting the simulator and deleting the Derived data in Xcode, the issue was fixed.

thanks!
