### ISSUE TITLE
separate core as core ruby gem

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#665]
## This is a
* [ ] Bug report
* [ ] Question
* [x] Freature Request

## Summary

- separate `lib/appium_lib/core`

---

## working
- (private so far)
    - https://github.com/KazuCocoa/appium_lib_core

**Comment by KazuCocoa** [comment]
After considering and update touch action related method, I'll proceed this issue.

**Comment by KazuCocoa** [comment]
@appium/admins 
Could you create a new repository named `ruby_lib_core` under the Appium organisation? I'd like to move some of the code from https://github.com/KazuCocoa/appium_lib_core to the repository.

I'm working to separate current `ruby_lib` to `core`, minimal Appium ruby client library, and extended helpful methods, include SauceLabs, part. ( _refine Appium ruby binding #602_ )

For end-users, they can continue to use `ruby_lib`. And if anyone would like to integrate Appium related features to their library, they can use the core part and extend any methods as their favourite way.

**Comment by KazuCocoa** [comment]
@jlipps Could you take a look at ^ when you have a time?
Thanks.

**Comment by jlipps** [comment]
@KazuCocoa https://github.com/appium/ruby_lib_core. Do you have access already?

**Comment by KazuCocoa** [comment]
@jlipps 
Thanks!
No, it looks I have no access to the repository. I can create an issue but can't set labels, for example.

**Comment by jlipps** [comment]
@KazuCocoa ok I added ruby_lib_core to the committers team, you should now have access. sorry for the delay!

**Comment by KazuCocoa** [comment]
Thanks! But I haven't merged and assigned, etc, yet.

Could you check the permission again? @jlipps 

![image](https://user-images.githubusercontent.com/5511591/32356338-d1f13126-c077-11e7-9aab-15f751413068.png)

**Comment by jlipps** [comment]
Sorry looks like I had to explicitly give Write access, @KazuCocoa. Can you try again?

**Comment by KazuCocoa** [comment]
Thanks! I could. 👍

**Comment by KazuCocoa** [comment]
@jlipps 
Could you enable Travis? Since I have no permission to add it.
https://travis-ci.org/appium/ruby_lib_core

**Comment by jlipps** [comment]
@KazuCocoa ok it's enabled

**Comment by KazuCocoa** [comment]
Thanks so much!
