### ISSUE TITLE
Accessing attributes returning string instead of boolean

### ISSUE THREAD

**Issue by alvy54** [appium/ruby_lib#666]
## This is a
* [ ] Bug report
* [x] Question
* [ ] Freature Request

## Environment
* Appium version (or git revision): 1.6.4
* `ruby_lib` version: 9.6.1
* Mobile platform/version/device under test: Android

## Actual behaviour and steps to reproduce
Accessing an element's attribute is now returning the string value instead of the boolean value.  In appium_lib 9.4.9, doing something like `id('someId')[:checked]` would return `true`.  In 9.6.1, it returns `"true"`.  Is this the expected behavior now?

## Expected behaviour
Expected attributes to return boolean value instead of string value.

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
hm...
I guess it depends on `selenium-webdriver` or Appium side response and I probably haven't changed the response between the versions.

- Could you tell me the webdriver's versions against the following combinations?
    - ruby_lib `9.4.9` + Appium `1.6.4`
    - ruby_lib `9.6.1` + Appium `1.6.4`
- And if you could, could you attach the appium server logs when you call the methods?

@alvy54

**Comment by alvy54** [comment]
I apologize @KazuCocoa, the new behavior is due to using Appium 1.6.5, not because of ruby_lib 9.6.1.  Attached is the server logs.
[selenium-server.txt](https://github.com/appium/ruby_lib/files/1312642/selenium-server.txt)

**Comment by KazuCocoa** [comment]
Never mind. Thanks for the log!

ah, I understood and the log also said a string of "true" is the response.
If you use `uiautomator2`, _Fix handling of boolean return values._ is the point you mentioned here.
https://github.com/appium/appium/blob/master/CHANGELOG.md#android---uiautomator-2-1
@alvy54 

So, the current behaviour is expected one.

**Comment by mykola-mokhnach** [comment]
This is W3C requirement, that _attribute_ endpoint should either return a string or null.

**Comment by KazuCocoa** [comment]
ping @alvy54 ^ and close this because of ^
