### ISSUE TITLE
Cannot send 'source' command with custom platformName

### ISSUE THREAD

**Issue by simongranger** [appium/ruby_lib#713]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
Since 9.7.0, we cannot send 'source' command with custom platformName 'NoProxy'.

For debug purpose, we've been using 'NoProxy' platformName to solely use appium-youiengine-driver and avoid proxying some commands to either appium-xcuitest-driver or appium-android-driver.
Since 9.7.0, it seems we cannot use this anymore and are getting the following error:

```
NameError: undefined local variable or method `source' for main:Object
Did you mean?  sauce
```

## Environment
* Appium version (or git revision): 1.7.1
* `ruby_lib` version: 9.7.3
* Mobile platform/version/device under test: iOS 11.0.3

## Actual behaviour and steps to reproduce
setup caps with the following value:
```
[caps]
app = "../build/ios/Debug-iphoneos/ticketbus.app"
automationName = "YouiEngine"
deviceName = "100541"
platformName = "noproxy"
platformVersion = "10.3.2"
udid = "6f5ac6f92d1cfaa32d4308c61deb2c5cb1fe6824"
xcodeOrgId = "W4E9HL2DXS"
youiEngineAppAddress = "169.254.177.72"
```
## Expected behaviour
We should be able to send any command through ARC.

## Link to Appium/Ruby logs

```
[1] pry(main)> source
NameError: undefined local variable or method `source' for main:Object
Did you mean?  sauce
```

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
Thanks! @simongranger 

`source` was defined in iOS or Android common module.
I move the module to common module => https://github.com/appium/ruby_lib/pull/714

After running tests, I'll merge it.
As workaround fix, you call `_print_source $driver. page_source` or use my working branch.

**Comment by KazuCocoa** [comment]
merged
