### ISSUE TITLE
TouchAction doesn't work for me

### ISSUE THREAD

**Issue by sevarudakov** [appium/ruby_lib#723]
## This is a
* [ ] Question

## Summary
I try to use gestures using the following:

@driver =  Appium::Driver.new(opts, false).start_driver
Appium::TouchAction.new(@driver).tap(x: 45, y: 110, duration: 1000).release.perform

I get this error:
   Failure/Error: $driver =  Appium::Driver.new(opts, false).start_driver
   
     NameError:
       undefined local variable or method `opts' 

## Environment
* Appium version 1.7.1
* `ruby_lib` version: 9.7.5
* Mobile platform/version/device under test:
iOS Simulator, Xcode 9

## Actual behaviour and steps to reproduce
 Failure/Error: $driver =  Appium::Driver.new(opts, false).start_driver
   
     NameError:
       undefined local variable or method `opts' 

## Expected behaviour
Gestures should work

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
https://gist.github.com/sevarudakov/dc30c2ee65dcf0380ebae260b3c37775

**Comment by KazuCocoa** [comment]
What did you set `opts`?
Please refer http://www.rubydoc.info/github/appium/ruby_lib/Appium%2FDriver:initialize as an example of the `opts`.

**Comment by KazuCocoa** [comment]
@sevarudakov 
Could you read the above document first?
