### ISSUE TITLE
Do appium take screenshot from specific element, similar to Selenium WebDriver?

### ISSUE THREAD

**Issue by wellavelino** [appium/ruby_lib#726]
## This is a
* [ ] Bug report
* [ X] Question
* [ ] Freature Request

## Summary
I’ve searched a way to take screenshot from specific element on mobile automation, using appium is possible?

## Environment
* Appium version (or git revision): v1.7.1
* `ruby_lib` version: 9.7.5
* Mobile platform/version/device under test:
Android/IOs

**Comment by mykola-mokhnach** [comment]
This is not supported natively now. However you could take the full page screenshot, get element rectangle and then crop the necessary area.

**Comment by KazuCocoa** [comment]
Thanks for the response! @mykola-mokhnach 

@wellavelino As mentioned the above, currently the Appium has no feature to get screenshot only for particular elements.

**Comment by cs-wellington-santos** [comment]
@mykola-mokhnach  thanks for you answer!

@KazuCocoa its a possible feature on future?

**Comment by wellavelino** [comment]
@mykola-mokhnach thanks for you answer!

@KazuCocoa its a possible feature on future?

**Comment by KazuCocoa** [comment]
I'm not sure, but we can request a new feature(https://www.w3.org/TR/webdriver/#dfn-take-element-screenshot), I think.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa this endpoint has recently been added to the base driver. It just needs to be implemented in drivers then

**Comment by wellavelino** [comment]
@mykola-mokhnach i can request this feature? this feature to become a nice to visual regression on mobile.

**Comment by KazuCocoa** [comment]
📝 
https://github.com/appium/appium-base-driver/blob/090d94795add7a42d0fc25be6b8b04baff0d1134/lib/mjsonwp/routes.js#L510

**Comment by wellavelino** [comment]
@KazuCocoa looking again for this request i found this on ruby_lib_core

https://github.com/wellavelino/ruby_lib_core/blob/master/lib/appium_lib_core/common/device.rb#L582

I just needed implement on ruby_lib?

**Comment by KazuCocoa** [comment]
No.

`ruby_lib` just call screenshot like below.
https://github.com/appium/ruby_lib/blob/f58dacea3a003c8c7f4871fd788e9545185cb958/lib/appium_lib/driver.rb#L435-L437

And you can access the `@driver` via https://github.com/appium/ruby_lib/blob/f58dacea3a003c8c7f4871fd788e9545185cb958/lib/appium_lib/driver.rb#L71

You can call core driver methods via:

```
$driver.driver.take_element_screenshot 'filename'
# or
driver.take_element_screenshot 'filename'
```

**Comment by wellavelino** [comment]
interesting, my ideia is add a new method on ruby_lib to take screenshot from elements, im not sure about that because the endpoint has been added on ruby_lib_core, but dont have any method to access on ruby_lib.

If you think's its a good ideia can i add this new method.

**Comment by wellavelino** [comment]
So what about this method?
[https://github.com/appium/ruby_lib/blob/f58dacea3a003c8c7f4871fd788e9545185cb958/lib/appium_lib/driver.rb#L449](url)

**Comment by KazuCocoa** [comment]
ah, that is `take_element_screenshot`. It's the same thing.

**Comment by KazuCocoa** [comment]
the error is https://github.com/appium/ruby_lib_core/blob/master/lib/appium_lib_core/common/device.rb#L588 and the initialisation itself is ruby_lib_core side. You should set `.png` extention as the file name as same as `screenshot` method.

**Comment by wellavelino** [comment]
Nice!
Thank you so much @KazuCocoa, when i opened this issue i don't know about this method on ruby_lib.
Now can i use visual regression with appium :)

**Comment by abhivaikar** [comment]
@wellavelino Is the method available only for ruby right now? Or is it implemented for all clients?

**Comment by wellavelino** [comment]
@abhivaikar I do not know, I'm only looking for ruby right now. But you can search in others clients ne method name is : `element_screenshot`

**Comment by KazuCocoa** [comment]
You can call `session/:session_id/element/:id/screenshot`, which is called by this ruby method, via the other driver as well, I believe. Because Ruby client calls the method via Ruby Selenium WebDriver's W3C module method. (For non W3C, I 've added it in ruby lib core.)

So, if you use Appium 1.8.x and handle your test with W3C session, you can call it.
(But please ensure the method has been implemented in Selenium WebDriver side.)
@abhivaikar

**Comment by 141801** [comment]
@KazuCocoa  sorry , I found It  used  mjsonwp bridge . how can I  handle my test with W3C session?do any config in capabilities

**Comment by KazuCocoa** [comment]
@141801 

Could you share your capability and server logs when you create the session?
I assume:

1. you should set `automationName` as `uiautomator2`
2. W3C or MJSONWP depends on your capability's correctness. I probably guide it. (Thus, I need server log as well)

**Comment by 141801** [comment]
@KazuCocoa   Thanks for your reply, I had comment out the bridge.rb(/Users/zhangliang/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/appium_lib_core-2.0.1/lib/appium_lib_core/common/base/)  to use w3c bridge
![2018-09-28 17 59 36](https://user-images.githubusercontent.com/42635299/46199029-e1505500-c348-11e8-9e3e-095c631d678b.png)

and also get method  not  implement  error  
![2018-09-28 17 38 35](https://user-images.githubusercontent.com/42635299/46199080-0a70e580-c349-11e8-825e-3a140536efed.png)

My capability  and server logs  are as follows
![2018-09-28 18 08 46](https://user-images.githubusercontent.com/42635299/46199265-9551e000-c349-11e8-83c2-7fbfb1faadca.png)

![2018-09-28 18 12 12](https://user-images.githubusercontent.com/42635299/46199448-101afb00-c34a-11e8-8786-f1d72149f9b1.png)

**Comment by 141801** [comment]
@KazuCocoa  
> you should set automationName as uiautomator2
That  is the mistake ,my automation name use uppercase letter, Thanks very much!

**Comment by benoyjose** [comment]
@KazuCocoa I need to take screenshot of the MobileElement based screen where the selected mobileElement needs to be highlighted or in red bordered box, currently I was only able to either take complete page screenshot or by using getSubimage to filter out the selected element using co ordinates. Can you please help me with this, is there any solution, my implementation is based in Java. I tried JavaScriptExecutor, but that is applicable only to webelements.

**Comment by KazuCocoa** [comment]
> filter out the selected element using coordinates. 

Do you mean you clipped a full screen image by coordinate with imagemagic(for example)?
Appium provides take an element screenshot like `element.getScreenshotAs(OutputType.BYTES);` in Java. @benoyjose 
https://discuss.appium.io/ also help to ask questions

**Comment by benoyjose** [comment]
Point point = ele.getLocation();

// Get width and height of the element
int eleWidth = ele.getSize().getWidth();
int eleHeight = ele.getSize().getHeight();

// Crop the entire page screenshot to get only element screenshot
BufferedImage eleScreenshot= fullImg.getSubimage(point.getX(), point.getY(),
    eleWidth, eleHeight);
ImageIO.write(eleScreenshot, "png", screenshot);

This is how I was able to clip out selected element as png. My requirement is to get the entire image with the selected element highlighted.

**Comment by KazuCocoa** [comment]
ah, i see. Below is the result of image_comparsion like https://github.com/appium/appium/blob/cdfd8fabfc28c03f7be418945a0ae6b95092c504/docs/en/writing-running-appium/image-comparison.md#occurrences-lookup . This is opencv feature tho.
<img src="https://user-images.githubusercontent.com/5511591/58524774-4627bc00-8204-11e9-8ce5-50d9762475c6.png" width=200>

So far, we have no such feature.
Creating a feature request on appium repo is better as the 1st step, I think.
(Use case why it is great Appium has the feature also helpful for us.)

If you already have any idea about command/implementation, it is also helpful.

**Comment by benoyjose** [comment]
@KazuCocoa I have found a solution using Graphics2d to get the selected element highlighted.
This is the Wildcard I used to fetch all elements.
 'List<MobileElement> ListWC = driver.findElements(By.xpath("//*"));'

Iterated elements to give individual screenshots of selected element highlighted.

` File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
                BufferedImage fullImg = ImageIO.read(screenshot);

                Point point = element_node.getLocation();
                int eleWidth = element_node.getSize().getWidth();
                int eleHeight = element_node.getSize().getHeight();

                Graphics2D g2d = fullImg.createGraphics();
                g2d.setColor(Color.RED);
                g2d.setStroke(new BasicStroke(10));
                g2d.drawRect(point.getX(), point.getY(), eleWidth, eleHeight);

                ImageIO.write(fullImg, "png", screenshot);
                File screenshotLocation = new File("D:\\" + element_node.getId()+ ".png");
                FileUtils.copyFile(screenshot, screenshotLocation);`

![Y29tLmFmb2xsZXN0YWQubWF0ZXJpYWxkaWFsb2dzc2FtcGxlOmlkL2Jhc2ljX3RpdGxlZF9idXR0b25z](https://user-images.githubusercontent.com/12951158/58683516-51a8ed80-8392-11e9-844f-f7e63ce5ef4e.png)
![Y29tLmFmb2xsZXN0YWQubWF0ZXJpYWxkaWFsb2dzc2FtcGxlOmlkL2Jhc2ljX2h0bWxfY29udGVudA==](https://user-images.githubusercontent.com/12951158/58683518-51a8ed80-8392-11e9-9b3f-ff665a16862a.png)

Hope this will be helpful to others too,
