### ISSUE TITLE
if webview has more than one window，how can applum_lib switch window like java_client

### ISSUE THREAD

**Issue by catfishuang** [appium/ruby_lib#728]
## This is a
* [x] Freature Request

## Environment
* Appium version (or git revision): 1.7.1
* `ruby_lib` version: 9.7.5

## Actual behaviour and steps to reproduce

1、in WeChat app，set context to webview
2、there are two pages，but the default is not the one I want to test，does appium_lib has method to solve the problem ? in java_client , some methods like getwindowhandle.. can do it

**Comment by KazuCocoa** [comment]
@catfishuang 
What about http://www.rubydoc.info/gems/selenium-webdriver/0.0.28/Selenium/WebDriver/Driver#window_handle-instance_method and `switch_to.window`?

You can call webdriver side methods like `@driver.window_handles` or `$driver.driver. window_handles`(If you use global scope driver) and I think you can call `window_handles`...

`@driver.switch_to.window('new window handle')`

**Comment by catfishuang** [comment]
@KazuCocoa 
i tried to use Selenium WebDriver, how can it switch to webview？i  didn't find the method......
appium has command "set_context", i confused about the problem

**Comment by KazuCocoa** [comment]
Ah, understood. I'm not familiar with Java client...

Basically, you can find pure Appium client stuff from:
http://www.rubydoc.info/github/appium/ruby_lib_core

And you can find more helpful command from:
http://www.rubydoc.info/github/appium/ruby_lib

Basically, appium clients depends on Selenium webdriver. So, if you can't find any methods you 'd like to find in the above documentation, please check webdriver side.
(But for native application stuff, you don't need to check webdriver side.)

If you can get contexts via [available_contexts](http://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/Device#available_contexts-instance_method), you can set some of contexts with [set_context](http://www.rubydoc.info/github/appium/ruby_lib_core/Appium/Core/Device#set_context-instance_method).
@catfishuang

**Comment by catfishuang** [comment]
$driver.set_context("WEBVIEW_com.tencent.mm:tools")

windows = $driver.driver.window_handles

$driver.driver.switch_to.window(windows[1])

puts $driver.get_source

It works well , thanks a lot......

**Comment by KazuCocoa** [comment]
Ah...

1. set webview
2. get windows from the webview
3. set a particular window from the windows

...

Thanks for sharing your result!
