### ISSUE TITLE
add mobile: endpoints methods to support multiple apps

### ISSUE THREAD

**Issue by KazuCocoa** [appium/ruby_lib#729]
## This is a
* [ ] Bug report
* [ ] Question
* [x] Freature Request

## Summary

https://github.com/appium/appium-xcuitest-driver/pull/576/files

## Environment
* Appium version (or git revision):
* `ruby_lib` version:
* Mobile platform/version/device under test:

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by mykola-mokhnach** [comment]
Plus https://github.com/appium/appium-xcuitest-driver/pull/584
