### ISSUE TITLE
unable to launch arc

### ISSUE THREAD

**Issue by businessph** [appium/ruby_lib#734]
ph@Phuongs-MacBook-Pro ~/stprojects/st_mobile_regression (master) $ arc
/Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_console-2.8.0/lib/appium_console.rb:37:in `start': uninitialized constant #<Class:Appium::Console>::AwesomePrint (NameError)
        from /Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_console-2.8.0/lib/cli.rb:77:in `init'
        from /Users/ph/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /Users/ph/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/ph/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /Users/ph/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_console-2.8.0/lib/cli.rb:86:in `<top (required)>'
        from /Users/ph/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/ph/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from /Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_console-2.8.0/bin/arc:3:in `<top (required)>'
        from /Users/ph/.rvm/gems/ruby-2.4.1/bin/arc:23:in `load'
        from /Users/ph/.rvm/gems/ruby-2.4.1/bin/arc:23:in `<main>'
        from /Users/ph/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/ph/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

started android emulator
started appium server

any ideas.  thanks in advance.

**Comment by JaniJegoroff** [comment]
Could you try

`bundle`
`bundle exec arc`

**Comment by KazuCocoa** [comment]
Sorry, the error is my previous PR's mistake.
I forget to insert a line to require "awesomep_print" into the console file, `lib/appium_console.rb`.
I'll release 2.8.1 soon. https://github.com/appium/ruby_console/pull/89

---

And thanks to the guide!

**Comment by KazuCocoa** [comment]
Could you try again with `2.8.1`? @businessph

**Comment by businessph** [comment]
ph@Phuongs-MacBook-Pro ~/stprojects/st_mobile_regression (master) $ gem uninstall appium_console
Remove executables:
	arc

in addition to the gem? [Yn]  Y
Removing arc
Successfully uninstalled appium_console-2.8.0
ph@Phuongs-MacBook-Pro ~/stprojects/st_mobile_regression (master) $ gem install appium_console 2.8.1
Fetching: appium_console-2.8.1.gem (100%)
Successfully installed appium_console-2.8.1
Parsing documentation for appium_console-2.8.1
Installing ri documentation for appium_console-2.8.1
Done installing documentation for appium_console after 0 seconds
ERROR:  Could not find a valid gem '2.8.1' (>= 0) in any repository
1 gem installed
ph@Phuongs-MacBook-Pro ~/stprojects/st_mobile_regression (master) $ bundle
Using rake 12.3.0
Using concurrent-ruby 1.0.5
Using i18n 0.9.1
Using minitest 5.10.3
Using thread_safe 0.3.6
Using tzinfo 1.2.4
Using activesupport 5.1.4
Using rack 2.0.3
Using rack-test 0.7.0
Using unf_ext 0.0.7.4
Using unf 0.1.4
Using domain_name 0.5.20170404
Using http-cookie 1.0.3
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using netrc 0.11.0
Using rest-client 2.0.2
Using rspec-support 3.7.0
Using rspec-core 3.7.0
Using diff-lcs 1.3
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using airborne 0.2.13
Using awesome_print 1.8.0
Using json 2.1.0
Using mini_portile2 2.3.0
Using nokogiri 1.8.1
Using ffi 1.9.18
Using childprocess 0.8.0
Using rubyzip 1.2.1
Using selenium-webdriver 3.7.0
Using tomlrb 1.2.6
Using appium_lib 9.7.5
Using backports 3.10.3
Using browserstack-local 1.3.0
Using builder 3.2.3
Using bundler 1.16.0
Using chunky_png 1.3.8
Using coderay 1.1.2
Using cucumber-tag_expressions 1.1.0
Using gherkin 5.0.0
Using cucumber-core 3.1.0
Using cucumber-expressions 5.0.5
Using cucumber-wire 0.0.1
Using multi_json 1.12.2
Using multi_test 0.1.2
Using cucumber 3.1.0
Using httpclient 2.8.3
Using method_source 0.9.0
Using parallel 1.12.0
Using parallel_tests 2.19.0
Using pry 0.11.3
Using selenium-cucumber 3.1.5
Bundle complete! 11 Gemfile dependencies, 54 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
ph@Phuongs-MacBook-Pro ~/stprojects/st_mobile_regression (master) $ bundle exec arc
/Users/ph/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/rubygems_integration.rb:458:in `block in replace_bin_path': can't find executable arc for gem appium_console. appium_console is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /Users/ph/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/rubygems_integration.rb:478:in `block in replace_bin_path'
	from /Users/ph/.rvm/gems/ruby-2.4.1/bin/arc:23:in `<main>'
	from /Users/ph/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ph/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
ph@Phuongs-MacBook-Pro ~/stprojects/st_mobile_regression (master) $ arc
/Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.8.1/lib/appium_lib/appium.rb:58:in `load_settings': toml doesn't exist appium.txt (RuntimeError)
	from /Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_console-2.8.1/lib/appium_console.rb:20:in `block in setup'
	from /Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_console-2.8.1/lib/appium_console.rb:42:in `start'
	from /Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_console-2.8.1/lib/cli.rb:77:in `init'
	from /Users/ph/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/ph/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/ph/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/ph/.rvm/gems/ruby-2.4.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_console-2.8.1/lib/cli.rb:86:in `<top (required)>'
	from /Users/ph/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/ph/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/ph/.rvm/gems/ruby-2.4.1/gems/appium_console-2.8.1/bin/arc:3:in `<top (required)>'
	from /Users/ph/.rvm/gems/ruby-2.4.1/bin/arc:23:in `load'
	from /Users/ph/.rvm/gems/ruby-2.4.1/bin/arc:23:in `<main>'
	from /Users/ph/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ph/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
ph@Phuongs-MacBook-Pro ~/stprojects/st_mobile_regression (master) $

**Comment by businessph** [comment]
fix worked thank you very much.  happy holidays.  :)
