### ISSUE TITLE
click action not performed due to Softkeyboard enable(Hide the keyboard also its not working) but test is passed. 

### ISSUE THREAD

**Issue by PMNagabhushanam** [appium/ruby_lib#736]
## This is a
* [x] Bug report
* [x] Question
* [ ] Freature Request

## Environment
* Appium version (or git revision):
* `ruby_lib` version:
* Mobile platform/version/device under test:

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by PMNagabhushanam** [comment]
Anyone Solve my problem i unable to login in my account due to softkeyboard..

**Comment by KazuCocoa** [comment]
@PMNagabhushanam 
Could you attach the full appium and ruby client side's log?

**Comment by KazuCocoa** [comment]
Could you attach the log and re-open again if you're struggling with this yet.
