### ISSUE TITLE
Issues running the Cucumber Android test

### ISSUE THREAD

**Issue by marcaractac** [appium/ruby_lib#744]
## This is a
* [ ] Bug report
* [*] Question
* [ ] Freature Request

I am currently trying to get the cucumber tests in this repo working as a way to get familiar with Appium before starting to write my own tests. I have been able to run the iOS cucumber test just fine, however, I'm running into issues trying to run the one for Android.

Environment
Appium version (or git revision) that exhibits the issue: 9.7.5
Desktop OS/version used to run Appium: OSX Sierra 10.12.6
Node.js version (unless using Appium.app|exe): 9.3.0
Mobile platform/version under test: using exactly what is outlined in appium.txt
I'm also using the Gemfile included in the repo, just trying to get these tests working as is before I start to work on my own.
This is what I get when trying to run the test:

parse error on value "rspec/expectations" (STRING_LITERAL) (Tomlrb::ParseError)
/Users/test/.rvm/gems/ruby-2.3.1@global/gems/tomlrb-1.2.6/lib/tomlrb.rb:25:in rescue in parse' /Users/test/.rvm/gems/ruby-2.3.1@global/gems/tomlrb-1.2.6/lib/tomlrb.rb:22:inparse'
/Users/test/.rvm/gems/ruby-2.3.1@global/gems/tomlrb-1.2.6/lib/tomlrb.rb:42:in load_file' /Users/test/.rvm/gems/ruby-2.3.1/gems/appium_lib-9.7.5/lib/appium_lib/appium.rb:63:inload_settings'
/Users/test/workspace/sample-code/examples/ruby/cucumber_android/features/support/env.rb:17:in <top (required)>' /Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:inload'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in load_code_file' /Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:inload_file'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in block in load_files!' /Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:ineach'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in load_files!' /Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:inload_step_definitions'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in run!' /Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:inexecute!'
/Users/test/.rvm/gems/ruby-2.3.1/gems/cucumber-2.4.0/bin/cucumber:8:in <top (required)>' /Users/test/.rvm/gems/ruby-2.3.1/bin/cucumber:23:inload'
/Users/test/.rvm/gems/ruby-2.3.1/bin/cucumber:23:in <main>' /Users/test/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:ineval'
/Users/test/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `

**Comment by marcaractac** [comment]
I managed to solve the issue!

**Comment by gabriellira** [comment]
@marcaractac how did you solve that issue? I'm having the same problem running the sample app 'cucumber_android'

**Comment by KazuCocoa** [comment]
The error said `parse error` and I guess `appium.txt` has some issues.

Thus, I think you can fix it make sure `appium.txt` format or using `Hash` format like https://github.com/appium/ruby_lib_core/blob/master/test/test_helper.rb#L36 and apply the hash to the driver.

**Comment by marcaractac** [comment]
Yeah I had issues where the editor I was updating appium.txt in was changing the quotation marks to ” or ’ instead of " or '. It was an easy mistake to overlook, but it was the cause of the problems. All smooth sailing once I fixed that, although it made me feel like a complete idiot lol
