### ISSUE TITLE
Requiring appium_lib after minitest throws a TypeError: superclass mismatch exception

### ISSUE THREAD

**Issue by MRod15** [appium/ruby_lib#747]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
When requiring 'appium_lib' after 'minitest' has been required, an `TypeError: superclass mismatch` exception is thrown.

## Environment
* Appium version (or git revision): 9.83.3
* `ruby_lib` version: 2.3.4
* Mobile platform/version/device under test: n/a
* Minitest version: 5.11.1

## Actual behaviour and steps to reproduce
```
$ irb
2.3.4 :001 > require 'minitest'
 => true 
2.3.4 :002 > require 'appium_lib'
TypeError: superclass mismatch for class Test
        from /home/test/.rvm/gems/ruby-2.3.4@tests/gems/appium_lib-9.0.0/lib/appium_lib/driver.rb:47:in `<module:Minitest>'
        from /home/test/.rvm/gems/ruby-2.3.4@tests/gems/appium_lib-9.0.0/lib/appium_lib/driver.rb:43:in `<top (required)>'
        from /home/test/.rvm/gems/ruby-2.3.4@tests/gems/appium_lib-9.0.0/lib/appium_lib.rb:12:in `require_relative'
        from /home/test/.rvm/gems/ruby-2.3.4@tests/gems/appium_lib-9.0.0/lib/appium_lib.rb:12:in `<top (required)>'
        from /home/test/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /home/test/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /home/test/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):2
        from /home/test/.rvm/rubies/ruby-2.3.4/bin/irb:11:in `<main>'

```

## Expected behaviour
```
$ irb
2.3.4 :001 > require 'minitest'
 => true 
2.3.4 :002 > require 'appium_lib'
=> true
```
## Link to Appium/Ruby logs

https://gist.github.com/MRod15/3d4581a9e788e78706405974810b682b

**Comment by KazuCocoa** [comment]
It happens by minitest `5.11.0+`. I've added a condition flow.
https://github.com/appium/ruby_lib/pull/748

**Comment by KazuCocoa** [comment]
Could you try the latest master branch? @MRod15

**Comment by MRod15** [comment]
Sorry for the delay, sure, will try! 👍

**Comment by MRod15** [comment]
@KazuCocoa, it's ok, I've tested it with success! :)

**Comment by rockwig** [comment]
Not sure this is related, but I tried using 9.8.4 and I now get this error: `uninitialized constant Minitest::VERSION (NameError)` when trying to run a test. Everything works fine with 9.8.3.

**Comment by KazuCocoa** [comment]
That's right.
We should skip `minitest` stuff if it's not `required`.

**Comment by KazuCocoa** [comment]
I've released v9.8.5. Could you try the latest one?
thanks.

**Comment by drzajwo** [comment]
@KazuCocoa For me now v9.8.5 everything works fine. Also in irb require 'appium_lib' and 'minitest' both returns true.

**Comment by KazuCocoa** [comment]
Thanks so much!

**Comment by MRod15** [comment]
@KazuCocoa , it seems that Minitest reverted the Test inheritance in 5.11.2 back to Runnable, breaking the code yet again...

http://docs.seattlerb.org/minitest/History_rdoc.html#label-5.11.2+-2F+2018-01-25

Should I open another issue?
