### ISSUE TITLE
Unable to perform gestures using touch action class

### ISSUE THREAD

**Issue by sevarudakov** [appium/ruby_lib#755]
## Summary

I have a problem with dismissing popup alert. I can't click on "OK" button to dismiss it using locator because the locators not pointing the button correctly but a bit lefter so it actually doesn't click it.
Because of that I decided to tap that button using its coordinates with touch action class like this:

```     
 opts = {
        caps: {
          platformName: :android,
          platformVersion: '7.0',
          deviceName: 'testing',
          automationName: 'UiAutomator2',
          app: '/Users/user/App.apk'
        },
        appium_lib: {
          wait: 30
        }
      }

      @core = Appium::Core.for(self, opts)
      @driver = @core.start_driver
      Appium::Core::TouchAction.new(@driver).tap(x: 1175, y: 1475, duration: 1000).release.perform 
```

However, after using mentioned above code it seems like it doesn't perform tap action this way either and app actually crashes but I don't get any errors in terminal it just tries to execute the next step.
 
## Environment
* Appium version (or git revision): 1.2.7
* `ruby_lib` version: appium_lib 9.8.3
* Mobile platform/version/device under test:
Android Emulator 7. 0 

## Actual behaviour and steps to reproduce
App crashes after using touch action class

## Expected behaviour
Should be able to perform "tap" action

## Link to Appium/Ruby logs
https://gist.github.com/sevarudakov/38f48d0a1428aaa45fa6c538dae495d3

**Comment by KazuCocoa** [comment]
@sevarudakov 

The request from the client to the Appium server looks fine.

```
[debug] [MJSONWP] Responding to client with driver.implicitWait() result: null
[info] [HTTP] <-- POST /wd/hub/session/2af786ba-7e9a-40fe-b202-f71bd13f0e06/timeouts/implicit_wait 200 3 ms - 76 
[info] [HTTP] --> POST /wd/hub/session/2af786ba-7e9a-40fe-b202-f71bd13f0e06/touch/perform {"actions":[{"action":"tap","options":{"x":1175,"y":1475,"duration":1000,"count":1}},{"action":"release"}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":1175,"y":1475,"duration":1000,"count":1}},{"action":"release"}],"2af786ba-7e9a-40fe-b202-f71bd13f0e06"]
[debug] [JSONWP Proxy] Proxying [POST /appium/tap] to [POST http://localhost:8201/wd/hub/session/61ab00d4-a69c-4852-972f-7e75b8d2b780/appium/tap] with body: {"x":1175,"y":1475}[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"61ab00d4-a69c-4852-972f-7e75b8d2b780","status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[info] [HTTP] <-- POST /wd/hub/session/2af786ba-7e9a-40fe-b202-f71bd13f0e06/touch/perform 200 134 ms - 76 [info] [HTTP] --> POST /wd/hub/session/a3597a95-dd15-4581-90d3-4430f6e20d8b/elements {"using":"xpath","value":"//android.widget.EditText[@resource-id=\"login-email-input\"]"}
```

The action correctly call after displaying the alert?
The touch action just taps the point and have no assertions. The following code is examples to check if the target is displayed or not.

```ruby
// Check the target element if it exists or not before tap action.
@core.wait { make sure the popup is displayed }
Appium::Core::TouchAction.new(@driver).tap(x: 1175, y: 1475, duration: 1000).perform  # you don't need `release` when you use tap.
```

Or

```ruby
// Check the target element if it exists or not after tap action.
@core.wait {
  Appium::Core::TouchAction.new(@driver).tap(x: 1175, y: 1475, duration: 1000).perform
  @driver.find_element(:xpath, "//android.widget.EditText[@resource-id=\"login-email-input\").displayed?   
}
```

If your crash happened by any actions after the tap action, I prefer to check elements before tapping. Make sense the above for your code?

-----

BTW, I tried https://github.com/appium/ruby_lib_core 's test code, replaced `press` to `tap`, and the action works fine.

- Appium console
```
[HTTP] --> POST /wd/hub/session/84838e34-4e23-48ce-a3f8-44bff6e464c5/touch/perform {"actions":[{"action":"tap","options":{"x":0,"y":597,"count":1}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":0,"y":597,"count":1}}],"84838e34-4e23-48ce-a3f8-44bff6e464c5"]
[debug] [JSONWP Proxy] Proxying [POST /appium/tap] to [POST http://localhost:8200/wd/hub/session/9049f497-5496-406e-9855-035cd284aae2/appium/tap] with body: {"x":0,"y":597}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"9049f497-5496-406e-9855-035cd284aae2","status":0,"value":true}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/84838e34-4e23-48ce-a3f8-44bff6e464c5/touch/perform 200 174 ms - 14

```

- Ruby code
```ruby
[2] pry(#<AppiumLibCoreTest::Android::DeviceTest>)> a = @@driver.find_element(:accessibility_id, 'App')
[3] pry(#<AppiumLibCoreTest::Android::DeviceTest>)> a.rect
=> #<struct Selenium::WebDriver::Rectangle x=0, y=597, width=1080, height=126>
[4] pry(#<AppiumLibCoreTest::Android::DeviceTest>)> x = a.rect.x
=> 0
[5] pry(#<AppiumLibCoreTest::Android::DeviceTest>)> y = a.rect.y
=> 597
[6] pry(#<AppiumLibCoreTest::Android::DeviceTest>)> Appium::Core::TouchAction.new(@@driver).tap(x: x, y: y).perform
=> #<Appium::Core::TouchAction:0x007fe2f4468e38 @actions=[], @driver=#<Appium::Core::Base::Driver:0x..f857c856c9bda39de browser="unknown">>
```

**Comment by sevarudakov** [comment]
Hi @KazuCocoa,

So I checked if the element is present before taping on it and it seems like it's not or appium can't see it for some reason. I tried explicit wait also.... I am confused because I can actually see it's there. 
May be I should switch to alert first? I tried ```@driver.switch_to.alert``` but it says method is undefined.

Can you please suggest what else I can try to do about it?

**Comment by KazuCocoa** [comment]
- Try emulator 7.1, 8.0 or 8.1
- Try with Real Device
    - I experienced some devices don't work well
- What about using `uiautomator` method?
    - Appium can run uiautomator methods like https://github.com/appium/ruby_lib/blob/b7daaac9b2262c80ee679263a809bd98371b312b/lib/appium_lib/android/element/generic.rb#L33 .
     - If the element can find with uiautomator, you can manage it via uiautomator.

**Comment by KazuCocoa** [comment]
I've listed the way to touch action. If you have any update, please update and re-open again.
(I believe this is not client-side stuff, though.)
