### ISSUE TITLE
Custom url not being updated.

### ISSUE THREAD

**Issue by Bevilacqua** [appium/ruby_lib#757]
## This is a
* [X] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
When trying to initialize a new driver with a custom url I get no errors the custom url is just not set.

## Environment
* `ruby_lib` version: 9.9

## Actual behaviour and steps to reproduce
Custom url is not specified

```ruby
        caps = {
        publicKey: 'HIDDEN',
        deviceName: "iphone5s",
        params:     "HIDDEN}"
      }

      opts = {
        "custom_url": "https://[HIDDEN]@appium.appetize.io/wd/hub",
        caps: caps
      }
      driver = Appium::Driver.new(opts, true) # Changing to false does not change result.
```

```
 => "#<Appium::Driver:0x007fc81f901340 ...  @custom_url=false ...>" 
```

## Expected behaviour
The custom url should be updated in the driver object.

**Comment by KazuCocoa** [comment]
What about the below like https://github.com/appium/ruby_lib/blob/master/grid/appium.txt.ios.example ?

```
opts = {
  caps: caps,
  appium_lib: {
    server_url: "http://localhost:4444/wd/hub"
  }
}

```
