### ISSUE TITLE
Question about shared preference on iOS and Android

### ISSUE THREAD

**Issue by deyvisonbm** [appium/ruby_lib#784]
## This is a
* [ ] Bug report
* [x] Question
* [ ] Freature Request

## Summary
Hi everyone, 

My question about appium, is one problem that i don't know how to resolve, can i use shared preference to set a specific condition on app?  

## Environment
* Appium version): 1.8
* Mobile platform/version/device under test: iOS/Android

**Comment by KazuCocoa** [comment]
Do you mean https://developer.android.com/reference/android/content/SharedPreferences ?
I haven't used this, but perhaps you can set the shreadPreference in capability for Android like: https://github.com/appium/appium-android-driver/pull/252/files#diff-3bc05c26e97c0fa865a3cb47981a69d0R64 .

```
{ sharedPreferences: {
    name: 'com.appium.prefs',
    prefs: [{type: 'string', name: 'mystr', value:'appium rocks!'}]
}}
```

Could you try this?

@deyvisonbm

**Comment by KazuCocoa** [comment]
Except for the way, you have no way to inject it from outside the app.

**Comment by cmfsotelo** [comment]
> Except for the way, you have no way to inject it from outside the app.
> I tried
> 
> ```
> $ adb shell run-as io.appium.android.apis mkdir -p /data/data/io.appium.android.apis/shared_prefs # could
> $ adb push string.xml /data/data/io.appium.android.apis/shared_prefs # permission error
> ```
Probably coming late to the party, but you can accomplish this if you change your last command.
The problem is simply you, as an external user, not being able to copy things into the app folder, hence the permission error.
You can go around this by pushing the file, for instance, into the sdcard folder, and then, runing as the package user, you can copy from the sdcard folder into your app folder.
Example below:
```
$ adb shell run-as io.appium.android.apis mkdir -p /data/data/io.appium.android.apis/shared_prefs # could
$ adb push string.xml /sdcard/
$ adb shell run-as io.appium.android.apis mv /scard/strings.xml /data/data/io.appium.android.apis/shared_prefs/strings.xml
```
