### ISSUE TITLE
Appium lib 9.14.0 ->  uninitialized constant Appium::Ios::Device

### ISSUE THREAD

**Issue by wrathtodd** [appium/ruby_lib#785]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary

There is an error shown after I start the new driver "uninitialized constant Appium::Ios::Device"

## Environment
* Appium version (1.8.0 or 1.8.1):
* `ruby_lib` version: 9.14.0
* Mobile platform/version/device under test: iPhone 8 (iOS 11.3.1)

## Actual behaviour and steps to reproduce
I have the following caps:

```
    caps = {
        :deviceName => self.device.name,
        :udid => self.device.udid,
        :platformVersion => self.device.iOSVersion,
        :platformName => :ios,
        :bundleId => bundleID,
        :xcodeOrgId => self.xcodeOrgID,
        :xcodeSigningId => "iPhone Developer",
        :newCommandTimeout => 120,
        :noReset => true,
        :app => ENV['APP_PATH'],
        :clearSystemFiles => true,
        :wdaLocalPort => self.device.wdaPort,
        :automationName => "XCUITest",
        :preventWDAAttachments => true,
        :useJSONSource => true,
    }

    appium_lib = {
        export_session: false,
        wait: 0,
        wait_timeout: 0,
        wait_interval: 1,
        server_url: "http://127.0.0.1:#{self.device.appiumPort}/wd/hub"
    }

    driver = Appium::Driver.new({:caps => caps, :appium_lib => appium_lib}, true)
```

After creating a driver, this error is shown. Not reproducible with appium_lib 9.13.0
Would be thankful for any helpful input on this issue

## Expected behaviour

The driver starts :)

**Comment by KazuCocoa** [comment]
mmm, could you share the version of `appium_lib_core` in your Gemfile.lock?

I assume this is related with https://github.com/appium/ruby_lib_core/pull/89/files . So, the version will help me.

Anyway, I'll take a look today.
@wrathtodd

**Comment by wrathtodd** [comment]
Thanks for your reply, @KazuCocoa!

In my Gemfile.lock it is  appium_lib_core (~> 1.7.0)

**Comment by KazuCocoa** [comment]
I found the cause... It happens only ruby_lib. Not core. I'll fix and release soon.

**Comment by KazuCocoa** [comment]
Could you try https://rubygems.org/gems/appium_lib/versions/9.14.1 ? @wrathtodd
