### ISSUE TITLE
Link in README broken: Installing Appium on OS X

### ISSUE THREAD

**Issue by entwanderer** [appium/ruby_lib#790]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary

Link in README.md for installing appium on mac os x is broken (404)

## Environment
latest chrome

## Actual behaviour and steps to reproduce
* Open README at https://github.com/appium/ruby_lib and click the link "Installing Appium on OS X"
* 404 Error occurs

## Expected behaviour

Install doc is openened

**Comment by KazuCocoa** [comment]
thanks!
And if you can create a PR, it's also welcome :)
