### ISSUE TITLE
Cannot perform startLogsBroadcast

### ISSUE THREAD

**Issue by jbhandari** [appium/ruby_lib#793]
## This is a
* [ ] Bug report
* [x] Question
* [ ] Freature Request

## Summary

After launching appium driver I cannot perform `startLogsBroadcast`
## Environment
* Appium version (or git revision): 1.8.1
* `ruby_lib` version: 9.14.1
* Mobile platform/version/device under test: iOS and Android

Trying to start logs broadcast, unable to do so:

```
appium_driver.execute_script 'mobile:startLogsBroadcast'

Selenium::WebDriver::Error::UnknownCommandError: Unknown mobile command "startLogsBroadcast". Only scroll,swipe,pinch,doubleTap,twoFingerTap,touchAndHold,tap,dragFromToForDuration,selectPickerWheelValue,alert,setPasteboard,getPasteboard,source,installApp,isAppInstalled,removeApp,launchApp,terminateApp,queryAppState,activateApp,viewportScreenshot,startPerfRecord,stopPerfRecord commands are supported.
from UnknownCommandError: Unknown mobile command "startLogsBroadcast". Only scroll,swipe,pinch,doubleTap,twoFingerTap,touchAndHold,tap,dragFromToForDuration,selectPickerWheelValue,alert,setPasteboard,getPasteboard,source,installApp,isAppInstalled,removeApp,launchApp,terminateApp,queryAppState,activateApp,viewportScreenshot,startPerfRecord,stopPerfRecord commands are supported.

```

How do I actually start it??? Thank you in advance!

**Comment by KazuCocoa** [comment]
I couldn't see log related `mobile:` command in `UnknownCommandError: Unknown mobile command`. The list should show all of https://github.com/appium/appium/blob/c986e4a62718b00976b26acb39e07e55f0c204d5/docs/en/commands/mobile-command.md#description . Thus, the error is probably server related one.

Could you attach the server log?
And what about using `appium@beta`?

**Comment by jbhandari** [comment]
@KazuCocoa I am performing these again, but I am getting a different error/issue...thankfully it seems the `startLogsBroadcast` command is found, but now I cannot find the endpoint for the broadcast unless I am doing something wrong.

```
driver.execute_script 'mobile:startLogsBroadcast'
=> nil

driver.session_id
=> "e2db0def-9dc7-42a8-95b3-7556d9dcb373"
```

Lets say my appium server is running on `http://11.11.11.122` on port `4000`

The url I am typing into my browser to access the broadcast is

`http://11.11.11.122:4000/ws/session/e2db0def-9dc7-42a8-95b3-7556d9dcb373/appium/syslog`

And the I keep getting this error back:

`The URL '/ws/session/e2db0def-9dc7-42a8-95b3-7556d9dcb373/appium/syslog' did not map to a valid resource`

Is there something I am missing?

**Comment by KazuCocoa** [comment]
@jbhandari 
WebSocket is:

https://github.com/appium/ruby_lib/blob/b9679e1295a031933b124530b85b30f9f086d2f3/lib/appium_lib/ios/xcuitest/command.rb#L19-L23

Could you try to connect the above URL?

ah... https://github.com/appium/appium/blob/b74e23e925847923ef627a827c066710ddfa2e0f/docs/en/commands/mobile-command.md#L71 loses `device` between `appium` and `syslog`..

**Comment by jbhandari** [comment]
@KazuCocoa  followed the same steps above, I am trying to visit:

`ws://11.11.11.122:4000/ws/session/e2db0def-9dc7-42a8-95b3-7556d9dcb373/appium/device/syslog`

However I get `This site can’t be reached, the webpage at ws://11.11.11.122:4000/ws/session/e2db0def-9dc7-42a8-95b3-7556d9dcb373/appium/device/syslog  might be temporarily down or it may have moved permanently to a new web address.` . 

The error given is `ERR_DISALLOWED_URL_SCHEME`

I am assuming I cannot use a regular browser?

**Comment by KazuCocoa** [comment]
Yes, you can't see it via browser so far.
You need to access the URL via websocker clients like `start_logs_broadcast` I commented above.

The command writes socket stream into a file.
If you'd like to customise the behaviour, below file helps you.

https://github.com/appium/ruby_lib/blob/9a8356b84198c6c9afb4d1dcf9a9c4067424b4c8/lib/appium_lib/common/command/ws_logcat.rb#L4-L12

**Comment by jbhandari** [comment]
Thank you for the clarification!
