### ISSUE TITLE
warning: already initialized constant Selenium::WebDriver::PointerActions::DEFAULT_MOVE_DURATION

### ISSUE THREAD

**Issue by kdthomas2121** [appium/ruby_lib#800]
## This is a
* [X] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
Recieving the following two warnings running our tests
`/gems/ruby-2.4.1/gems/appium_lib_core-1.7.2/lib/appium_lib_core/common/base/bridge/w3c.rb:10: warning: already initialized constant Selenium::WebDriver::PointerActions::DEFAULT_MOVE_DURATION
/.rvm/gems/ruby-2.4.1/gems/selenium-webdriver-3.13.0/lib/selenium/webdriver/common/interactions/pointer_actions.rb:21: warning: previous definition of DEFAULT_MOVE_DURATION was here
`
## Environment
* Appium version (or git ): appium_lib_core 1.7.2 appium_lib 9.14.2

* `ruby_lib` version: 2.4.1
* Mobile platform/version/device under test: Any

## Actual behaviour and steps to reproduce
Receiving this warning running any tests
## Expected behaviour
No warning

**Comment by KazuCocoa** [comment]
Thanks!
but the change is intentional override to make a delay of touch action short in Appium.
