### ISSUE TITLE
Unable to find nested element

### ISSUE THREAD

**Issue by alexttransisland** [appium/ruby_lib#801]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Environment
* Appium version (or git revision): 1.8.1
* Ruby version: `2.4.4`
* `ruby_lib` version: not sure, but it was installed with `gem 'appium_lib', '~> 9.7.0'`
* Mobile platform/version/device under test: iOS 11.2 iPhone 6 emulator

## Actual behaviour and steps to reproduce
1. Call any child any element like
```
$driver.find_element(:accessibility_id, 'introScreen').find_element(:accessibility_id, 'skipLink')
```
2. See `cannot find element by :accessibility_id (ArgumentError)`, while try to search inside the parent element.

## Expected behaviour
Nested element with `:accessibility_id` should be correctly processed.

## Link to Appium/Ruby logs

Relevant Appium logs here
```
[HTTP] <-- POST /wd/hub/session/f2858e15-fba2-4c59-8b97-b01a3b26a8be/timeouts/implicit_wait 200 14 ms - 76
[HTTP] 
[HTTP] --> POST /wd/hub/session/f2858e15-fba2-4c59-8b97-b01a3b26a8be/elements
[HTTP] {"using":"accessibility id","value":"introScreen"}
[debug] [W3C] Calling AppiumDriver.findElements() with args: ["accessibility id","introScreen","f2858e15-fba2-4c59-8b97-b01a3b26a8be"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/3AFE438C-7556-41EE-B707-5DFD1E3FAFB4/elements] with body: {"using":"accessibility id","value":"introScreen"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"18000000-0000-0000-A784-000000000000"}],"sessionId":"3AFE438C-7556-41EE-B707-5DFD1E3FAFB4","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"18000000-0000-0000-A784-000000000000"}]
[HTTP] <-- POST /wd/hub/session/f2858e15-fba2-4c59-8b97-b01a3b26a8be/elements 200 106 ms - 124
[HTTP] 
[HTTP] --> GET /wd/hub/session/f2858e15-fba2-4c59-8b97-b01a3b26a8be/element/18000000-0000-0000-A784-000000000000/displayed
[HTTP] {}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/f2858e15-fba2-4c59-8b97-b01a3b26a8be/element/18000000-0000-0000-A784-000000000000/displayed] to [GET http://localhost:8100/session/3AFE438C-7556-41EE-B707-5DFD1E3FAFB4/element/18000000-0000-0000-A784-000000000000/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"3AFE438C-7556-41EE-B707-5DFD1E3FAFB4\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 3AFE438C-7556-41EE-B707-5DFD1E3FAFB4 with f2858e15-fba2-4c59-8b97-b01a3b26a8be
[HTTP] <-- GET /wd/hub/session/f2858e15-fba2-4c59-8b97-b01a3b26a8be/element/18000000-0000-0000-A784-000000000000/displayed 200 225 ms - 76
[HTTP] 
[HTTP] --> GET /wd/hub/session/f2858e15-fba2-4c59-8b97-b01a3b26a8be/screenshot
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getScreenshot() with args: ["f2858e15-fba2-4c59-8b97-b01a3b26a8be"]
```
Second element search even was not processed by appium.

Ruby logs:
```
[1] pry(#<IntroScreen>)> skip_link
D, [2018-07-12 15:45:35#34344] DEBUG -- : Looking Page for Element by [accessibility_id]:[skipLink]
ArgumentError: cannot find element by :accessibility_id
from /Users/whatever_here/.rvm/gems/ruby-2.4.4/gems/selenium-webdriver-3.6.0/lib/selenium/webdriver/common/search_context.rb:60:in `find_element'
```
Similar issue happens with selenium-webdriver `3.13.0` (but with different line).

## Any additional comments
It's working fine with `gem 'appium_lib', '~> 9.6.1'`, it's not working for any version after, even the latest one.
The reason why I need to do nested search, not direct is in `react-navigate` application process. It saves previous pages in the DoM, so I always need to search against latest displayed screen. (which could have been displayed several times in the past)

**Comment by KazuCocoa** [comment]
@alexttransisland
Ruby client and Appium don't support the way.
If you'd like to find the nested element, what about using class chain like `find_elements :class_chain, 'XCUIElementTypeWindow[2]/XCUIElementTypeAny[-2]'` or XPath?

- https://github.com/appium/ruby_lib_core/blob/0a5134c80939484301250331bc77b384bc01cf1c/lib/appium_lib_core/ios/xcuitest/search_context.rb#L6

Read https://github.com/facebook/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules for more details about the class chain.

**Comment by alexttransisland** [comment]
I know these could be used, I'm asking why it was decided they started to be depricated after `9.6.1`

**Comment by KazuCocoa** [comment]
ah, i see.
Ruby binding calls `find_element_by` in selenium-webdriver. So, the result depends on selenium-webdriver. https://github.com/appium/ruby_lib/blob/v9.6.1/lib/appium_lib/device/device.rb#L449

I haven't change any lines associated with `find_element` in 9.6.1.
https://github.com/appium/ruby_lib/blob/master/release_notes.md#v961-2017-08-27

Ruby library has refered below selenium-webdriver from `9.5.0`. 
`s.add_runtime_dependency 'selenium-webdriver', '~> 3.4', '>= 3.4.1'`

Which version of webdriver-element when it works?

**Comment by alexttransisland** [comment]
@KazuCocoa I think there is some mapping lost in between, like https://github.com/appium/ruby_lib/compare/v9.6.1...v9.7.0#diff-ece083f7d284e12027dc18a4bc42cef6L6

**Comment by KazuCocoa** [comment]
Sorry. I missed. Yeah.

**Comment by alexttransisland** [comment]
And this somehow stopped to work for nested elements https://github.com/appium/ruby_lib/compare/v9.6.1...v9.7.0#diff-1ec598d82d38b25d7f35f68114d104a6R7

Would you be able to investigate it?

**Comment by KazuCocoa** [comment]
Maybe, I figure out.

Before `9.6.1`, ruby_lib monkey patched mani places. In the search context as well.
https://github.com/appium/ruby_lib/blob/v9.6.1/lib/appium_lib/device/device.rb#L466

```
module Selenium
  module WebDriver
    class Element
      include SearchContext
```

`Element` class include the monkey patched `SearchContext` then.

But after 9.7.0, i reduced such monkey patch. So, included `SearchContext` became pure selenium-webdriver's one.
To fix this, maybe I must override https://github.com/appium/ruby_lib_core/blob/master/lib/appium_lib_core/patch.rb#L6 with `Appium::Core::Base::SearchContext` in the latest case.

**Comment by alexttransisland** [comment]
👏

**Comment by KazuCocoa** [comment]
I'm waiting for the CI.

You can try it out with below libraries in your gemfile.

- the latest `appium_lib`
- `appium_lib_core` with https://github.com/KazuCocoa/ruby_lib_core/tree/fix-search-context-for-appium

**Comment by alexttransisland** [comment]
@KazuCocoa yeah, it started to be working. Thanks for the fix!

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib_core/releases/tag/v1.8.1
Thanks for your report!
