### ISSUE TITLE
Change in documentation/method handling in Webview Context

### ISSUE THREAD

**Issue by brandondjango** [appium/ruby_lib#823]
## This is a
* [ ] Bug report
* [ ] Question
* [ x ] Feature Request

## Summary

To switch tabs in a Webview context, you have to interact with the Appium::Core::Base::Driver. 

However, in the documentation here for example: http://appium.io/docs/en/commands/web/window/get-handle/

It might appear to a layman you have to work with just the Appium::Driver, when this is not the case.

I would suggest changing the documentation to better explain this or handling some methods for the Appium::Core to be supported at the Appium::Driver level.

I spent an entire day trying to figure this out, I'm not sure if this makes me dumb or not.

![screen shot 2018-10-18 at 5 19 20 pm](https://user-images.githubusercontent.com/10518376/47184920-fdb53100-d2f9-11e8-80de-e9c0fc3fabd6.png)

Thanks.

## Any additional comments

Appium is great. I hope this is the correct forum to bring this up.

**Comment by KazuCocoa** [comment]
thanks,
Yes, so far, this library provides vanilla selenium-webdriver methods via `driver` attribute. The driver is https://github.com/appium/ruby_lib_core . This library wraps some of the methods for native application.
https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/driver.rb#L72

Let me improve this, thanks for your suggestion

**Comment by KazuCocoa** [comment]
I've added some selenium-webdriver wrapper in `Appium::Drive`r to make callable them directly via global `$driver` and `Appium::Driver` instance via Core.
https://github.com/appium/ruby_lib/pull/827

I'd like to make sure documentation as well in the future. thanks for the suggestion.
