### ISSUE TITLE
Undefined method `displaed?`

### ISSUE THREAD

**Issue by luizlohn** [appium/ruby_lib#824]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
When I run a test with:
$driver.find_elements(how, what).displayed?
Show the message:  undefined method `displayed?' for [#<Selenium::WebDriver::Element:0x323231bc id="2">]:Array
  Did you mean?  display (NoMethodError)

## Environment
* Appium version (or git revision): 1.7.1
* `ruby_lib` version:
appium_lib (9.15.1)
appium_lib_core (2.0.2)

* Mobile platform/version/device under test: Android

**Comment by KazuCocoa** [comment]
Yes. thanks! @JaniJegoroff
