### ISSUE TITLE
no need to set absolute path for windows uwp app (specified with app bundle id) in driver.rb::initialize()?

### ISSUE THREAD

**Issue by djwgit** [appium/ruby_lib#830]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary
should not set app's absolute path for a windows uwp app with a given bundle ID.

## Environment
* Appium version (or git revision): 1.9.1
* `ruby_lib` version: 9.15.1
* Mobile platform/version/device under test: windows10

## Actual behaviour and steps to reproduce
with this ruby sample for testing windows uwp app using winappdriver
https://github.com/Microsoft/WinAppDriver/blob/master/Samples/Ruby/features/step_definitions/setup_steps.rb
it fails with error message:
`App doesn't exist. C:/github/explorer-uwp-appium-test/Microsoft.WindowsCalculator_8wekyb3d8bbwe!App (RuntimeError)`

seems the problem is here
https://github.com/appium/ruby_lib/blob/12eb2f39fe8d022efe0fb4a666c8661f9270cc7d/lib/appium_lib/driver.rb#L178
it tries to set the absolute path to the windows uwp app bundle, given with a bundle ID
if comment out this line, appium driver starts and works well

## Expected behaviour
should not calculate absolute path for windows uwp app bundle

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
https://github.com/Microsoft/WinAppDriver

> Application identifier or executable full path

ah... Only windows case, the path must accept bundle id.

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib/blob/master/CHANGELOG.md#v9160
