### ISSUE TITLE
ruby lib doc has '\n\n' all over

### ISSUE THREAD

**Issue by waynema** [appium/ruby_lib#834]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Environment
* Appium version (or git revision):
* `ruby_lib` version:
* Mobile platform/version/device under test:

## Actual behaviour and steps to reproduce
https://github.com/appium/ruby_lib/blob/master/docs/ios_docs.md
https://github.com/appium/ruby_lib/blob/master/docs/android_docs.md
have \n\n all over the docs.

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
thanks! This will fix in next release with newer https://rubygems.org/gems/appium_thor/versions/1.1.3
