### ISSUE TITLE
[Feature Request] Fix verification in order to support latest available Appium server beta version

### ISSUE THREAD

**Issue by vitalyk** [appium/ruby_lib#836]
## This is a

* [ Feature Request]

## Summary
Given: there is a check https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/driver.rb#L334
And I'm running iOS test with the latest appium server beta `1.10.0-beta.6`
Then I'm getting the error ```XCUITest requires Appium version >= 1.6.0 (Appium::Core::Error::NotSupportedAppiumServer)```

Suggestion: by using a `Version` gem, it works for me: `(Gem::Version.new(@appium_server_status['build']['version']) < Gem::Version.new(REQUIRED_VERSION_XCUITEST))`

## Environment
* Appium server version (or git revision): 1.10.0-beta.6 https://www.npmjs.com/package/appium
* appium_lib version: 9.16.0
* `ruby_lib` version: 2.4.4
* Mobile platform/version/device under test: iOS 12.1

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
Thanks! good catch.
I change the logic to use Gem::Version and stop raising the error since we can see such version error in server side.

**Comment by KazuCocoa** [comment]
I've release the fix as 1.6.1. thanks!

**Comment by vitalyk** [comment]
@KazuCocoa Great! Thanks!
