### ISSUE TITLE
How can I remove multiple warnings

### ISSUE THREAD

**Issue by crisrol423** [appium/ruby_lib#840]
## This is a
* [ ] Bug report
* [x] Question
* [ ] Freature Request

## Summary
in my spec_helper. rb

opts = {
  caps: {
    platformName: :android,
    automationName: :uiautomator2,
    platformVersion: '8.0.0',
    deviceName: 'HUAWEI nova 2i',
    app: './builds/app-debug.apk'
  },
  appium_lib: {
    wait_timeout: 5
  }
}

RSpec.configure do |config|
  config.before(:suite) do
    Appium::Driver.new(opts, true)
  end
end

and on running rspec shows these warnings

/Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib.rb:2: warning: setting Encoding.default_external
/Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib.rb:3: warning: setting Encoding.default_internal
/Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/ios/xcuitest/bridge.rb:1: warning: loading in progress, circular require considered harmful - /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/ios/ios.rb
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in  `<main>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in  `eval'
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/rspec:23:in  `<main>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/rspec:23:in  `load'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/exe/rspec:4:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in  `invoke'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in  `run'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:86:in  `run'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:98:in  `setup'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in  `load_spec_files'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in  `each'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1560:in  `block in load_spec_files'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in  `load_file_handling_errors'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in  `load'
        from /Users/crol/workspaces/TRIBE-MobileTesting/android/spec/scenarios/instagram_insights_v1_spec.rb:3:in  `<top (required)>'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
        from /Users/crol/workspaces/TRIBE-MobileTesting/android/spec/spec_helper.rb:4:in  `<top (required)>'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:35:in  `require'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in  `rescue in require'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in  `require'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib.rb:10:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib.rb:10:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/appium.rb:22:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/appium.rb:22:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/ios/ios.rb:10:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/ios/ios.rb:10:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/ios/xcuitest.rb:5:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/ios/xcuitest.rb:5:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/ios/xcuitest/bridge.rb:1:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/ios/xcuitest/bridge.rb:1:in  `require_relative'
/Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/uiautomator2/bridge.rb:1: warning: loading in progress, circular require considered harmful - /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/android.rb
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in  `<main>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in  `eval'
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/rspec:23:in  `<main>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/rspec:23:in  `load'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/exe/rspec:4:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in  `invoke'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in  `run'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:86:in  `run'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:98:in  `setup'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in  `load_spec_files'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in  `each'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1560:in  `block in load_spec_files'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in  `load_file_handling_errors'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in  `load'
        from /Users/crol/workspaces/TRIBE-MobileTesting/android/spec/scenarios/instagram_insights_v1_spec.rb:3:in  `<top (required)>'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
        from /Users/crol/workspaces/TRIBE-MobileTesting/android/spec/spec_helper.rb:4:in  `<top (required)>'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:35:in  `require'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in  `rescue in require'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in  `require'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib.rb:10:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib.rb:10:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/appium.rb:25:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/appium.rb:25:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/android.rb:11:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/android.rb:11:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/uiautomator2.rb:3:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/uiautomator2.rb:3:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/uiautomator2/bridge.rb:1:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/uiautomator2/bridge.rb:1:in  `require_relative'
/Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/espresso/bridge.rb:1: warning: loading in progress, circular require considered harmful - /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/android.rb
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in  `<main>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in  `eval'
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/rspec:23:in  `<main>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/bin/rspec:23:in  `load'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/exe/rspec:4:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in  `invoke'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in  `run'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:86:in  `run'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:98:in  `setup'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in  `load_spec_files'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1558:in  `each'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1560:in  `block in load_spec_files'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in  `load_file_handling_errors'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:2034:in  `load'
        from /Users/crol/workspaces/TRIBE-MobileTesting/android/spec/scenarios/instagram_insights_v1_spec.rb:3:in  `<top (required)>'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
        from /Users/crol/workspaces/TRIBE-MobileTesting/android/spec/spec_helper.rb:4:in  `<top (required)>'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:35:in  `require'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in  `rescue in require'
        from /Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:130:in  `require'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib.rb:10:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib.rb:10:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/appium.rb:25:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/appium.rb:25:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/android.rb:14:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/android.rb:14:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/espresso.rb:1:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/espresso.rb:1:in  `require_relative'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/espresso/bridge.rb:1:in  `<top (required)>'
        from /Users/crol/.rvm/gems/ruby-2.4.1/gems/appium_lib-9.16.1/lib/appium_lib/android/espresso/bridge.rb:1:in  `require_relative'
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old hide_keyboard
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of hide_keyboard was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old take_element_screenshot
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of take_element_screenshot was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old save_viewport_screenshot
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of save_viewport_screenshot was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old lock
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of lock was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old device_locked?
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of device_locked? was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old unlock
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of unlock was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old hide_keyboard
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of hide_keyboard was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old is_keyboard_shown
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of is_keyboard_shown was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old ime_activate
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of ime_activate was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old ime_available_engines
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of ime_available_engines was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old ime_active_engine
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of ime_active_engine was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old ime_activated
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of ime_activated was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old ime_deactivate
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of ime_deactivate was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old get_settings
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of get_settings was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old update_settings
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of update_settings was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old within_context
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of within_context was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old switch_to_default_context
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of switch_to_default_context was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old current_context
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of current_context was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old available_contexts
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of available_contexts was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old set_context
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of set_context was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old set_immediate_value
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of set_immediate_value was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old replace_value
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of replace_value was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old push_file
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of push_file was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old pull_file
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of pull_file was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old pull_folder
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of pull_folder was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old keyevent
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of keyevent was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old press_keycode
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of press_keycode was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old long_press_keycode
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of long_press_keycode was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old match_images_features
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of match_images_features was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old find_image_occurrence
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of find_image_occurrence was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old get_images_similarity
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of get_images_similarity was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old compare_images
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of compare_images was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old launch_app
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of launch_app was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old close_app
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of close_app was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old reset
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of reset was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old app_strings
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of app_strings was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old background_app
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of background_app was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old install_app
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of install_app was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old remove_app
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of remove_app was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old app_installed?
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of app_installed? was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old activate_app
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of activate_app was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old terminate_app
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of terminate_app was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old app_state
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of app_state was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old stop_recording_screen
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of stop_recording_screen was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old stop_and_save_recording_screen
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of stop_and_save_recording_screen was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old shake
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of shake was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old device_time
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of device_time was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old touch_actions
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of touch_actions was here
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: method redefined; discarding old multi_touch
/Users/crol/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/forwardable.rb:220: warning: previous definition of multi_touch was here
## Environment
* Appium version (or git revision):
* `ruby_lib` version:
* Mobile platform/version/device under test:

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
One is adding `$VERBOSE = nil` to reduce such warning.
Another is https://github.com/appium/ruby_lib_core/pull/174 .

In your case, I think you load modules multiple times. Then, the warning happen. The PR can resuce such warning.

**Comment by KazuCocoa** [comment]
Let me test with ruby_lib and the latest core before releasing it

**Comment by KazuCocoa** [comment]
You can reduce warning messages adapting the latest ruby_lib_core even if you call modules multiple times
