### ISSUE TITLE
Sendkeys are not working with UiAutoator2 driver appium version 1.9.0 

### ISSUE THREAD

**Issue by JeevanandhaBharathi** [appium/ruby_lib#846]
## This is a
* [ ] Bug report
* [x] Question
* [ ] Freature Request

## Environment
* Appium version (or git revision):
* `ruby_lib` version:
* Mobile platform/version/device under test:

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
Could you attach appium logs? @JeevanandhaBharathi
