### ISSUE TITLE
Bundler::GemspecError: rubyzip gem corrupted

### ISSUE THREAD

**Issue by Balamuruganvsb** [appium/ruby_lib#847]
## Not able to get success response when do the "bundle install" in project folder. 

But, the Appium_lib and rubyzip gems are installed properly when directly installing. Also, I removed the cache files and tried it but the results are same.

* Appium version (or git revision): 1.10.1
* Mobile platform/version/device under test: Android 

XXXXXX $ bundle install
Fetching gem metadata from http://rubygems.org/............
Resolving dependencies...
Using rake 12.2.1
Using eventmachine 1.2.7
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using faye-websocket 0.10.7
Using ffi 1.10.0
Using childprocess 0.9.0
Fetching rubyzip 1.2.2
Bundler::GemspecError: Could not read gem at /Users/XXXX/vendor/bundle/ruby/2.3.0/cache/rubyzip-1.2.2.gem. It may be corrupted.
An error occurred while installing rubyzip (1.2.2), and Bundler cannot continue.
Make sure that `gem install rubyzip -v '1.2.2' --source 'http://rubygems.org/'` succeeds before bundling.

In Gemfile:
  appium_lib was resolved to 9.18.0, which depends on
    appium_lib_core was resolved to 2.3.4, which depends on
      selenium-webdriver was resolved to 3.141.0, which depends on
        rubyzip

**Comment by KazuCocoa** [comment]
What about `--path vendor/bundle` in another path?
Changing to newer Ruby version also helps in some times.

**Comment by Balamuruganvsb** [comment]
Thanks @KazuCocoa . The issue got fixed after removing the `vendor/bundle' path using below command.

   bundle install --system 

https://stackoverflow.com/questions/19961821/why-bundle-install-is-installing-gems-in-vendor-bundle

Now, I'm facing the 'LoadError' issue when running the feature file.

XXXX $ cucumber features/XYZ.feature   
cannot load such file -- childprocess (LoadError)
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver.rb:18:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.3.0/gems/selenium-webdriver-3.141.0/lib/selenium-webdriver.rb:18:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.3.0/gems/appium_lib-9.18.0/lib/appium_lib/appium.rb:2:in `<top (required)>'
/Library/Ruby/Gems/2.3.0/gems/appium_lib-9.18.0/lib/appium_lib.rb:10:in `require_relative'
/Library/Ruby/Gems/2.3.0/gems/appium_lib-9.18.0/lib/appium_lib.rb:10:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/Users/bala/Documents/TA_Creditone_Android/features/support/env.rb:8:in `<top (required)>'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:107:in `load'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:107:in `load_code_file'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:144:in `load_file'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:85:in `block in load_files!'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:84:in `each'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:84:in `load_files!'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:272:in `load_step_definitions'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:68:in `run!'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/lib/cucumber/cli/main.rb:34:in `execute!'
/Library/Ruby/Gems/2.3.0/gems/cucumber-3.1.2/bin/cucumber:9:in `<top (required)>'
/usr/local/bin/cucumber:22:in `load'
/usr/local/bin/cucumber:22:in `<main>'


I checked the local gems files using command "gem list --local". 'childprocess' gem file is there in the list.

**Comment by JaniJegoroff** [comment]
@Balamuruganvsb Always run commands inside the bundle (not saying this will solve your problem but it's worth to try out)
```
$ bundle exec cucumber features/XYZ.feature
```

**Comment by Balamuruganvsb** [comment]
Thanks @JaniJegoroff. But, the command also gives the same error.

**Comment by KazuCocoa** [comment]
mmm...

Jani's solution should work if you install gems via `bundle install` (no --system)..
What about all of cucumber related dependencies once and install it again?

Close this issue, since this is not this library's issue. (it's fine to continue this thread though.)

**Comment by Balamuruganvsb** [comment]
@KazuCocoa @JaniJegoroff Gems are installed properly. Please see the logs.

XXXX $ sudo gem install bundler
Password:
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Done installing documentation for bundler after 6 seconds
1 gem installed
XXXX $ sudo bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Using rake 12.2.1
Using eventmachine 1.2.7
Using websocket-extensions 0.1.3
Using websocket-driver 0.7.0
Using faye-websocket 0.10.7
Using ffi 1.10.0
Using childprocess 0.9.0
Using rubyzip 1.2.2
Using selenium-webdriver 3.141.0
Using appium_lib_core 2.3.4
Using mini_portile2 2.4.0
Using nokogiri 1.10.1
Using tomlrb 1.2.8
Using appium_lib 9.18.0
Using builder 3.2.3
Using bundler 2.0.1
Using gherkin 4.1.3
Using cucumber-core 1.5.0
Using cucumber-wire 0.0.1
Using diff-lcs 1.3
Using multi_json 1.13.1
Using multi_test 0.1.2
Using cucumber 2.4.0
Using json 2.1.0
Using parallel 1.12.1
Using report_builder 1.8
Using rspec-support 3.8.0
Using rspec-expectations 3.8.2
Bundle complete! 6 Gemfile dependencies, 28 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

(Tried without sudo for bundle install )


Cucumber gems details:
===================

XXXX $ bundle info cucumber     
  * cucumber (2.4.0)
        Summary: cucumber-2.4.0
        Homepage: http://cukes.info
        Path: /Library/Ruby/Gems/2.3.0/gems/cucumber-2.4.0
XXXX $ bundle info cucumber-core
  * cucumber-core (1.5.0)
        Summary: cucumber-core-1.5.0
        Homepage: http://cukes.info
        Path: /Library/Ruby/Gems/2.3.0/gems/cucumber-core-1.5.0
