### ISSUE TITLE
text and text_exact methods don’t take into account letters in string - uppercase or lowercase or capitalized

### ISSUE THREAD

**Issue by vitalyk** [appium/ruby_lib#852]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Environment
* Appium version (or git revision): 1.11.0
* `ruby_lib` version: 10.0.0
* Mobile platform/version/device under test: iOS/12.1/iPhone 8 simulator

## Actual behaviour and steps to reproduce
Given such examples all are now equivalents:
text('White wall') == text('WHITE Wall')  == text('White Wall') == text('WHITE wall')
same issue with the text_exact method
## Expected behaviour
text method should locate text by partial match but taking into account text registry 

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
thanks.

Considering compatibility for the previous implementation,

- the `_exact` one should be case sensitive (will update)
https://github.com/appium/ruby_lib/blob/8b42a9726eae67f52d79820e27ff3a0169d7a0f5/lib/appium_lib/ios/common/helper.rb#L327
- the no-exact one should be case insensitive
https://github.com/appium/ruby_lib/blob/8b42a9726eae67f52d79820e27ff3a0169d7a0f5/lib/appium_lib/ios/common/helper.rb#L288
