### ISSUE TITLE
/session/:sessionId/appium/settings command

### ISSUE THREAD

**Issue by 22rtz** [appium/ruby_lib#858]
## This is a
* [ ] Bug report
* [X ] Question
* [ ] Freature Request

What is the ruby commad which implements the following api? 
**POST /session/:sessionId/appium/settings**

Referece
https://appium.io/docs/en/advanced-concepts/settings/

thank you in advance

**Comment by KazuCocoa** [comment]
Do you mean https://github.com/appium/ruby_lib/blob/8e7abeee3b0bc46b8d28b4352bed39819d68cbaf/android_tests/lib/android/specs/driver.rb#L231-L238 ?

**Comment by KazuCocoa** [comment]
http://appium.io/docs/en/commands/session/settings/update-settings/
http://appium.io/docs/en/commands/session/settings/get-settings/
