### ISSUE TITLE
How to pull a file or folder from a physical iOS device

### ISSUE THREAD

**Issue by jbhandari** [appium/ruby_lib#862]
## This is a
* [ ] Bug report
* [x] Question
* [ ] Freature Request

## Summary

Trying to pull a file and/or folder on a real iOS device. I have iFuse working under the hood. I just don't understand for a given `bundleId` how do you pull that data, or where to get the path to the data.

Is there a certain folder we can only access in iOS because of security features in iOS etc.

In short more info is needed on how to locate the path to data on an iOS phone! Any help is much appreciated!

## Environment
* Appium version (or git revision): 1.13
* Mobile platform/version/device under test: iOS 12.2

## Actual behaviour and steps to reproduce

- create a session
- try to use `@driver.pull_file(<path_to_file>)` or `@driver.pull_file(<path_to_file>)`

**Comment by KazuCocoa** [comment]
How about https://www.rubydoc.info/github/appium/ruby_lib_core/master/Appium/Core/Base/Driver#pull_file-instance_method , https://github.com/appium/appium/issues/12283 ?

```
decoded_file = @driver.pull_file '@com.appium.example/Documents/file.txt'
File.open('proper_filename', 'wb') { |f| f<< decoded_file }
```

**Comment by KazuCocoa** [comment]
I checked ifuse in https://github.com/appium/appium/issues/12283#issuecomment-497384996
Then, I noticed current logic can work for the app which has `UIFileSharingEnabled` flag in the plist

**Comment by KazuCocoa** [comment]
Close this issue.
Please watch https://github.com/appium/appium/issues/12283 and relevant issues @jbhandari 
(I'm working to add a feature for real device file movements and add the doc into appium repo)
