### ISSUE TITLE
'page' command is broken on iOS?

### ISSUE THREAD

**Issue by waynema** [appium/ruby_lib#865]
## This is a
* [ x] Bug report

## Summary
the page command to list the useful elements seems broken on the iOS platform.

## Environment
* Appium version (or git revision): 1.14.2
* `ruby_lib` version: 10.4.0
* Mobile platform/version/device under test: iOS 12.4 Simulator / Xcode 10.3

## Actual behaviour and steps to reproduce
When I set a debug point on iOS app,  I ususally can use the "page" command on the pry command line to list the elements on the page.  However, it is only returning nil now.   The "source "command is still working though.  Also the same "page" command works on Android for me.

## Expected behaviour
page command should work on iOS

**Comment by KazuCocoa** [comment]
Could you share your output of source command? (If it is difficult to share in a public place, you can also send it to an email in my github profile.)
I assume some strings in your source from Appium server break XML parser.

**Comment by KazuCocoa** [comment]
Published https://rubygems.org/gems/appium_lib/versions/10.4.1
