### ISSUE TITLE
Selenium [DEPRECATION] Selenium::WebDriver::Error::TimeOutError is deprecated. Use Selenium::WebDriver::Error::TimeoutError (ensure the driver supports W3C WebDriver specification) instead.

### ISSUE THREAD

**Issue by hardik-plume** [appium/ruby_lib#869]
## This is a
* [/] Bug report
* [ ] Question
* [ ] Freature Request

## Environment
* Appium version (or git revision): 1.15.1
* `ruby_lib` version: 10.5.0
* Mobile platform/version/device under test: iPhone 11 simulator

## Actual behaviour and steps to reproduce
using exists method throws Selenium [DEPRECATION] Selenium::WebDriver::Error::TimeOutError is deprecated. Use Selenium::WebDriver::Error::TimeoutError (ensure the driver supports W3C WebDriver specification) instead.

## Expected behaviour
No deprecation warning shown
## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
It is expected for now. selenium-webdriver ruby gem raises the message.

As backwards compatibility, appium ruby gem also has the `TimeOutError` error yet to support lower selenium-webdriver version. I'm planning to remove it in switching it to selenium 4 base.
(Or I can remove the message with stopping to support lower selenium-webdriver version.)

**Comment by KazuCocoa** [comment]
https://github.com/appium/ruby_lib_core/issues/175 (Selenium 4 update issue)

**Comment by hardik-plume** [comment]
i do not plan to switch to selenium4 @KazuCocoa

**Comment by KazuCocoa** [comment]
You can specify the lower selenium-webdriver version to prevent the message.
Maybe 3.14 has no it.

**Comment by kayner** [comment]
Is there a fix for this problem other than `Selenium::WebDriver.logger.level = :error` or changing selenium-webdriver version?

**Comment by KazuCocoa** [comment]
No, so far.

Bump minimal selenium-webdriver version and remove https://github.com/appium/ruby_lib_core/blob/fc7149cbaa199c5bd460d7af49efa2ef09b04243/lib/appium_lib_core/common/base/search_context.rb#L138-L139 is another way.

**Comment by KazuCocoa** [comment]
I checked again. Probably #267 prevents the timeout error warning without updating selenium-webdriver dependencies. (I tested a bit on my local)
Could you try it when you have a change?

**Comment by KazuCocoa** [comment]
I've pushed appium/ruby_lib_core#267 as appium_lib_core (3.10.0)
