### ISSUE TITLE
Appium behaving differently than the Appium inspector while trying to retrieve the value of an element

### ISSUE THREAD

**Issue by sai-poluri** [appium/ruby_lib#870]
## The value of the element displayed as ‘nil’ though it gets displayed in the inspector
 Bug report
 Question

 **Summary**
Appium 15.1: On iOS and Ruby_lib latest, The value of the element is returned as ‘nil’ though the value gets displayed in the Appium inspector and the other elements around that element return values. Wondering what has changed for that particular element.

**Works fine on older versions of Appium v1.9.0 which works with ruby lib**.

I have tried upgrading to Appium beta version, but it didn’t help. Looking forward for suggestions

**Desired Caps used:**
      caps["platformName"]= "iOS"
      caps["platformVersion"]= "11.4"
      caps["app"]= "/Users/display/Desktop/QA-Dashboard/app/assets/images/app.ipa"
      caps["automationName"]= "XCUITest"
      caps["deviceName"]= deviceName
      caps["udid"]= udid
      caps["wdaLocalPort"]=wdaLocalPort
      appium_lib["server_url"]="http://127.0.0.1:#{port}/wd/hub"
      caps["clearSystemFiles"]= false
      caps["noReset"]= ENV['NOAPPINSTALL']
      caps["xcodeOrgId"]= "XXXXX"
      caps["xcodeSigningId"]= "sai_poluri@xxxxx.com"
      #caps["autoAcceptAlerts"]= true
      caps["newCommandTimeout"]= 1500
      caps["agentPath"]= 
      caps["bootstrapPath"]

 Environment
* Appium version (or git revision): 15.1
* `ruby_lib` version: 2.6.0
* Mobile platform/version/device under test: iOS

## Actual Behavior and steps to reproduce
Appium behaving differently than as that of the elements shown in the inspector, the value of the element returned is nil instead of the value displayed in the appium inspector.

## Expected behavior
The appium should be able to return the value of that element

Link to Appium/Ruby logs

https://gist.github.com/sai-poluri/03a3afafc94a23ddf10e4a2651b79b2a

Any additional comments
I have tried installing Appium beta version, but didn't help.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/13288

**Comment by KazuCocoa** [comment]
The issue looks Appium environment than Ruby client.
As the above link, we got feedback Xcode 11 environment did not work well against iOS 12 (and lower) environment.
Was your environment Xcode 10?

**Comment by sai-poluri** [comment]
Works after the Xcode 10 downgrade. Thank you.

**Comment by KazuCocoa** [comment]
glad to hear it
