### ISSUE TITLE
Mobile app login issue in appium-ruby-cucumber combination

### ISSUE THREAD

**Issue by Balamuruganvsb** [appium/ruby_lib#877]
Scenario: Verify that user can log in to 'XYZ' application with valid credentials
    Then  I enter "xyz" in identifier "Username"
    Then I enter "xyz" in identifier "Password"
     Then I tap on identifier "sign_in_btn"
    Then I assert for element "home page"  

The problem is the line that has "sign_in_btn" button. When running the feature file, the username and password are entered properly and clicked the sign-in button and moved to the home page. But, the error comes as element ("sign_in_btn") not found.  I'm not sure whether "sign in" is clicked by default keyboard or from my code. But, if I remove the third line(sign_in_btn), I can't move forward after the second line(Password).

My question is if I'm able to move to the home page means why I'm getting error in "Sign in".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both
* Importanat gem versions: 
                cucumber 2.4.0
                appium_lib 9.14.3
                appium_lib_core 1.8.3
                rake 12.2.1

**Comment by KazuCocoa** [comment]
Could you share the appium log as GIST?

> whether "sign in" is clicked by default keyboard

Do you mean if appium ruby client has a default behaviour to click the keyword `sign in`?
If so, no.it depends on your feature file, I think.

**Comment by Balamuruganvsb** [comment]
@KazuCocoa 
[appium-server-logs.txt](https://github.com/appium/ruby_lib/files/4356151/appium-server-logs.txt)

_Do you mean if appium ruby client has a default behaviour to click the keyword sign in?
If so, no.it depends on your feature file, I think._

> I think, there is no default behavior for keyboard sign in. Because, If I skip the "sign in" step in my code, I couldn't able to move forward after the second line(Password).

**Comment by KazuCocoa** [comment]
You sent `Sign In` instead of `sign_in_btn`

```
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/67966f4c-99d2-4630-b38e-1f1aa734b48a/element[39m
[info] [35m[HTTP][39m [90m{"using":"xpath","value":"//*[@text='Sign In']"}[39m
[debug] [35m[W3C (67966f4c)][39m Calling AppiumDriver.findElement() with args: ["xpath","//*[@text='Sign In']","67966f4c-99d2-4630-b38e-1f1aa734b48a"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [35m[BaseDriver][39m Waiting up to 20000 ms for condition
[debug] [35m[WD Proxy][39m Matched '/element' to command name 'findElement'
[debug] [35m[WD Proxy][39m Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/cfce6f1d-2c39-45d7-ac21-7cfa3332dc4e/element] with body: {"strategy":"xpath","selector":"//*[@text='Sign In']","context":"","multiple":false}
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"cfce6f1d-2c39-45d7-ac21-7cfa3332dc4e","value":{"ELEMENT":"654913ea-52f6-44cd-abc4-160dd638e0ef","element-6066-11e4-a52e-4f735466cecf":"654913ea-52f6-44cd-abc4-160dd638e0ef"}}
[debug] [35m[W3C (67966f4c)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"654913ea-52f6-44cd-abc4-160dd638e0ef","ELEMENT":"654913ea-52f6-44cd-abc4-160dd638e0ef"}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/67966f4c-99d2-4630-b38e-1f1aa734b48a/element [39m[32m200[39m [90m123 ms - 137[39m
```

Appium ruby client does not have hardcoded `Sign In` keyword, so maybe your test code or dependencies have it.

**Comment by Balamuruganvsb** [comment]
@KazuCocoa  I tried both XPath(using text) and accessibility id to tap on sign in button. But, both are giving the same results. Here are the logs for "sign_in_btn". 
[appium-server-logs.txt](https://github.com/appium/ruby_lib/files/4356358/appium-server-logs.txt)

_Appium ruby client does not have hardcoded Sign In keyword, so maybe your test code or dependencies have it._

I haven't added any unwanted test code to sign in the application. Can you please let us know what type of dependencies(gem files) to create this issue.

**Comment by KazuCocoa** [comment]
Can you share your Ruby code which calls appium_lib methods?
I can take a look if this library affects it.

_dependencies_ meant your entire environment since I don't know your Ruby code and the dependencies

**Comment by Balamuruganvsb** [comment]
@KazuCocoa 

[Code.docx](https://github.com/appium/ruby_lib/files/4358038/Code.docx)

**Comment by KazuCocoa** [comment]
I thought you addressed `sign_in_btn` converted to `Sign In` unexpectedly, but do you mean you cannot find the element?? (Not an issue in this library)


I could see `sign_in_btn` in your attached log.

```
[debug] [35m[BaseDriver][39m Set implicit wait to 20000ms
[debug] [35m[W3C (272cb158)][39m Responding to client with driver.timeouts() result: null
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/272cb158-8f2c-41aa-80f2-2637fa977b96/timeouts [39m[32m200[39m [90m2 ms - 14[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/272cb158-8f2c-41aa-80f2-2637fa977b96/element[39m
[info] [35m[HTTP][39m [90m{"using":"id","value":"sign_in_btn"}[39m
[debug] [35m[W3C (272cb158)][39m Calling AppiumDriver.findElement() with args: ["id","sign_in_btn","272cb158-8f2c-41aa-80f2-2637fa977b96"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [35m[BaseDriver][39m Waiting up to 20000 ms for condition
```

The id is resource id. You should specify the resource id correctly.
Did you check the page source?

**Comment by Balamuruganvsb** [comment]
Yes. The resource id "sign_in_btn" is correct. The element ("sign_in_btn") is clicked properly and navigated to the next page while running the code. But, the error comes in the "sign_in_btn" line.

**Comment by KazuCocoa** [comment]
Sorry, I'm confusing. Do you mean you should catch the error in below's _Then_ section, but Ruby lib does not raise an issue there?

If `steps` file is expected, no issue for Ruby lib. The question is more Cucumber's exception handling rather than this library. I'd recommend you to ask it in https://discuss.appium.io/ than this repository.

```
When(/^I tap on identifier "([^"]*)"$/) do |arg|
  instance = MobilegesturesinAndroid::Mobilegestures.new
  instance.touch_with_id(arg)
end
Then(/^I assert for element "([^"]*)"$/) do |arg|
  instance = MobilegesturesinAndroid::Mobilegestures.new
  instance.assert_with_id(arg)
end
```

bw, `Then I tap on identifier "sign_in_btn"` should be `When`?

**Comment by Balamuruganvsb** [comment]
my intention is not to catch the error in line number 4(home page). Even the line number has a correct accessibility id and should be passed.

I want to get to know why the error comes in the "sign_in_btn" line when it's actually passed.

_Then I tap on identifier "sign_in_btn" should be When?_

I'm sure, It won't create any issue.

**Comment by KazuCocoa** [comment]
How about adding `raise` like below and observe if the error happens correctly?
It seems how Cucumber handles raised error rather than this library. Then, Cucumber community is more proper than here.

```ruby
When(/^I tap on identifier "([^"]*)"$/) do |arg|
  instance = MobilegesturesinAndroid::Mobilegestures.new
  instance.touch_with_id(arg)
end
Then(/^I assert for element "([^"]*)"$/) do |arg|
  raise RuntimeError
  # instance = MobilegesturesinAndroid::Mobilegestures.new
  # instance.assert_with_id(arg)
end
```

https://cucumber.io/docs/cucumber/checking-assertions/?sbsearch=assert#ruby
btw, you also can add `expect` like below to declare the expectation in rspec.

```ruby
Then(/^I assert for element "([^"]*)"$/) do |arg|
  instance = MobilegesturesinAndroid::Mobilegestures.new
  expect(instance.assert_with_id(arg)).to be true
end
```

Closes this issue for now since this issue may be out of this library.
(Can keep discussing here)
