### ISSUE TITLE
Appium is not compatible with Pry 0.13.0

### ISSUE THREAD

**Issue by v-kumar** [appium/ruby_lib#878]
## This is a
* [/] Bug report
* [ ] Question
* [ ] Freature Request

## Environment
* Appium version (or git revision):
* `ruby_lib` version:
* Mobile platform/version/device under test:
appium_lib-10.5.0

## Actual behaviour and steps to reproduce
Pry's latest version has removed the constant `HOME_RC_FILE`.
```
NameError: uninitialized constant Pry::HOME_RC_FILE
/usr/local/bundle/ruby/2.4.0/gems/appium_lib-10.5.0/lib/appium_lib/driver.rb:856:in `<top (required)>'
/usr/local/bundle/ruby/2.4.0/gems/appium_lib-10.5.0/lib/appium_lib/appium.rb:22:in `require_relative'
/usr/local/bundle/ruby/2.4.0/gems/appium_lib-10.5.0/lib/appium_lib/appium.rb:22:in `<top (required)>'
/usr/local/bundle/ruby/2.4.0/gems/appium_lib-10.5.0/lib/appium_lib.rb:24:in `require_relative'
/usr/local/bundle/ruby/2.4.0/gems/appium_lib-10.5.0/lib/appium_lib.rb:24:in `<top (required)>'
/usr/local/bundle/ruby/2.4.0/gems/appium_capybara-1.10.0/lib/appium_capybara.rb:1:in `<top (required)>'
```

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by KazuCocoa** [comment]
Removed it as 10.6.0
Thanks for the report!

**Comment by v-kumar** [comment]
Thanks for the quick resolution.
