### ISSUE TITLE
1.17.1 iOS: session fails to connect to appium

### ISSUE THREAD

**Issue by danielMayberg** [appium/ruby_lib#883]
## The problem
when running automations on iOS simulator I get
RuntimeError: ERROR: Unable to connect to Appium. Is the server running on http://127.0.0.1:4723/wd/hub?

happens on Appium::Driver.new(opts, true).start_driver
this occurs before appium creates a log

## Environment
* Appium 1.17.1
* MacOS catalina 10.15.5
* iphone 8 os13.5 simulator
* Ruby

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Do you have any ideas on how to debug server startup from a ruby script?

**Comment by KazuCocoa** [comment]
Ruby binding does not provide server setup.
Users should launch an Appium server outside Appium Ruby binding.

@danielMayberg How to start an Appium server in your code?

**Comment by danielMayberg** [comment]
@KazuCocoa I start it like this:

`export PATH=\"$PATH:\"/usr/local/bin/ && /usr/local/bin/appium #{should_reset} " +
          "--log #{TEMP_FOLDER_PATH}#{ENV_PATH_SEPARATOR}final_report" + "_#{device_tag}_#{BROWSER}_0#{ENV_PATH_SEPARATOR}appium_log.txt"`

**Comment by KazuCocoa** [comment]
Okay, then, can you get a response by `curl -X GET http://127.0.0.1:4723/wd/hub/status`?
If the Appium server worked, you can get the response like `{"value":{"build":{"version":"1.18.0-beta.1","git-sha":"3aa3f6a271b796f3f8557094769b5f75e089a59d","built":"2020-07-18 22:56:57 +0900"}},"sessionId":null,"status":0}`

If it worked, you can set the Ruby lib's log level to debug as `Appium::Logger.level = :debug`.

**Comment by danielMayberg** [comment]
@KazuCocoa on the failed runs I get this:
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to 127.0.0.1 port 4723: Connection refused`

**Comment by KazuCocoa** [comment]
Hm... btw, did you wait for the Appium server's wake up after `spawn`?

**Comment by danielMayberg** [comment]
@KazuCocoa How long should the wait be?

**Comment by KazuCocoa** [comment]
It depends on your system launching Appium server.

The easiest way is waiting for the port will be used by someone (This case is Appium server).
e.g. https://stackoverflow.com/questions/517219/ruby-see-if-a-port-is-open

**Comment by danielMayberg** [comment]
@KazuCocoa  I added this code:
`begin
  port_open = Socket.tcp("127.0.0.1", 4723, connect_timeout: 20){ true }
  rescue Errno::ECONNREFUSED
    return false
  end
  warn "port status is ...#{port_open}"`

it's still flaky, sometimes I get that port_open is true and still fail.

test log:
`Simulator/Device started
port status is ...true
Tag: @@full
INFO: Starting Scenario: iOS - Verify paywall from settings
Tags: @@native_ios_paywall, @@native_ipad, @@native_iphone

RuntimeError: ERROR: Unable to connect to Appium. Is the server running on http://127.0.0.1:4723/wd/hub?
`

**Comment by KazuCocoa** [comment]
Your code seems it checks if the port is open. The port is open means Appium server still does not listen to it.

e.g.
```ruby
def launch?
  while true
    begin
      s = TCPSocket.new('127.0.0.1', 4723)
      s.close
      return true
    rescue Errno::ECONNREFUSED, Errno::EHOSTUNREACH
      sleep 0.5
    end
  end
end
```

----

Close this issue for now since this is not library's issue

**Comment by danielMayberg** [comment]
Alright I'll keep debugging, thanks for all the help! appreciate it @KazuCocoa
