### ISSUE TITLE
element.click doesn't return true anymore

### ISSUE THREAD

**Issue by sshock** [appium/ruby_lib#885]
## The problem

Sometime between appium 1.14.2 and appium 1.15.0, something changed to cause element.click to return `nil`.  Previously it returned `true`.

The assumption we made in our code was that a return value of true indicated the click worked, whereas false or nil maybe meant it couldn't click on the element for some reason.

Was that assumption correct and is it a bug that it no longer returns `true`, or was this changed on purpose because maybe the return value never really had any meaning?  I looked at the release notes for appium 1.15.0 and didn't see anything about this API change.

## Environment

Appium version (or git revision) that exhibits the issue: 1.17.1
Last Appium version that did not exhibit the issue (if applicable): 1.14.2
Desktop OS/version used to run Appium: Ubuntu 18.04.4 LTS
Node.js version (unless using Appium.app|exe): 10.22.0
Npm or Yarn package manager: 6.14.6
Mobile platform/version under test: Android 8.1
Real device or emulator/simulator: real device
Appium CLI or Appium.app|exe: cli

## Details

Here's a quick example from a ruby irb session running appium 1.17.1 that illustrates that click returns `nil` now instead of `true`.  In this example there was a button on the screen and it did click it.

```irb
[4] pry(main)> e = dr.find_element(:xpath => "//android.widget.Button")
=> #<Selenium::WebDriver::Element:0x3f7847fa36841ebc id="62c02638-da74-4ec7-afaa-d3300efec9d6">

[6] pry(main)> x = e.click
=> nil
```

**Comment by sshock** [comment]
Thanks @KazuCocoa .  Before closing this issue, can you confirm how a WebDriver response can and should translate into return values for libraries such as ruby appium_lib?

It makes sense that an HTTP response can have two things (a response code and a body, not to mention headers), but a call to `element.click` in ruby using appium_lib has only a single return value.

The WebDriver spec may very well dictate what an HTTP response look like, but it doesn't dictate what return values in a library like appium_lib should be.

The documentation for `Element#click` makes no mention at all about the return value, leaving it vague: https://www.selenium.dev/selenium/docs/api/rb/Selenium/WebDriver/Element.html#click-instance_method

Perhaps the general pattern is: HTTP status codes from the appium WebDriver endpoint don't usually get reflected in the return values in appium libs, because for error responses they usually turn into exceptions and that is how one would detect them.

As for `click` specifically, since the response from the WebDriver endpoint is always "success with data null", there is no data to worry about returning, so one could easily argue that click should just return nil.  But I think one could also easily argue that it might as well return `true` to indicate success.

What I'm getting at is, it seems arbitrary what `Element#click` should return, and I don't see any rule or documentation to indicate why it should favor returning `nil` over `true`.  But most importantly, I think it should be more clearly documented even if the docs just say "the return value has no meaning and should be ignored".

**Comment by KazuCocoa** [comment]
As ruby_lib/ruby_lib_core (and selenium binding), we won't customise the response in client. It simply returns the server response, `value`, basically. (In some methods handle return value to a proper hash like `app_state` though.)

The return value by server in click is `{"value":null}` JSON and HTTP status code 200 as W3C spec if no error happened. An error case is like `{"value": {"error": "xxx", "message": "xxx", xxx}}` JSON and its HTTP status code.  So, it returns `nil` for now. Probably Appium server returned `{"value": true}` as the response before (but it was wrong format for W3C)

I'd recommend you to override such return value to a value you want in your code if you wanted to override the response.
`::Selenium::WebDriver::Element#click`

**Comment by sshock** [comment]
@KazuCocoa Thanks for the response.  I will close this issue now.  It does make sense that, as a general rule, unless a conversion is necessary for some reason, the "value" field returned by the server in the JSON body becomes the return value of the API call.

It would be nice if the documentation for the ruby client library were updated to be more explicit about #click (and all methods) to state exactly what the return value is, e.g., "#click always returns nil".
