### ISSUE TITLE
Getting a Selenium::WebDriver::Error::InvalidSessionIdError when upgrading rbenv

### ISSUE THREAD

**Issue by jmelki39** [appium/ruby_lib#917]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: Desktop v1.21.0
* Last Appium version that did not exhibit the issue (if applicable): v.1.14.0 Desktop
* Desktop OS/version used to run Appium: mac OS Big Sur v11.6.1
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager: Homebrew
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Real Device Samsung Galaxy S10+
* Appium CLI or Appium.app|exe: Appium.app

## Details

I have been running my Android mobile automation fine for a couple years using Appium Desktop v1.14.0, Ruby on Rails and Cucumber without updating any versions because I know its fragile and I don't want to spend time fixing everything once I upgrade to newer versions. I ended up running `brew upgrade rbenv ruby-build` and it upgraded my rbenv and ruby-build and now my automation has been failing. In my trouble shooting, I upgraded Appium to v1.21.0 and continue to get the same error I was seeing in v1.14.0. I am using rbenv 2.6.3 and `rbenv install' support: /usr/local/bin/rbenv-install (ruby-build 20220125)

## Link to Appium logs

(https://gist.github.com/jmelki39/77237d559d904a1300061f99e9dedb4d)

## Code To Reproduce Issue [ Good To Have ]

I'm not even sure what part of Code to put in here, but I think the issue is with my mobile driver? And this is how I have it setup in the code:

    def initialize_mobile_driver
      $driver = nil

      caps = get_capabilities

      $driver = Appium::Driver.new(caps, true)
      Appium.promote_appium_methods(Support::Screens)

      $driver.start_driver
    end

    def driver_quit
      $driver.driver_quit
    end

**Comment by waynemd** [comment]
@KazuCocoa , i got same issue after I upgrade to appium_lib 12 version (https://github.com/appium/ruby_lib/issues/917#issuecomment-1041757326).  I use ruby 2.7.5 version and it works on the old appium_lib 10 but not on appium_lib 12 with.   what's the solution for it?

**Comment by KazuCocoa** [comment]
Could you share the appium log and ruby log possibly?

I don't know if your case is the global variable thing, but one possible diff between 10 and 12 that could be related to the global driver is the below default value change.
https://github.com/appium/ruby_lib/compare/v10.6.0...v12.0.0#diff-e79205e5a6c4b0bcaf417522b013e796ddb7049c0221f716ede29dce3b65e62dR154

**Comment by waynemd** [comment]
this change here might be a problem

**Comment by KazuCocoa** [comment]
Possibly this is related to Cucumber integration stuff.
I don't know the integration, but if it cannot give the global driver argument properly, `global_driver` as an option to `Appium::Driver.new` will help. e.g.:
```
opts = {
         caps: {
           platformName: :ios,
           app: '/path/to/MyiOS.app'
         },
         appium_lib: {
           wait_timeout: 30
         },
         global_driver: true
       }
appium_driver = Appium::Driver.new(opts)
appium_driver.start_driver
```

https://github.com/appium/appium_capybara/blob/0d30dde8a8548f7c933270958b5cf3ca5978ba6a/example/spec/capybara_init.rb#L12 is when I added `global_driver` in the capybara example.

**Comment by KazuCocoa** [comment]
Probably I could reproduce.
v11 had no issue, so it is in v12 change stuff. Potentially selenium v4 update also affected somewhere, but i haven't figure it out yet.

**Comment by KazuCocoa** [comment]
this was because of v11.2's Ruby 3 update.
https://github.com/appium/ruby_lib/pull/893/files#diff-8ea275ac8a0a8f75d9ffea422eba089783fc7634ab4ef51095dacdef34cf7dc8R207-R210

So, this was not global variables. This was `promote_appium_methods`'s issue.
Then, the previous session's session-id remained in the next session.

This was to avoid redundant definition purpose, but probably unexpected state remained then. So, delete it once -> re-define it may be better.

**Comment by KazuCocoa** [comment]
Could you try the branch out by adding `gem 'appium_lib', git: 'https://github.com/appium/ruby_lib.git', branch: 'remove'` as Gemfile?

**Comment by waynemd** [comment]
@KazuCocoa , the branch works.  Thanks!

**Comment by KazuCocoa** [comment]
12.0.1 has the fix. Please try it out

**Comment by waynemd** [comment]
@KazuCocoa working for me.  thanks for the quick fix and quick release!

**Comment by waynemd** [comment]
@KazuCocoa , this problem reappears on the appium 2.0 version.  I see a lot of 'buttons' is already defined. Skipping to override it.
'first_button' is already defined. Skipping to override it.
