### ISSUE TITLE
Hard coded 'wd/hub' calls to Appium server make it impossible to use this library with Appium 2.

### ISSUE THREAD

**Issue by wlreed** [appium/ruby_lib#948]
## This is a
* [ ] Bug report
* [ ] Question
* [X] Freature Request

## Summary
Hard coded 'wd/hub' calls to Appium server make it impossible to use this library with Appium 2.

## Environment
* Appium version (or git revision): v2.0.0-beta.45
* `ruby_lib` version: 12.0.1
* Mobile platform/version/device under test: iOS, Android

## Actual behaviour and steps to reproduce
1) Start Appium server
2) Use appium_lib to connect to server
3) timeout:  No route found for 'wd/hub/session'

## Expected behaviour
Client connects to server and automation commences

## Link to Appium/Ruby logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
https://gist.github.com/wlreed/0a521e7a0cb896365436c7ad50016b5c

## Any additional comments
Link to hard coded 'wd/hub' calls:
https://github.com/appium/ruby_lib/search?q=wd%2Fhub

**Comment by KazuCocoa** [comment]
What about setting `server_url ` like https://github.com/appium/ruby_lib_core/blob/f415b0981d00fd1e0c223f59f120f3477988d439/test/unit/appium_lib_core_test.rb#L92?
The default URL has `/wd/hub` for backward compatibility yet. Appium 2 can have the url with `--base-path=/wd/hub` as well

**Comment by wlreed** [comment]
Yes, that will work!  How can I find all the parameters for Appium 2?  I have searched, but I have not found the documentation for this.

**Comment by Dor-bl** [comment]
https://github.com/appium/appium#server-command-line-interface

**Comment by KazuCocoa** [comment]
`--base-path` exists in appium v1 as well https://appium.io/docs/en/writing-running-appium/server-args/. So the argument itself does not change, but the default behavior changed a bit. Maybe the listening path is also in the appium log. `appium server --help` also shows the available parameters.

**Comment by KazuCocoa** [comment]
I've updated the readme https://github.com/appium/ruby_lib#start-appium-server as well. This may also help
