### ISSUE TITLE
Double-click action sends incorrect request body

### ISSUE THREAD

**Issue by AaronC81** [appium/ruby_lib#974]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Freature Request

## Summary

When using `driver.action.double_click.perform`, ruby_lib makes a POST request to `/doubleclick` with an empty JSON body.
WinAppDriver does not accept this and reports an unknown error:

```
POST /wd/hub/session/883E3086-A3CC-48D2-8978-B0CD8A450C4D/doubleclick HTTP/1.1
Accept: application/json
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
Connection: close
Content-Length: 2
Content-Type: application/x-www-form-urlencoded
Host: 127.0.0.1:4723
User-Agent: appium/ruby_lib/9.0.0

{}
HTTP/1.1 500 Internal Error
Content-Length: 133
Content-Type: application/json

{"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
```

On the other hand, Appium-Python-Client sends a body with a `sessionId` key, and this works successfully:

```
POST /wd/hub/session/150C0F01-DF0D-40A1-AFDE-70EF79A2A194/doubleclick HTTP/1.1
Accept: application/json
Accept-Encoding: identity
Connection: keep-alive
Content-Length: 53
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:4723
User-Agent: appium/python 1.3.0 (selenium/3.141.0 (python windows))

{"sessionId": "150C0F01-DF0D-40A1-AFDE-70EF79A2A194"}
HTTP/1.1 200 OK
Content-Length: 63
Content-Type: application/json

{"sessionId":"150C0F01-DF0D-40A1-AFDE-70EF79A2A194","status":0}
```

`/doubleclick` also works when sending no body at all, using cURL.

I don't know for certain what WinAppDriver is actually doing with this body, but it looks like the Ruby library should send either an empty body, or a body with a `sessionId` key.

## Environment
* Appium version (or git revision): N/A (WinAppDriver 1.2.1)
* `ruby_lib` version: 9.0.0
* Mobile platform/version/device under test: Windows 10 21H2

## Actual behaviour and steps to reproduce

1. Connect to WinAppDriver
2. Use `driver.action.double_click.perform`
3. Observe the exception on the Ruby end, and an error in the logs of WinAppDriver

## Expected behaviour

Double clicks as expected with no exception

## Link to Appium/Ruby logs

https://gist.github.com/AaronC81/bdd3332168ddbe8b5a3e0cb42c1055a7

**Comment by KazuCocoa** [comment]
https://github.com/search?q=repo%3ASeleniumHQ%2Fselenium+double_click+language%3ARuby&type=code&l=Ruby
The latest selenium client perhaps does not have the endpoint.
